### ISSUE TITLE
When a client sets the cursor on two windows Mir shows wrong cursor

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1000]
In some cases, Mir shows the previous cursor supplied by the client, instead of the current one. This seems to only happen when the are multiple windows (EDIT: multiple windows of the same app). The hotspot is always correct, only the image is wrong (when it should show the I cursor, it will show the arrow but too high).

**Comment by AlanGriffiths** [comment]
Got a reproducer?

**Comment by wmww** [comment]
1. Open `miral-shell`
2. Open two windows of the same client
  * For example, run `gedit --new-window` twice
3. Move the cursor between the two windows a few times until the problem appears

**Comment by wmww** [comment]
The problem might be caused by Mir creating multiple `ms::CursorStreamImageAdapter`s for the same `mc::BufferStream`. GTK will use the same cursor surface for multiple toplevel surfaces.  Each toplevel surface the cursor is used for makes a new adapter. Each adapter sets the stream's `frame_posted_callback`, which might be a problem if more than one adapter is hooked up at a time.

**Comment by AlanGriffiths** [comment]
> The problem might be caused by Mir creating multiple `ms::CursorStreamImageAdapter`s for the same `mc::BufferStream`. GTK will use the same cursor surface for multiple toplevel surfaces. Each toplevel surface the cursor is used for makes a new adapter. Each adapter sets the stream's `frame_posted_callback`, which might be a problem if more than one adapter is hooked up at a time.

That sounds like Mir is handling leave/enter inconsistently with Mutter.

From the description of `enter` "When a seat's focus enters a surface, the pointer image is undefined" - I strongly suspect Mir retains the same pointer window from any earlier `set_cursor` (which is clearly consistent with "undefined", but likely different than Mutter.)

I still can't imagine why this interpretation of "undefined" would be problematic unless we are seeing updates to the pointer surface out of sequence.

**Comment by wmww** [comment]
No. GTK is setting the cursor immediately, not leaving it undefined. Mir is just wrong.
