### ISSUE TITLE
The Mir-on-X platform relies on mesa

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1012]
We've a "mir-on-X11" platform that relies on mesa for buffer allocation. That means it doesn't work on "supported" non-mesa stacks such as Nvidia's eglstream.

**Comment by wmww** [comment]
Possibly the cause of #914?

**Comment by AlanGriffiths** [comment]
> Possibly the cause of #914?

Why would you think that?

**Comment by wmww** [comment]
Because the VM failure happens in the mesa buffer allocator
