### ISSUE TITLE
Setters incorrectly exposed in miral::WindowInfo

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1031]
`miral::WindowInfo` has setters exposed in the public interface. These set the internal `WindowInfo` state, but do not update the actual window properties as a user might expect.

This ties into other problems such as `WindowInfo` having a potentially different state than the underlying `scene::Surface`, and the confusing distinction between `Window` and `WindowInfo`.

Since users already *shouldn't* be calling these functions, we may be able to get away with deprecating them and making them throw without an ABI break. We should also talk about either replacing `WindowInfo::Self` with `scene::Surface`, or giving `BasicWindowManager more privileged access to it than we expose in the public interface.

**Comment by AlanGriffiths** [comment]
Could you be specific here?

As discussed before, we're partway through removing legacy attributes from `Surface` that belong on `WindowInfo` where the latter is the only thing that needs to hold it. (That work got interrupted a couple of years ago, and has yet to be resumed.)

As you don't specify the setters concerned, it is unclear whether "users already shouldn't be calling these functions" or "these properties need to be removed from `scene::Surface`".

**Comment by wmww** [comment]
It appears to me that **NO** window property setters should be exposed in the public MirAL interface. As `BasicWindowManager is currently designed, users of MirAL should call `modify_window()` to change window properties.

**Comment by AlanGriffiths** [comment]
Fixed in Miral 3.0
