### ISSUE TITLE
wl_subsurface.visiblity not implemented

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1032]
When running Gedit and opening the hamburger or open menus, I get a bunch of lines like this:
```
[2019-10-07 21:02:18.676892] < -warning- > mirserver: TODO: wl_subsurface.visiblity not implemented
```
I haven't actually observed any incorrect behavior. Quite possibly an easy fix

**Comment by AlanGriffiths** [comment]
I've not seen this for a long time. Certainly predates 1.8.
