### ISSUE TITLE
non-input event type 11 warning

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1047]
Mir generates warnings like so:
```
[2019-10-14 16:20:32.865246] < -warning- > mirserver: WaylandSurfaceObserver::input_consumed() got non-input event type 11
```
The event it's referring to is `MirInputDeviceStateEvent`. It appears this event may be able to replace pieces of #1035.

**Comment by AlanGriffiths** [comment]
Thanks for noting this. Assuming this event happens at the right times (looks like it should) then it it a better approach. It ought to address other re-sync scenarios too.
