### ISSUE TITLE
Displacement/DeltaX/DeltaY should be replaced by Size/Width/Height

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1064]
I often end up blindly converting between deltas and sizes, and rarely if ever has this distinction caught a bug for me. I don't completely understand what the conceptual difference is. In the current implementation `Width - Width -> DeltaX`, but `Width - Width -> Width` would also make perfect sense (for example, `screen_width - panel_width -> maximized_window_width`). Also, I propose `Size + Size -> Size`, `Point + Size -> Point` and `Point - Size -> Point`. Basically, I think it makes sense to use sizes in every context we currently use displacements, and removing displacement will make code easier to write, easier to read, faster to compile, and actually *less* prone to bugs (because it's easier to spot them without `as_size()`, `as_displacement()` scattered everywhere).

**Comment by AlanGriffiths** [comment]
There are issues with these types, but I don't think the answer is _clearly_ conflating "displacement" and "size", that may be a meaningful distinction.

Consider an alternative resolution: "size" _IsA_ "displacement" and make "size" explicitly constructable from "displacement". To cover your examples:

Expression|Meaning
--|--
`Width - Width`|`operator-(DeltaX, DeltaX) -> DeltaX`
`Size + Size -> Size`|`operator+(Displacement, Displacement) -> Displacement`
`Point + Size -> Point`|`operator+(Point, Displacement) -> Point`
`Point - Size -> Point`|`operator-(Point, Displacement) -> Point`

There should be no need for `as_displacement()` - that ought to be an implicit conversion.
We'd keep `as_size()`, or equivalently have an `explicit Size(Displacement)` constructor.

**Comment by wmww** [comment]
Adding an implicit conversion from `Size` to `Displacement` may be a good idea, but what you propose has issues. For example it wouldn't allow `Size + Size + Size` or `Size - Size - Size` (since the first expression would return a `Displacement`, which can't be added or subtracted from `Size`). I think it would be enough to have implicit `Size -> Displacement` conversion __and__ add operators for `Size + Size -> Size` and `Size - Size -> Size`.

**Comment by wmww** [comment]
Oh, true. I think `Width + Width -> Width`, `Width - Width -> Width` (and same for height) makes sense, but I didn't consider how that fails to transfer sensibly to `Size`.

**Comment by AlanGriffiths** [comment]
Shrug
