### ISSUE TITLE
mir doesn't build on latest Arch

### ISSUE THREAD

**Issue by vanyasem** [MirServer/mir#1084]
https://paste.ubuntu.com/p/GgwGncQzRD/

**Comment by wmww** [comment]
I'll be back home to my Arch box day after tomorrow

**Comment by RAOF** [comment]
Interesting!

This is in platform code that we want to remove; I'm not how much effort we want to go to fix this before then.

**Comment by vanyasem** [comment]
This happens in both the release version and when built from git. Is there maybe a workaround you can suggest?

**Comment by vanyasem** [comment]
Answering my own question - it's possible to build mir by setting `MIR_FATAL_COMPILE_WARNINGS` to `OFF` and enforcing `-fpermissive`. A nasty workaround, but gets the package built. Considering platform code is to be removed, it might not be that bad

**Comment by vanyasem** [comment]
A few more errors - https://paste.ubuntu.com/p/jym6KhcZ8d/

**Comment by vanyasem** [comment]
This is a patch I came up with which worked for me
```
diff --git a/include/renderers/gl/mir/renderer/gl/egl_platform.h b/include/renderers/gl/mir/renderer/gl/egl_platform.h
index 9e3201a4d7..3cf2fd0216 100644
--- a/include/renderers/gl/mir/renderer/gl/egl_platform.h
+++ b/include/renderers/gl/mir/renderer/gl/egl_platform.h
@@ -19,7 +19,9 @@
 #ifndef MIR_RENDERER_GL_EGL_PLATFORM_H_
 #define MIR_RENDERER_GL_EGL_PLATFORM_H_
 
-typedef void* MirServerEGLNativeDisplayType;
+#include <EGL/eglplatform.h>
+
+typedef EGLNativeDisplayType MirServerEGLNativeDisplayType;
 
 namespace mir
 {
```

**Comment by vanyasem** [comment]
I believe it's a bug also affecting Ubuntu, but I also had to apply this patch:
```
diff --git a/src/platforms/wayland/platform.cpp b/src/platforms/wayland/platform.cpp
index c7cd62316d..ce5d6672f1 100644
--- a/src/platforms/wayland/platform.cpp
+++ b/src/platforms/wayland/platform.cpp
@@ -59,7 +59,7 @@ mg::NativeDisplayPlatform* mgw::Platform::native_display_platform()
 
 EGLNativeDisplayType mgw::Platform::egl_native_display() const
 {
-    return eglGetDisplay(wl_display);
+    return eglGetDisplay((NativeDisplayType)wl_display);
 }
```

**Comment by wmww** [comment]
We seem to be effected by https://github.com/protocolbuffers/protobuf/issues/4186

**Comment by wmww** [comment]
Combining #1087 and #1088 should get it building

**Comment by vanyasem** [comment]
@wmww can confirm that. tested in a clean building chroot

**Comment by wmww** [comment]
Both these PRs have merged
