### ISSUE TITLE
What is the right behavior if WAYLAND_DISPLAY and the lockfile exists?

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1163]
It is normal for a Wayland compositor to create the socket specified by WAYLAND_DISPLAY, and for clients to connect to the socket specified by WAYLAND_DISPLAY.

But, if there's another compositor already servicing WAYLAND_DISPLAY, Mir cannot do this and fails to start (with a verbose error message).

Should it check for the lockfile? And if it finds one, should it treat the other compositor as a host and choose another? That seems both convenient and unexpectedly clever.

By comparison if WAYLAND_DISPLAY is not set and wayland-0.lock exists, Mir (courtesy of libwayland) selects wayland-1 (etc.) and starts using Mir-on-X.

**Comment by wmww** [comment]
Yes, that sounds like reasonable behavior. It may make sense to have a Mir option to force Mir to try to run on a specific display and fail otherwise. The `WAYLAND_DISPLAY` variable could be treated as a hint in it's absence.

**Comment by AlanGriffiths** [comment]
@wmww note that the behavior implemented by https://github.com/MirServer/egmde-snap/pull/10 is subtly different to that described above.
 
If WAYLAND_DISPLAY and the lockfile exists then it unsets WAYLAND_DISPLAY. Consequently, Mir (courtesy of libwayland) selects wayland-1 (etc.) and starts using either the "mesa-x11" or the "wayland" platform (they both return `PlatformPriority::supported`).

**Comment by AlanGriffiths** [comment]
Over the course of time we've settled on the following:
1. The Mir libraries respect `WAYLAND_DISPLAY` if it is set and fail if there's a conflict (as described above);
2. Various launcher scripts (miral-app, snaps, test runners etc,.) check whether `WAYLAND_DISPLAY` is set and the file exists:
2.1. Some scripts convert an existing `WAYLAND_DISPLAY` to a `--wayland-host` and unset `WAYLAND_DISPLAY`,
2.2. Some scripts unset `WAYLAND_DISPLAY`,
2.3. Some scripts set `WAYLAND_DISPLAY` to a unique value
This seems to resolve any problems as to the correct behaviour.
