### ISSUE TITLE
Mir fails to close when XWayland app is running

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1169]
To reproduce:
1. Run `mir_demo_server` with a `--x11-display-experimental` (only tested with Mir-on-X)
1. Run an X11 app on the XWayland display
1. Close Mir with Ctrl+Alt+Backspace
1. X11 app is killed but the Mir window doesn't close

Note that there isn't a problem if you close the X11 app before attempting to close Mir.

**Comment by wmww** [comment]
It appears this was introduced somewhere in #1160, although Mir was fatal erroring previously. Neither of those behaviors are preferable.

**Comment by AlanGriffiths** [comment]
Actually, if you wait, it still crashes. The new, incorrect, behavior is to make several (failing) attempts to restart the Xwayland server.
