### ISSUE TITLE
XWayland: need XWayland executor

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1174]
@AlanGriffiths This is less of an issue and more of a request that I'm dropping here instead of IRC in case your client is offline. Since none of the XWayland classes are threadsafe, any calls into them should probably be made on the XWayland thread. For example `XWaylandWMShellSurface::handle_resize()` is called on the Wayland thread, and it should delegate `surface->send_resize(new_size)` to the XWayland thread instead of calling it directly as it currently does. I'm in the middle of writing most of the code to make this happen, but there is no XWayland executor and I'm not sure how to make one. There are similar issues in the other direction, but we have a Wayland executor so I can handle that.

**Comment by AlanGriffiths** [comment]
@wmww to clarify:

What are you referring to as "the XWayland thread"? `XWaylandServer::spawn_thread`? That just spawns the Xwayland process and waits for it to terminate.

Other than that, we've got much the same situation as in frontend_wayland: client-initiated calls on the wayland thread and Mir-initiated calls on other threads. I think the same solution we use there can be applied for most of this (migrate the calls to the Wayland executor).

The only exception to that is possibly the  `xcb_*` calls made by the X Window Manager? If any of those could be blocking then we might need an additional executor in `XWaylandWMSurface`.

Are we on the same page? Or have I misunderstood your concerns?

**Comment by AlanGriffiths** [comment]
Ah! I missed `XWaylandWM::event_thread`. Is that what you meant?

**Comment by wmww** [comment]
That's all good info. I'm still not entirely sure how many threads there are and what they do, but it's good to know what the spawn thread is for, and that it's not what I want. I believe I want an executor on the event thread. As I said there doesn't seems to be any locking in the XWayland frontend, which implies each object should be accessed on a specific thread. It seems to me most of the XWayland frontend including `XWaylandWMSurface` should be on some sort of XWayland thread (probably the event thread you mentioned?). `XWaylandWMShellSurface` needs to be on the Wayland thread, and talk between the two needs to be routed through executors. Thus the need for an XWayland event thread executor.

**Comment by AlanGriffiths** [comment]
> each object should be accessed on a specific thread

That's an oversimplification. Immutable state can be accessed from any thread. Only mutable state that needs care by using atomics or mutexes or restricting access to a single thread.

Introducing and coordinating threads is expensive, and not the solution of first resort. Adding threads makes most sense to avoid blocking IPC calls, or for using non-threadsafe APIs (like libwayland), or thread aware ones (like GL).

As is clear from a lot of the recent cleanup there's a lot of immutable state that hasn't been marked const (or isn't initialized on creation). I think there's more we can do in this direction.

**Comment by wmww** [comment]
Alright, I will make the XWayland classes threadsafe rather than having a dedicated XWayland thread with an executor.
