### ISSUE TITLE
X11: pointer position not mapped correctly

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1178]
Open xeyes and xterm and position the windows well apart.

Move the mouse cursor over xterm.

Expect: the eyes follow the cursor.
Actual: the "eyes" move as though the cursor were over xeyes

**Comment by AlanGriffiths** [comment]
To expand a bit: Wayland sends the cursor movements to the window under the cursor in surface co-ordinates. Wayland clients (and that includes Xwayland) don't have knowledge of the window positions. So I don't think this is trivial to get working.

But it does work with GNOME Wayland and Xwayland.

**Comment by wmww** [comment]
Fixed by #1245
