### ISSUE TITLE
QtMir shell dies on Mir-on-X when mapping AnonymousShm file

### ISSUE THREAD

**Issue by gerboland** [MirServer/mir#120]
With:
1. latest Mir (0.29 at writing)
2. QtMir from https://github.com/ubports/qtmir using the "xenial_-_mir29" branch

In a Terminal, we want to test QtMir with Mir-on-X, so run
          ./demos/qml-demo-shell/qtmir-demo-shell

It fails for me with "Failed to map file: Invalid argument" which is coming from mir::AnonymousShmFile constructor.

**Comment by gerboland** [comment]
I'm still seeing this with Mir trunk and UBPorts on Bionic:
http://pastebin.ubuntu.com/p/gXpsjVZyq8/
I'll look to see why.

**Comment by gerboland** [comment]
Problem is that we were trying to mmap a file of zero length, which you can see from frame 3 of the backtrace.

**Comment by gerboland** [comment]
The issue is how QtMir disables Mir's cursor, it implements mir::graphics::CursorImage to supply an empty image (size 0x0) in a class named "qtmir::NamedCursor".  Mir tries to mmap memory for it, and naturally mmap chokes on the 0 size.

What I'm trying to figure out is how to avoid that. Is calling mg::SoftwareCursor::show on a CursorImage which is zero sized wrong? I.e. should it throw on a null cursor? 
My workaround is mg::SoftwareCursor::show(CursorImage) checking the size before trying to make a renderable for it, but it doesn't feel right. Opinions welcome

**Comment by AlanGriffiths** [comment]
It seems to me that disabling Mir's cursor by giving a software cursor an empty image is simply a bad idea. We should support "--cursor null"  in addition to "--cursor sofware" and "--cursor auto"

**Comment by AlanGriffiths** [comment]
@wmww this is the bug we were telling you about last night

**Comment by gerboland** [comment]
I'd consider this fixed, the ball is in QtMir's court to use a different Mir api to request a hidden cursor.

One (bad) option is setenv("MIR_SERVER_CURSOR", "null", 1)...

**Comment by vanyasem** [comment]
@gerboland Next time when you do something like that I suggest you to open an issue on the affected repo ;)
