### ISSUE TITLE
Restored windows do not get resized properly

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1209]
Repro:
1. Open Gedit in XWayland
2. Maximize 
3. Unmaximize

Expected: window becomes restored and the size it was before the maximize

Actual: window becomes restored, but keeps the maximized size an position

**Comment by AlanGriffiths** [comment]
I've seen X11 windows fail to restore like this, so I agree there's an issue. But this "Repro" doesn't work for me. E.g. with egmde --edge:

1. Start Terminal
2. `GDK_BACKEND=x11 gedit`
3. Double click titlebar - window maximizes
4. Double click titlebar = window restores (to original size)

Similarly with using the "maximize" icon.

Also tried `miral-app -demo-server --x11-display 3`/`DISPLAY=:3 GDK_BACKEND=x11 gedit`

**Comment by wmww** [comment]
Looks like I didn't check against current master before opening this. It does indeed appear to be fixed already.

**Comment by wmww** [comment]
Hmm... appears to have been fixed by 514352bc49d01c487c7a148a072ddedc5c5b5d00
