### ISSUE TITLE
XWayland: windows can not request a change in state

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1210]
The maximize/minimize controls on Gedit don't work on XWayland (but SSDs do)

**Comment by AlanGriffiths** [comment]
I'm unclear what this means. Are you configuring GDK to use X11 (which adds SSD) and also CSD?

**Comment by AlanGriffiths** [comment]
OK, got it - you mean gedit's CSD titlebar.

**Comment by wmww** [comment]
Sorry, I didn't write that clearly. I'm running Gedit with `GDK_BACKEND=x11`. Gedit provides CSDs and Mir provides SSDs (the double decorations in this case is an issue for another day).
