### ISSUE TITLE
WaylandSurfaceObserver destroyed flag not threadsafe

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1216]
`WaylandSurfaceObserver` makes heavy use of the "run unless a `shared_ptr<bool>` is true" paradigm. This would be fine if the destroyed flag was only accessed and set on the Wayland thread, but `*destroyed = true` is in the destructor. The surface (and thus also the observer) may be destroyed on any number of threads.

Even making the destroyed flag atomic wouldn't fix the problem, because:
1. Wayland thread checks `destroyed` is false
1. Non-Wayland thread deletes the observer and sets `destroyed` to true
1. Wayland thread function continues using the observer, unaware anything happened

What we would really need is a mutex that is locked in the destructor when setting `destroyed` and also for the duration of all operations in the observer when we are assuming it isn't destroyed. However, this is ugly and there may be a better way.

I haven't observer any bugs steaming from this issue, but if there are any they would likely be extremely hard to reproduce so I think we should deal with it anyway.

**Comment by RAOF** [comment]
So, I think that [`SharedWlBuffer`](https://github.com/MirServer/mir/blob/e12a1f404bd01d5c94258599823a4ec2b1be1b0e/src/platforms/common/server/buffer_from_wl_shm.cpp#L106) could be abstracted into a `SharedWlResource`; that would be an implementation of one of our proposed “how do we make interacting with libwayland less awful” architectures.

**Comment by wmww** [comment]
A potential issue with that is that the `WaylandInputDispatcher` must not outlive the seat it was created with. If we were using a sort of shared ownership model then the final cleanup could come after other important stuff has been destroyed and there might be room for events to get fired in between.

**Comment by wmww** [comment]
If we switch surfaces to using the `ObserverRegistrar` system, that will do all the hard work of sending all notifications on the Wayland thread and not sending notifications after we have removed the observer.

**Comment by RAOF** [comment]
> A potential issue with that is that the `WaylandInputDispatcher` must not outlive the seat it was created with. If we were using a sort of shared ownership model then the final cleanup could come after other important stuff has been destroyed and there might be room for events to get fired in between.

If the `WaylandInputDispatcher` took the seat as a `SharedWlResource` that would be easy - you'd attempt to lock the seat and get something that evaluates to `false`.

**Comment by wmww** [comment]
Looks like this issue has been fixed. We now use `run_on_wayland_thread_unless_window_destroyed()`, which moves to the Wayland thread before making any checks. `~WaylandSurfaceObserver()` is empty.
