### ISSUE TITLE
XWayland keyboard state not cleared

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1236]
1. Open a window with XWayland
2. Hold a key down
3. Close the window
4. Release the key
5. Open the window again (or a window of a different app)

Expected: no keys are down

Observed: the key is stuck down until pressed again

**Comment by AlanGriffiths** [comment]
To reproduce it is important to have no other windows open. E.g.

mir_demo_server --x11-display 3&
sleep 1; DISPLAY=:3 xterm

**Comment by wmww** [comment]
I believe the problem is that before a surface is destroyed we send a `wl_pointer.leave()` event, but not a `wl_keyboard.leave()` (or `wl_touch.leave()`). XWayland continues to think the keys are held down, which results in this and also in spamming `roundtrip`s
