### ISSUE TITLE
[X11] When using CLion the keyboard focus gets screwed up

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1274]
When editing code in CLion (under our X11 support on master).

When typing "tooltips" are shown, e.g. for completion. These appear and disappear as you type.

Sometimes, while this is happening, the input cursor disappears and typing has no effect. But up/down arrows change the highlighted line.

A mouse click restores the cursor and normal function.

(Not sure if this is CLion specific or if it could affect other Java based UIs.)

**Comment by AlanGriffiths** [comment]
or a simple reproducer:

1. Create a new C++ project (C++ Executable)
2. Move cursor to body of main
2. Type "for (auto "

By this time we should be in the weird state described.

**Comment by wmww** [comment]
I love how Java sets `WM_NAME`, `_NET_WM_NAME`, `WM_ICON_NAME` and `_NET_WM_ICON_NAME` to the same very long value after every keystroke. And of course we don't cache that so we send a `modify_window()` on every keystroke.

**Comment by wmww** [comment]
I think I know what's going on. In some situations, CLion/IntelliJ tears down a popup then immediately creates a new one. As the first one gets destroyed, we set input focus to the parent. Somehow that's interfering with the creation of the new popup, and we're left in a bad state. If I stop setting input focus to the parent it fixes the problem but breaks other apps. Looking into a better solution.

**Comment by wmww** [comment]
Ah! removing the hack in abstract_shell.cpp mentioned in #1295 also fixes it

**Comment by wmww** [comment]
Feel free to release once current PRs are merged. A few of the XWayland issues still pose a serious threat to usability, but those aren't getting fixed this week.
