### ISSUE TITLE
[X11] Cursor input sometimes "goes through" the top window

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1275]
I've seen this most often starting Firefox and CLion using X11 (using egmde --edge Firefox needs to be forced by starting with BkSp or it starts with Wayland).

With CLion over Firefox right clicking brings Firefox to the top and shows a context menu.

**Comment by wmww** [comment]
My theory is that we aren't keeping the stacking order synced between Mir and XWayland, so XWayland thinks FF is on top (and thus gives it input) when Mir is showing it below.

**Comment by AlanGriffiths** [comment]
Another scenario in which the "stacking order" problem manifests is using Mir Shell workspaces.

1. Log into "Mir Shell"
2. Start a terminal: `Ctrl-Alt-T`
3. Launch an X11 app: `hexchat`
4. Launch another X11 app: `clion`
5. Move the second app to another workspace: `Ctrl-Meta-F2`
6. Return to first workspace: `Alt-Meta-F1`
7. Right click on first app (hexchat)

Expect: context menu appears on hexchat
Actual: context menu appears on clion (when switch workspace - `Alt-Meta-F2`)
