### ISSUE TITLE
Can not close xterm when launched by Mir

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1284]
If xterm is launched with Ctrl+Alt+X, clicking the `X` on the SSDs does nothing. If it is launched externally, it closes the window as you would expect.

**Comment by wmww** [comment]
It's sending the correct `WM_DELETE_WINDOW` request in both cases. Kate, Gedit, PCManFM and xeyes all close fine when launched via `external_client_launcher.launch_using_x11()`. No clue what's going on here.

**Comment by wmww** [comment]
It seems to be passed down through the environment or a similar process (xterms launched by a mir-launched xterm also can't close), but I can't reproduce with an externally launched terminal even after copying all possibly relevant variables from the environment reported by the xterm launched from Mir.

**Comment by AlanGriffiths** [comment]
How about xterm launched from a Mir launched gnome-terminal?

PS This must be recent, I've been doing this all week.

**Comment by wmww** [comment]
Good idea, I'm curious

**Comment by AlanGriffiths** [comment]
I cannot reproduce this on 18.04.

**Comment by AlanGriffiths** [comment]
> Reproduced on 20.04.

Still happening. Weird that the way it is launched affects using the X icon.

**Comment by AlanGriffiths** [comment]
Still happens on 22.04

**Comment by AlanGriffiths** [comment]
> And, interestingly, launching with "sh -c xterm" doesn't exhibit a problem.

On the other hand `sh -c 'exec xterm'` does exhibit the problem. I suspect this something carried over through fork/exec. (e.g. signal handling)

**Comment by AlanGriffiths** [comment]
Confirmed: `killall xterm` doesn't work for the xterm started by Mir
