### ISSUE TITLE
Clipboard not implemented for X11 clients

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1312]
> This is about making X11 apps as functional as Wayland apps in this regard, so allowing `Ctrl`+`C`/`Ctrl`+`V` copy/paste between them, and between them and Wayland apps.

**Comment by AlanGriffiths** [comment]
Are you referring to offering Wayland's copy/paste to Xwayland? Or X11 copy/paste to X11 clients?

Alsn, there are several copy/paste protocols around the desktop world. Is this about primary buffer (which we don't currently support on native Wayland either) or clipboard?

**Comment by wmww** [comment]
This is about making X11 apps as functional as Wayland apps in this regard, so allowing `Ctrl`+`C`/`Ctrl`+`V` copy/paste between them, and between them and Wayland apps.

**Comment by wmww** [comment]
Fixed by  #1892. #1905 improves it and further improvements for incremental copy are on the way, but I think this can be closed.

**Comment by AlanGriffiths** [comment]
> Fixed by #1892. #1905 improves it and further improvements for incremental copy are on the way, but I think this can be closed.

You intended to close this right?
