### ISSUE TITLE
[Mir-on-X] Cursor movement mapped incorrectly

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1314]
Likely not all of this setup is required, but this is how I got there...

0. Install mir-demos, mir-graphics-drivers-desktop from ppa:mir-team/rc
1. create a `.config/miral-shell.config` with the line `window-manager=tiling`
2. Log in to "Mir Shell"
3. Open a terminal `Ctrl-Alt-T`
4. Install mir-kiosk: `sudo snap install mir-kiosk`
5. Run mir-kiosk `env -u WAYLAND_DISPLAY mir-kiosk`
6. Install mir-kiosk-neverputt: `sudo snap install mir-kiosk-neverputt`
7. Check which WAYLAND_SOCKET mir-kiosk provides and run `WAYLAND_DISPLAY=wayland-0 mir-kiosk-neverputt`

Expect: the mouse drawn by neverputt moves with the mouse drawn by miral-shell
Actual: the mouse drawn by neverputt moves to reflect the actual screen position (when the cursor is on the Mir-on-X window)

**Comment by AlanGriffiths** [comment]
OK, this seems to be an issue with the display size reporting from the Mir-on-X11 platform. We're forcing the Mir-on-X11 window to resize into a tile, but that isn't being reported through mir-kiosk to the neverputt client.

I don't think it is being reported by the Mir-on-X11 platform at all, as that doesn't expect the window to be resized.

A workaround is to specify a `--x11-output` that is smaller than the tile.

**Comment by wmww** [comment]
I can confirm that this has always been a problem

**Comment by AlanGriffiths** [comment]
There is a comment in #1914 saying this is fixed, but while it has improved a lot, **it still misplaces the cursor in the scenario described**.

Initially, the panel containing neverputt mismatches the size of the content drawn by neverputt (which is vertically centered), The mismatch is by the size of the upper margin. Creating additional windows and switching between them leads to a bunch of weird displacements.

**Comment by wmww** [comment]
I think this is the same thing I've been looking into recently because I see it in Sway and i3. I will take care of it (but perhaps not until after the XCB port lands).

**Comment by wmww** [comment]
`mir-kiosk-neverputt` doesn't seem to be working for me. When run normally it fails with
```
Failure to initialize SDL (Could not initialize UDEV)
```
when run with sudo it seems to start, but it just freeses and it or Mir never show up.

Can you check if this is still an issue?

**Comment by AlanGriffiths** [comment]
> Failure to initialize SDL (Could not initialize UDEV)

Is `hardware-observe` connected?

**Comment by wmww** [comment]
I'm not sure what that means, so probably not?

**Comment by AlanGriffiths** [comment]
> I'm not sure what that means, so probably not?

It is a snap interface that SDL2 (spuriously) requires to be connected.

Run `/snap/mir-kiosk-neverputt/current/bin/setup.sh` to set up the required interfaces.

I'll make look into improving the help message.

**Comment by wmww** [comment]
Ah! That fixed it.

I'm unable to reproduce this problem on current Mir master with the steps provided. Everything seems to work fine to me.
