### ISSUE TITLE
Firefox/Wayland flickers badly

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1316]
1. Log in to "Mir Shell"
2. Start a terminal: `Ctrl-Alt-T`
3. Run `firefox`

Expect: firefox to work without flickering
Actual: firefox flickers when initially displayed, when typing into search bar, when mouse moves over it

Not seen on GNOME/Wayland when starting Firefox with:

`env -u DISPLAY GDK_BACKEND=wayland firefox`

**Comment by AlanGriffiths** [comment]
I've seen this with Intel platform, also reported with Nvidia

**Comment by wmww** [comment]
Not present on all Intel platforms. I am posting this from Firefox on Wayland on Mir master on Intel on updated 20.04, and there is no problem.

**Comment by wmww** [comment]
My Arch Oryx has the problem (even on Intel) but my Ubuntu XPS does not. I discovered that enabling WebRender seems to fix it on Arch, but Ubuntu doesn't *appear* to have it either way. Could be some other configuration I've set on Ubuntu, as others on the same distro do experience the issue.

**Comment by AlanGriffiths** [comment]
> My Arch Oryx has the problem (even on Intel) but my Ubuntu XPS does not. I discovered that enabling WebRender seems to fix it on Arch, but Ubuntu doesn't _appear_ to have it either way. Could be some other configuration I've set on Ubuntu, as others on the same distro do experience the issue.

Or, maybe, the mesa driver that is selected?

**Comment by wmww** [comment]
My working theory is that Firefox is relying on the compositor only using the sections of the buffers it says are damaged. Mir uses the whole buffer. It appears Mir has a right to do this, but we might consider implementing damage anyway. Firefox on Wayland in Weston is also broken, though possibly slightly less so. Firefox on Wayland on Sway works fine.

**Comment by wmww** [comment]
I have discussed this with the Firefox devs and filed a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1637397. Depending on how long that takes to resolve we still may want to consider implementing damage.

**Comment by wmww** [comment]
For now anyone who needs a workaround can enable WebRender (set `gfx.webrender.all` to `true` in `about:config`). WebRender is theoretically less stable, but I've found it perfectly usable for a while.

**Comment by AlanGriffiths** [comment]
> For now anyone who needs a workaround can enable WebRender (set `gfx.webrender.all` to `true` in `about:config`).

Excellent, that is enough of a hint for me to get a working browser is a confined desktop snap. \o/

**Comment by AlanGriffiths** [comment]
The [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1685263) was fixed a year ago
