### ISSUE TITLE
Flicker when multiple outputs are connected

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1317]
Observed on my XPS running 20.04. When an external monitor is connected and windows are on both outputs, both tend to flicker and sometimes get the content of each other. It is especially bad when a window is being dragged between the two outputs.

**Comment by wmww** [comment]
When the window has a subsurface (such as the gedit open dropdown), the main window and the subsurface sometimes end up separated (one on the correct output, the other in the correct position but on the wrong output). Since subsurfaces are all part of the same Mir `BasicSurface`, this indicates to me the bug happens after  renderables have been created by the surface.

**Comment by wmww** [comment]
Observed on the X11 platform as well

**Comment by AlanGriffiths** [comment]
@wmww on #1332 I discovered similar problems that exist only on master. Is that also the case here?

**Comment by AlanGriffiths** [comment]
Not reproduced with egmde-snap/edge on 18.04 or 16.04. (Likely fixed by #1343)
