### ISSUE TITLE
HiDPI support for X11 apps

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1367]
When HiDPI support lands X11 apps will get scaled up, but will be low resolution. From sway I know it's possible to scale them correctly. Not a priority at the moment.

**Comment by RAOF** [comment]
FWIW, KWin also fails to correctly scale HiDPI apps.

This is annoying, as CLion is an XWayland app and so is all blurry on my laptop :grinning:

**Comment by wmww** [comment]
Attaching these two X PRs, which seem relevant (though hopefully we'll have a solution before they merge): https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/111, https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/432

**Comment by wmww** [comment]
It seems I was incorrect in the call earlier today. Sway does __not__ support HiDPI on XWayland. It seems the change I was thinking of that caused my problem to go away was me purchasing a normal DPI laptop.

The status quo is that there is no way to know the scale of an XWayland app, so all XWayland apps must be scaled the same. Currently Sway requests them render at 1x scale and then stretches the buffers. This gives consistent but blurry results.

There is a [proposal](https://github.com/swaywm/sway/pull/5090) to requests the correct scale and assume apps respect it. Apps that don't respect X11 scaling will then render smol.

This tradeoff exists when running X11 natively as well, either all apps are lower resolution or some apps are not scaled. I assume GNOME is taking the latter approach, and that's what we want to do until a real fix is ready on the X11 side (which could be a very long time). I will look into how to do that.
