### ISSUE TITLE
Popups always appear on output with majority of window

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1408]
As you can see, popups select the output that holds the majority of their parent window, even if they would entirely fit on another output.
![a](https://user-images.githubusercontent.com/9331264/78680025-f6e8f800-78b8-11ea-8751-6a8d9d4c2455.png)

**Comment by AlanGriffiths** [comment]
That's weird. None of the miral popup placement code should be "output aware".

**Comment by wmww** [comment]
Um.. yes it should? That's a major consideration in placing popups.

**Comment by AlanGriffiths** [comment]
Cannot reproduce this year

**Comment by AlanGriffiths** [comment]
> Cannot reproduce this year

Correction, reproduced using egmde-snap/edge as the shell on 18.04.

**Comment by AlanGriffiths** [comment]
Right, this placement logic stems from the Unity8 days when it was enforced that windows could not span outputs.

But that's not what we should have for the "floating" window manager. I suspect we should be taking the display area that contains the anchor rect, not the one that contains the parent.
