### ISSUE TITLE
Google Meet crashes firefox tab when run on Xwayland on Mir Shell

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1415]
Running 1.8.0 rc54 built on Fedora and logged into "Mir Shell", I tried to join a Google Meet.

At the point of joining the meeting, the firefox tab crashed.

**Comment by wmww** [comment]
I reproduced on both 18.04 and Arch. Firefox on Wayland tabs don't crash, but do have that awful flicker. Neither issue exists on Sway.

**Comment by AlanGriffiths** [comment]
Can no longer reproduce (tested on 2.0 & master).
