### ISSUE TITLE
Fake news: Mir 1.8.0 reports itself as 1.7.2

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1422]
See CMakeLists.txt:31 for the source of fake news

**Comment by wmww** [comment]
\* wmww wonders if it might be possible to write tests that will fail if the changelog, cmake version, git tags and any other potential version indicators don't match

**Comment by AlanGriffiths** [comment]
Of course it is _possible_.

Even better would be a "single source of truth". (I had a branch for that some time ago, but it never landed...)

**Comment by Saviq** [comment]
In Multipass we've decided for git tags to be the single source of truth. It works fine there, but has the disadvantage that you don't get that when working with just a tarball - which I think is a requirement for Mir.

In Mir there are at least three sources:
1. `CMakeLists.txt`
1. `debian/changelog`
1. git tags

I don't think we _can_ get rid of 1., I don't think we _should_ get rid of 3.

There is some potential to automate 2. and 3., though…

**Comment by AlanGriffiths** [comment]
4. The name of a `release/[0.9]*\.[0.9]*` branch

**Comment by AlanGriffiths** [comment]
We _should_ not get rid of 1, but we *could* (by scraping 2).

Because we expect packaging from tarballs without using `debian`, I think 1 should be the truth.

We can likely add consistency checks for the other, but the criteria might differ between `master` (or most PRs) and `release/[0-9]+\.[0-9]+` branches.

**Comment by AlanGriffiths** [comment]
Obsolete - 1.8.0 is nowhere in the wild
