### ISSUE TITLE
How can KWinFT make use of Mir?

### ISSUE THREAD

**Issue by subdiff** [MirServer/mir#1430]
Hi all,

I recently [announced the KWinFT project](https://subdiff.org/blog/2020/the-k-win-ft-project). The two major offerings are the KWinFT compositor and Wrapland, respective forks of KWin and KWayland. The reasons for doing that are numerous and you can read above announcement for an overview.

My plan was with Wrapland to remove the Qt dependency and make it a modern C++ library. Now in a comment to the announcement I was made aware of Mir already offering that.

I examined now the Mir project a bit and first I have to say that it looks very well managed and setup here on GitHub. Kudos!

In regards to the KWinFT project I would be interested in seeing if and to what extent I could make use of Mir. For that some questions for now:
* From the examples I saw Mir seems to abstract many things quite radically. Is there also an alternative low-level access? Do you have an example comositor?
* I won't be able to do any major switch-overs at once, so is there integration possible in a partial manner? Do you offer integration with other Wayland event loops for example?
* In any case for Wrapland I could make use of [wlcs](https://github.com/MirServer/wlcs) I guess. I have build up quite a CI machinery in the last few months for KWinFT and I am always looking for more checks I can run on it. Is there a contained example on how to make use of it?

Thanks,
Roman

**Comment by AlanGriffiths** [comment]
Hi Roman, I'm not sure exactly what you're looking for, so I'll answer as best I can and we'll see where we go from there.

Mir contains a compositor, and there are several examples using it:

* In mir-demos there's miral-kiosk and miral-shell
* In mir-test-tools there's mir_demo_server
* There's a few Mir based snaps
  * [mir-kiosk](https://snapcraft.io/mir-kiosk)
  * [mate-wayland](https://snapcraft.io/mate-wayland)
  * [egmde](https://snapcraft.io/egmde)
  * [egmde-confined-desktop](https://snapcraft.io/egmde-confined-desktop)

[Unity8](https://unity8.io/) (which was recently renamed Lomiri) as used by the UBports "Ubuntu Touch" phone integrated the Qt scenegraph and compositing into Mir via a project QtMir. That approach was a bit untidy and we are aiming to replace that in the medium term.

Our approach to integrating additional Wayland support is outlined here: [Mir support for Wayland](https://ubuntu.com/blog/mir-support-for-wayland).

The wlcs documentation is here: https://github.com/MirServer/wlcs/wiki/Integrating-WLCS-with-your-test-suite. I know @RAOF has done some work on supporting other compositors, but I'm not sure if there's anything public.

Much of the discussion around Mir and related projects happens on the [Mir forum](https://discourse.ubuntu.com/c/mir). That may already contain answers for some of what you want and be a better place for further discussions.

I hope that's enough to get you to the next level!

Best,
Alan

**Comment by wmww** [comment]
I'm sure it's mentioned on our website or somewhere, but I'd just like to add that we're on #mir-server on freenode. That might be a better place to have any long-winded discussions. Morning US time (afternoon European time) on week days is probably the best time to catch us.

**Comment by RAOF** [comment]
> The wlcs documentation is here: https://github.com/MirServer/wlcs/wiki/Integrating-WLCS-with-your-test-suite. I know @RAOF has done some work on supporting other compositors, but I'm not sure if there's anything public.

There is [this, in-progress for Weston](https://gitlab.freedesktop.org/RAOF/weston/tree/wlcs-integration).

> I won't be able to do any major switch-overs at once, so is there integration possible in a partial manner? Do you offer integration with other Wayland event loops for example?

The extension support Alan references allows access to Mir's `wl_display`, but that's kinda the reverse of what you want; you can add your own stuff on, but Mir will have already published its globals.

**Comment by AlanGriffiths** [comment]
> The extension support Alan references allows access to Mir's `wl_display`, but that's kinda the reverse of what you want; you can add your own stuff on, but Mir will have already published its globals.

I get it now.

@subdiff while this isn't something we support now, we're happy improve Mir support for real world requirements. (Simple stuff by accepting PRs, but this likely needs discussion first to fit cleanly into the architecture.)

**Comment by subdiff** [comment]
Thanks for all your help. I'll close this issue as I have some pointers to go by now. If there is something more to talk about I'll create a new issue or just post in the forum/IRC channel.
