### ISSUE TITLE
File handles are leaked in miral-test

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1431]
I've seen this with several tests. Not yet sure if it is a problem  with Mir or the test harness.

Examples:
1. `miral-test --gtest_filter=Runner.stop_callback_is_called --gtest_repeat=4000` errors after iteration 1002
2. `miral-test --gtest_filter=TestServer.connect_client_works --gtest_repeat=1000` errors after iteration 992

**Comment by RAOF** [comment]
Ok, I'm pretty sure this is fallout from our “just leak the `g_source`” approach to handling tearing down the `GLibMainLoop`. In 91426b8 we added a action that takes a shared reference to a `Renderable`, which means when we fail to destroy the functor on shutdown we leak the fd owned by the underlying buffer.

**Comment by Saviq** [comment]
>     1. `miral-test --gtest_filter=Runner.stop_callback_is_called --gtest_repeat=4000` errors after iteration 1002

This ran successfully to iteration 40k here, so looks like this got fixed.
