### ISSUE TITLE
Intermittent in WLCS: Mir fatal error: fake event failed to go through

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1432]
So far I've only observed this locally on my Oryx Pro (Arch). There's no obvious pattern as to which tests hit the issue. Out of the 400+ tests, one will hit it about once every 5 or 10 runs. The crash is preceded by a 5s pause (which makes sense if you look at `emit_mir_event()` in test_wlcs_display_server.cpp). It happens both with and without GDB. The one-liner I use to reproduce is:
```
while gdb --ex 'set pagination off' --ex r --ex c --ex q --args ./wlcs ../../mir/build/lib/miral_wlcs_integration.so --gtest_filter='-*times_out*:*BadBufferTest*'; do echo 'again!'; done
```

**Comment by wmww** [comment]
Hmmm... does not appear to effect Ubuntu (which explains why we haven't noticed it before)

**Comment by wmww** [comment]
After an extensive amount of tracing it appears that `mir::dispatch::ActionQueue` is waking up it's fd, but `dispatch_loop()` in threaded_dispatcher.cpp is not noticing and dispatching. Depending on where I put print statements I can make it also fail (almost every run) when tearing down the server. I can not reproduce either on Ubuntu.

**Comment by wmww** [comment]
Somehow the `poll()` at `src/common/dispatch/threaded_dispatcher.cpp:203` isn't picking up the event it should. Perhaps someone else will have a better idea why that might be.

**Comment by AlanGriffiths** [comment]
Sounds like the same cause as #1405

**Comment by wmww** [comment]
Oh shoot, you're right and that's kinda obvious

**Comment by wmww** [comment]
Can no longer reproduce, probably fixed.
