### ISSUE TITLE
Parallel build unreliable due to use of wayland generator

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#1440]
When trying #1436 I stumbled upon a problem with parallel builds - `wayland_wrapper.h` was missing.

There should be dependencies between CMake targets set up so the ordering is ensured.

**Comment by wmww** [comment]
Not a duplicate of but may be related to #629

**Comment by Saviq** [comment]
I've updated the description to only deal with the parallelism.

**Comment by Saviq** [comment]
I've not seen any problem like that, having built with `-j16` routinely.
