### ISSUE TITLE
Possible BasicWindowManager thread safety issue

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1467]
in `BasicWindowManager::select_active_window()`, a line sets `allow_active_window = hint;`. This might be a problem because `allow_active_window` is a class member, the mutex is not locked and the function can be called externally (via the window manager tools interface). The obvious solution of locking the mutex may not work, because I believe the policy can and does select an active window while being called into from the wm, and the wm calls into the policy with it's mutex locked. I have not noticed any real world bugs I can attribute to this issue.

**Comment by AlanGriffiths** [comment]
It is a precondition violation to call tools methods without a lock.
