### ISSUE TITLE
Intermittent spinner errors on Focal in the lab

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#1468]
I've seen this failure before (but I believe on Nvidia), so for the record:

```log
[2020-05-08 01:45:03.251186] < -warning- > mirserver: WaylandInputDispatcher::input_consumed() got non-input event type 11
[2020-05-08 01:45:06.978981] <information> server_example_test_client.cpp: Terminating client
[2020-05-08 01:45:06.979181] <information> mirserver: Stopping
I: [FAILED] /usr/bin/mir_demo_client_wayland_egl_spinner
[timestamp] End : mir_demo_client_wayland_egl_spinner 2020-05-08T01:45:07+00:00
running client mir_demo_client_wayland
[timestamp] Start : mir_demo_client_wayland 2020-05-08T01:45:07+00:00
```

It happened in the `amd` job, but it actually used i915, because it's a hybrid.

http://10.101.50.238:8080/blue/organizations/jenkins/cert-focal-mir-amd-gfx/detail/cert-focal-mir-amd-gfx/4/pipeline

**Comment by Saviq** [comment]
On Nvidia, too:

http://10.101.50.238:8080/blue/organizations/jenkins/cert-focal-mir-201405-15065/detail/cert-focal-mir-201405-15065/12/pipeline

**Comment by RAOF** [comment]
Hm. Ok. I've run the amd job repeatedly for an hour without getting any failures.

Notably, however, that boot had the Intel chip on `/dev/dri/card0` and the AMD chip on `/dev/dri/card1`, whereas the failed run has it the other way around.

**Comment by RAOF** [comment]
Nope, that's not it. At least not directly. Just had a *successful* run with AMD on `/dev/dri/card0` and Intel on `/dev/dri/card1`.

**Comment by AlanGriffiths** [comment]
@Saviq are you still seeing this?

**Comment by Saviq** [comment]
> @Saviq are you still seeing this?

Not in a while, no.

**Comment by Saviq** [comment]
Right.

```plain
/snap/mir-test-tools/5107/usr/bin/mir-smoke-test-runner: line 34:  4122 Segmentation fault      WAYLAND_DISPLAY=${wayland_display} ${root}/mir_demo_server ${options} --test-client ${root}/${client}
I: [FAILED] /snap/mir-test-tools/5107/usr/bin/mir_demo_client_wayland_egl_spinner
[timestamp] End : mir_demo_client_wayland_egl_spinner 2021-04-15T08:15:26+00:00
[timestamp] End time : 2021-04-15T08:15:26+00:00
I: The following clients failed to execute successfully:
I:     mir_demo_client_wayland_egl_spinner
I: Smoke testing complete with returncode -1
```

**Comment by AlanGriffiths** [comment]
That looks different to the earlier log, might be a different cause. Any clue which process segfaulted this time? (Are there logs from Mir?)

**Comment by Saviq** [comment]
This was a manual run in the lab, so I lost the context I'm afraid. Will look out for it again, though.

**Comment by AlanGriffiths** [comment]
I've seen a similar failure when running tests on a loaded RPi3b. I think it is a timing issue (i.e. the spinner starts late and then fails to shutdown in a timely manner) as appending `--test-timeout 10` made it go away.

**Comment by Saviq** [comment]
I've not seen this in a long while, and was unable to reproduce on a stressed Pi for a couple hours now.
