### ISSUE TITLE
Two copies of Window occasionally appear

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1491]
Very rarely (maybe 1 in 100 window openings), a 2nd, decorationless copy of an X11 window appears. They seem to be using the same buffers (update in sync). It appears the two windows are distinct scene surfaces (perhaps race in the creation path causes them both to be created?).

**Comment by wmww** [comment]
A `Surface already has a role` exception seems to get thrown as well

**Comment by AlanGriffiths** [comment]
Could this perhaps be a side-effect of duplicating the Xwayland parameters? #1493

**Comment by wmww** [comment]
No, I observed it a few times on the "good" half of the bisect.

**Comment by AlanGriffiths** [comment]
Not seed for a while
