### ISSUE TITLE
Selecting MIR_USE_LD=lld doesn't work without clang

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1533]
E.g. CMake symbol detection fails work with just `MIR_USE_LD=lld`, for this to work needs  also `CMAKE_CXX_COMPILER=clang++ CMAKE_C_COMPLIER=clang`.

I don't think we need to make this work, but we probably want a better diagnostic.

**Comment by RAOF** [comment]
Huh! This seems to be fixed. I've just tred it with gcc 10 and lld on Ubuntu 21.04, and it works.
