### ISSUE TITLE
Wayland keyboard input gets messed up

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#155]
$ miral-app

In the terminal in the Mir session

$ mir_demo_client_chain_jumping_buffers^m
(yes, Ctrl+M not the enter key)

The chain_jumping_buffers demo starts. Switch back to the terminal.

Open another tab: Ctrl-Shift-T

Type a command, e.g. "ls"

Expect: typing appears in terminal tab
Actual: keys are interpreted as though "Ctrl" is held down

**Comment by AlanGriffiths** [comment]
I wonder if this is connected?

`        // TODO: We might need to copy across the existing depressed keys?
`

**Comment by AlanGriffiths** [comment]
Hey @RAOF I had a poke around but failed to guess the right incantation, I hope you know this stuff better than I: could you take a look?

**Comment by RAOF** [comment]
Ah, yeah. I'll see how to slurp the relevant state out and send it.
