### ISSUE TITLE
"Shell components" should not be part of the focus sequence

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1578]
Running with (say) Waybar, it is easy to Alt-Tab and get focus onto the docked bar. Similarly, when apps are closed and the focus shifts focus can go to the bar.

I guess it should be possible to get focus onto a docked bar explicitly (e.g. if it has app icons for switching), but it's too easy at present.

**Comment by AlanGriffiths** [comment]
Note: I've frigged this in egmde by setting surfaces outside the application layers to `mir_window_type_decoration`, but that's not the correct fix.

**Comment by wmww** [comment]
I believe it should be possible within Mir to let a surface that is anchored and/or on a different layer take focus, but our Layer Shell implementation should set something to disable focus for it's surfaces. Could it simply use `mir_window_type_decoration`? Is there another property it could set? I looked at the surface document but it didn't seem to mention the decoration type.

**Comment by AlanGriffiths** [comment]
Not implementing layer-shell correctly?

**Comment by AlanGriffiths** [comment]
> Not implementing layer-shell correctly?

Yes, closed in favour of #1972
