### ISSUE TITLE
Mir on FreeBSD?

### ISSUE THREAD

**Issue by lonnietc** [MirServer/mir#1601]
Hello,

Sorry if this is the wrong place for this as I cannot locate a mailing list or form.

I have a project that will be on FreeBSD and needs to run just one application (either a VNC client or RDP client which could be rdesktop or Freerdp) and am trying to determine if Mir could be used as a replacement to Xorg so as to keep the footprint size down.

This is meant to be an super-ultra-thin ISO that has just a remote access client and absolutely nothing more while making the ISO absolutely as small as possible. (The smaller the better)

Can Mir work in this regard?
Thanks in advance

**Comment by AlanGriffiths** [comment]
@lonnietc there's no active mailing list. The [mirserver.io](https://mir-server.io/) lists:

* [Mir in the Ubuntu Community forum](https://community.ubuntu.com/c/mir); and, 
* [#mir-server on Freenode](https://webchat.freenode.net/?channels=%23mir-server)

As to FreeBSD, it would take work to port Mir to FreeBSD. Mir has dependencies on the GNU/Linux ecosystem. I don't know detail of FreeBSD to estimate how big a job that would be. (While this isn't a full solution for you, we've accepted changes (to support postmarketOS) for Mir to work on musl as well as glibc.)

If you don't want to port Mir to FreeBSD, would Ubuntu Core be an option for you? We do support Mir on that platform.

**Comment by lonnietc** [comment]
Thanks for getting back to me.

I would like to learn more about Ubuntu Core with Mir to see exactly how small it could be as an ISO.

Where can I learn more on this?

**Comment by AlanGriffiths** [comment]
https://lmgtfy.com/?q=ubuntu+core

**Comment by lonnietc** [comment]
Thanks again
