### ISSUE TITLE
Desktop session loses the touchpad after suspend/resume

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1612]
1. On a laptop run mir-shell or egmde from the greeter.
2. Close the lid to suspend
3. Open the lid to resume

The greeter starts up, and the keyboard (and external mouse) work fine. But the touchpad doesn't.

**Comment by wmww** [comment]
I can reproduce running master on a TTY. FWIW TTY switching away and back fixes it.

**Comment by AlanGriffiths** [comment]
Possibly shares a cause with #617

**Comment by AlanGriffiths** [comment]
I don't know what's behind it, but after resume touchpad input leads to:
```plain
[2020-08-05 16:35:01.130492] < -warning- > evdev-input: Failed to find requested fd for path /dev/input/event6
Failed to set flags: Bad file descriptor (9)
[2020-08-05 16:35:01.130570] < -warning- > evdev-input: Failed to find requested fd for path /dev/input/event6
```
(And, from other debugging, `/dev/input/event6` is "UNIW0001:00 093A:1336 Touchpad-event6-2362-4918")
