### ISSUE TITLE
miral-shell keyboard shortcuts don't respect keyboard mapping

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#1627]
I've got my keyboard mapped to `us:dvorak`, and pressing <ctrl>+<alt>+T in miral-shell (both under `x11` and `gbm-kms`) does *not* launch a terminal. However, pressing <ctrl>+<alt>+y (y is where t is in a qwerty layout) *does* open a terminal.

The clients of miral-shell get the correct keymap and interpret key events appropriately, but it seems that miral-shell itself does *not* get key events translated by the keymap?

**Comment by AlanGriffiths** [comment]
Hmm. That's _obviously_ because miral_shell.cpp uses `mir_keyboard_event_scan_code()` not `mir_keyboard_event_key_code()`.

Looking at `egmde::ShellCommands::keyboard_shortcuts()` that does the same (wrong) thing.

Something for 2.1.
