### ISSUE TITLE
Nested Mir doesn't grok orientation

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1629]
Here's mircade nested in mir-kiosk with:
```plain
$ snap get mir-kiosk
Key             Value
...
display-config  
layouts:
  default:                         # the default layout
    cards:
    - card-id: 0
      HDMI-A-1:
        orientation: right

display-layout  default
...
```

![image](https://user-images.githubusercontent.com/9048879/88413778-ad72d900-cdd3-11ea-85fb-f8ed17caa780.png)

**Comment by AlanGriffiths** [comment]
This is fixed in 2.0's "wayland" platform. Rebuilding the mircade snap.

**Comment by AlanGriffiths** [comment]
One part of this is that `mf::Output::send_initial_config()` doesn't send the correct transform.
Another is that the "wayland" platform ignores the transform.

**Comment by wmww** [comment]
Why does the nested Mir have to understand the transform at all? Is that only problem that it doesn't resize correctly? Why is it sizing based on output instead of a size it is configured to?

**Comment by AlanGriffiths** [comment]
> Why does the nested Mir have to understand the transform at all? Is the only problem that it doesn't resize correctly? Why is it sizing based on output instead of a size it is configured to?

What it aims to implement is one fake "output" per host output (with a matching configuration). Perhaps there are more general or more sophisticated things to do, but this was the simplest thing to replicate the old "nested" feature.

**Comment by wmww** [comment]
Hmm, I see. The problem with sending output transform is that then some clients will send transformed buffers, and correctly handling them was difficult (IIRC it was because we haven't switch our surface abstraction over to match the Wayland one yet)

**Comment by AlanGriffiths** [comment]
Agreed. But if we are pretending not to be rotated and simply passing, for example, the physical dimensions, then this confuses clients too. (I don't think this just affects nested Mir, as similar behaviour happens with X11 based client snaps.)

**Comment by wmww** [comment]
Only integer scales can be reported over Wayland, but a Mir output may have a floating point scale. Therefore clients should never assume they can reverse engineer the logical output size, and should instead take the size Mir configures them to be. Other than guessing desired size, is there any other reason clients need to know output transform?

**Comment by AlanGriffiths** [comment]
> Other than guessing desired size, is there any other reason clients need to know output transform?

As you mention above, it allows clients to prepare transformed (and scaled) buffers to submit to the server.

**Comment by wmww** [comment]
Right. We already send scale and process scaled buffers correctly. Since we don't have the infrastructure in place yet to correctly handle transformed buffers, we shouldn't tell them the outputs are transformed. We *could* (and probably should) swap X and Y on rotated outputs (as your PR does), but that doesn't really matter as long as clients aren't basing their size off of the output size.
