### ISSUE TITLE
Mir on OpenIndiana (illumos-based)?

### ISSUE THREAD

**Issue by lonnietc** [MirServer/mir#1649]
Hi All,

I am seeking an alternative to X11 that might be able to run on Openindiana (illumos-based) systems such that I can run just a single application and no desktop manager is required. I am trying to keep the file size footprint as absolutely small as possible which is a huge challenge.

Any help would be greatly appreciated.

**Comment by RAOF** [comment]
So, I don't think we currently have anyone trying to run Mir on non-Linux kernels. We're not deliberately bound to the Linux kernel, but we haven't attempted to avoid Linux-only features like `epoll`, `timerfd`, and so on.

If you wanted to do the work, think it would be *possible* to make a build of Mir run on non-Linux POSIX systems, but it probably doesn't right now and we have no plans to do the porting required to make it work.

**Comment by lonnietc** [comment]
Hello,

Would you say that, in general, the file sizes of Mir are significantly smaller than Xorg?

Also, as I am still new to Mir and might want to give it a try to help out on this effort, will Mir run the X11 applications?  

In particular, I am interested in running Remmina and FreeRDP in a type of Kiosk mode for Remmina which uses the FreeRDP libraries.

**Comment by AlanGriffiths** [comment]
> Would you say that, in general, the file sizes of Mir are significantly smaller than Xorg?

That's not an easy comparison to make. For example, Mir provides window management whereas you'd typically need a separate window manager with X11.

> Also, as I am still new to Mir and might want to give it a try to help out on this effort, will Mir run the X11 applications?

Mir has optional support for X11 applications that, if enabled, uses Xwayland (from Xorg).

> In particular, I am interested in running Remmina and FreeRDP in a type of Kiosk mode for Remmina which uses the FreeRDP libraries.

You shouldn't need X11 support for Remmina - it uses the GTK3+ toolkit, which runs perfectly well on Wayland (and hence on Mir).

**Comment by AlanGriffiths** [comment]
Not an issue
