### ISSUE TITLE
Rendering is incorrect on RPi 4

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#1663]
It looks like ![this](https://user-images.githubusercontent.com/804339/89596118-ba92cc00-d899-11ea-948c-8e02aae3be0a.jpeg)

Probably a stride issue.

Update: this is a Mesa issue. Munging Weston to disable the `linux_dmabuf` support, glmark2 under Weston displays the sam eproblem.

**Comment by Aury88** [comment]
This issue also affect lomiri [[1](https://gitlab.com/ubports/community-ports/pinephone/-/issues/12)][[2](https://gitlab.com/ubports/core/rootfs-builder-debos/-/issues/2)] (aka unity8) in UT on RPi4.
 let us know if there is any useful information you need to help solve the problem.
