### ISSUE TITLE
glmark2-es2 --fullscreen on XWayland is not fullscreen

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#1669]
One way to reproduce:
```
mir_performance_tests --gtest_filter=GLMark2Xwayland.fullscreen
```

There should be no decoration afaict?

**Comment by wmww** [comment]
Odd. Fullscreen works fine on all other XWayland apps tested (Gedit, Kate and Blender). Stranger still `glmark2-es2 --fullscreen` seems to be intermittently fullscreen on sway (about one every ten runs it's windowed). Will investigate.

**Comment by wmww** [comment]
Ah! it's setting `_NET_WM_STATE` before mapping the window. We were ignoring that because X11 apps are supposed to use a client message to change that property, but according to the protocol apps *can* set it initially and the window manager should respect that.
