### ISSUE TITLE
Wayland globals removed on wrong thread

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1689]
On server shutdown, it appears we're removing globals from the object's destructors, which are being called as part of shared pointer destruction. This is happening in a thread other than the Wayland thread. Noticed this when running Mir in wayland-debug for an unrelated reason.

**Comment by RAOF** [comment]
Not actually closed by 91868fd

**Comment by wmww** [comment]
We do tear down globals on a different thread than the main Wayland one, but we do that after the Wayland thread has been joined. Thus I assume it is safe.
