### ISSUE TITLE
eglstream-kms platform only built for amd64

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#1713]
We only build the eglstream-kms platform for amd64, but there exist at least ARM boards with NVIDIA graphics. We should probably just build it everywhere?

**Comment by Saviq** [comment]
FWIW it's unclear to me that the ARM Nvidia hardware (Tegra?) uses the same API. That said, if it ~~blends~~builds, let's.

**Comment by RAOF** [comment]
This is the result of a discussion in #mir-server by someone who wants to use Mir on a Jenson, and has demo code using EGLStream/EGLOutput working. There might be weird pitfalls lurking, but the base EGL & KMS APIs apparently exist there.
