### ISSUE TITLE
glxgears -fullscreen has decorations

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1758]
`glxgears` is an X11 app that Mir provides window borders for, but this shouldn't happen for fullscreen windows.

Run `miral-app` and from a terminal in that window run `glxgears -fullscreen`.

Expect: a fullscreen window without borders
Actual: a fullscreen window **with** borders

_Note, this may be an issue with `glxgears`, other X11 apps do fullscreen correctly._

**Comment by wmww** [comment]
Note that as far as I can tell, glxgears is not actually requesting to be fullscreen. It's asking for an undecorated window that covers the whole screen area, so that's the best we can give it.
