### ISSUE TITLE
Allow shells to enable XWayland by default

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1762]
Currently a shell can't default to having XWayland support turned on, the user must set a env var/command line option/config option to get it (it's probably possible for the shell to hack it's own environment, but that's not ideal). It should be possible for a shell to enable XWayland by default, and it should then still be possible for a user to explicitly disable it if they desire.

**Comment by AlanGriffiths** [comment]
Not quite true, the shell only needs the following line before starting Mir:
```c++
    setenv("MIR_SERVER_ENABLE_X11", "", 0);
```

**Comment by AlanGriffiths** [comment]
This ought to be an option added to `miral::X11Support`.
