### ISSUE TITLE
Smoke tests get stuck sometimes when nested

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#1775]
To reproduce:
```bash
# create an "ubuntu" user
$ sudo adduser ubuntu
# ...
# make tty3 auto-login for the user
$ sudo mkdir -p /etc/systemd/system/getty@tty3.service.d/
$ sudo tee /etc/systemd/system/getty@tty3.service.d/override.conf <<EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin ubuntu --noclear %I \$TERM
EOF

# add the test runner to its .bashrc
$ sudo tee -a ~ubuntu/.bashrc <<EOF
loginctl activate

mir-kiosk &> /tmp/mir-kiosk.log &
sleep 1

(env MIR_SERVER_WAYLAND_HOST=wayland-0 mir-test-tools.smoke-test ) &> /tmp/mir.log
touch /tmp/mir-done

pkill miral-kiosk
EOF

# loop tty3 until you see it getting stuck
$ while true; do sudo rm /tmp/mir-done; sudo systemctl restart getty@tty3.service; until [ -f /tmp/mir-done ]; do sleep 1; done; done
```

When it does get stuck, the screen is blank, and any activity (moving your mouse, toggling VT) will unblock it.

Attached are gdb traces from the three involved processes:
[mir-kiosk.gdb.txt](https://github.com/MirServer/mir/files/5428744/mir-kiosk.gdb.txt)
[mir_demo_server.gdb.txt](https://github.com/MirServer/mir/files/5428745/mir_demo_server.gdb.txt)
[mir_demo_client_wayland_egl_spinner.gdb.txt](https://github.com/MirServer/mir/files/5428746/mir_demo_client_wayland_egl_spinner.gdb.txt)

**Comment by AlanGriffiths** [comment]
Reproduced hosted by mir-kiosk running on X11 on the desktop. Hopefully this can be reproduced with debug symbols.

**Comment by AlanGriffiths** [comment]
Reproduced hosted by mir-kiosk running on X11 on the desktop. Hopefully this can be reproduced with debug symbols.

**Comment by AlanGriffiths** [comment]
Simpler reproducer:
```plain
mir-kiosk&
while true; do mir-smoke-test-runner; done
```
