### ISSUE TITLE
Ignore Hot Plug Detect

### ISSUE THREAD

**Issue by G2020sudo** [MirServer/mir#1776]
Is there a method to ignore the display hot plug detect events ?

**Comment by Saviq** [comment]
Hi @G2020sudo you can provide a static display config, have a look at [our Discourse post on this](https://discourse.ubuntu.com/t/display-configuration-for-mir-kiosk/7815). That said, it will currently need the configured displays to exist on startup.

**Comment by G2020sudo** [comment]
Thanks, I did notice this but wasn't sure this would work if a monitor disconnects. For example if I have a 2 displays side by side horizontally and a window spanning both diplays will the window move when one of the displays disconnects? Sounds like it will work but wanted to double check. Thanks again
 
  On Fri, Oct 23, 2020 at 8:52 AM, Michał Sawicz<notifications@github.com> wrote:   


Hi @G2020sudo you can provide a static display config, have a look at our Discourse post on this. That said, it will currently need the configured displays to exist on startup.

**Comment by AlanGriffiths** [comment]
> Thanks, I did notice this but wasn't sure this would work if a monitor disconnects. For example if I have a 2 displays side by side horizontally and a window spanning both diplays will the window move when one of the displays disconnects? Sounds like it will work but wanted to double check. Thanks again

It depends on the active window manager policy, display configuration options and, possibly, which monitor unplugs.

Setting a static display configuration will prevent, for example, the origin moving from one output to another. But not the window manager updating the layout. The "tiling" window manager example would relay the tiles.

It is probably faster and easier to try your scenario out.

**Comment by G2020sudo** [comment]
Thanks. I experimented with mir-kiosk today and was to launch chromium via **snap start chromium-mir-kiosk**, but with 2 displays connected it appears mir is cloning the displays by default. 

Is there a method to not clone but use sidebyside instead?

**Comment by AlanGriffiths** [comment]
> Is there a method to not clone but use sidebyside instead?

Are your questions specific to mir-kiosk? That will always fullscreen applications, so having applications spanning outputs is meaningless unless you also employ the ["display groups" feature](https://discourse.ubuntu.com/t/multiple-outputs-as-a-single-logical-display/18920) that recently landed on master.

For a more general discussion of configuring mir-kiosk see: https://discourse.ubuntu.com/t/configuring-mir-kiosk-a-masterclass/8150

**Comment by G2020sudo** [comment]
@AlanGriffiths  yes I referring to mir-kiosk. I managed to get mir-kiosk on the edge channel working group. However, the main window was cloned on the second display unless I also changed the position. When I finally got this working I then tested with chromium-mir-kiosk but it is confused and only displaying on the first screen. I need it span across both displays like the link you sent. Is it possible to get more details about how the "display groups" demo was accomplished?  

For example for my two displays I had to use the below display-config:
      state: enabled        # {enabled, disabled}, defaults to enabled
        mode: 640x480@59.9  # Defaults to preferred mode
        position: [0, 0]      # Defaults to [0, 0]
        orientation: normal   # {normal, left, right, inverted}, defaults to normal
        scale: 1
        group: 2      # Outputs with the same non-zero value are treated as a single display

and

        state: enabled        # {enabled, disabled}, defaults to enabled
        mode: 640x480@59.9  # Defaults to preferred mode
        position: [640, 0]      # Defaults to [0, 0]
        orientation: normal   # {normal, left, right, inverted}, defaults to normal
        scale: 1
        group: 2      # Outputs with the

**Comment by AlanGriffiths** [comment]
> Is it possible to get more details about how the "display groups" demo was accomplished?

https://discourse.ubuntu.com/t/multiple-outputs-as-a-single-logical-display/18920/2

> I then tested with chromium-mir-kiosk but it is confused and only displaying on the first screen.

For "display groups" to work, the Mir server being used and the client application need to co-operate. In particular, the the client needs to draw a window the size it is asked for, and not the size of the output. Not all clients do this correctly (i.e. they have bugs).

In your case, `chromium-mir-kiosk` is a poor choice for testing. It is a demo from some years ago and was never a supported solution.

Closing this issue as the original question has been answered, and support for `chromium-mir-kiosk` is off-topic. As was said on https://discourse.ubuntu.com/t/snaps-to-develop-a-web-kiosk-on-ubuntu-core-using-wayland/6424/109

> Source is here: https://git.launchpad.net/~mir-team/+git/chromium-mir-kiosk?h=master 11
but it hasn’t been touched in some time, so I’ve no idea if it will build. We’re not developing it any further, and instead pointing people at https://snapcraft.io/wpe-webkit-mir-kiosk

**Comment by G2020sudo** [comment]
ok thank you for the help!
