### ISSUE TITLE
XWayland display unset unless app explcitly launched with X11

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1782]
If, for example, you open a Wayland terminal and then launch an X11 app from it, it fails to find a display.

**Comment by AlanGriffiths** [comment]
Please give a reproducer. Are you starting your Wayland terminal from a Mir server?

I can, for example, start miral-shell, launch a terminal and start xeyes without problems.

**Comment by AlanGriffiths** [comment]
After discussing, turns out that the terminal isn't launched from Mir and isn't supplied the DISPLAY Mir is using
