### ISSUE TITLE
BasicWindowManager does not always use correct input event for move/resize

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1792]
While investigating #760, I noticed that when initiating a move/resize gesture we were blindly using the most recent input event without checking it against the serial from the request. This means that if the user drags the titlebar then touches the window and the `move` request from the titlebar doesn't come in until after the touch, the user will end up moving the window with the touch instead of the click.

**Comment by wmww** [comment]
All the functions in `BasicWindowManager` that take timestamps probably need to be changed to take an input event and all the instances of
```
if (timestamp >= last_input_event_timestamp)
```
probably need to be dropped. Consider the following sequence:

| Server | Client |
|--:|:--|
| pointer pressed `serial=1` ⬎ | |
| pointer motion ⬎ | ↳ pointer pressed `serial=1` |
| | ↳ pointer motion |
| touch down `serial=2` ⬎ | ⬐ window move `serial=1` |
| window move `serial=1` ↲ | ↳ touch down `serial=2` |

I believe this currently initiates an interactive move from the touch, which is obviously wrong (the touch may not have even been over the titlebar). I think the correct behavior is for the interactive pointer move to precede uninterrupted. The correct timestamp of the move request would be that of the first pointer press (before both the touch and the pointer motion), which would indicate that requests with the non-latest timestamp should not be discarded.

**Comment by AlanGriffiths** [comment]
In part this is a legacy of bolting on the Wayland frontend: the timestamps were (are?) correctly with respect to the mirclient API: receiving a request tagged with anything other than the latest input event should result in the request being ignored.

The Wayland frontend supplies the latest input timestamp into this without any checking of serial numbers. Maybe this can be improved there, or maybe we should rework the whole thing and rip out any affected mirclient code.

**Comment by wmww** [comment]
In the case of a window move request, the "latest timestamp" is almost always going to be wrong because the request wont be send until there is pointer motion after the button press, but the serial will be for the press because motion doesn't have a serial. It could maybe work if we made it latest-event-with-a-serial, but IMO that's not the *right* way to do it, and leads to undesirable behavior in edge cases (like described in the chart).

**Comment by wmww** [comment]
My solution to this is for the fronted to store a mapping of serials to recent input events, match request serials with their event and send the event (instead of a timestamp) to the window manager. The issue with this is in order to fix #1793 the window manager needs to know the position of the cursor (or touch) at the time of the event that started it all. It will have the event, but it's position will be relative to the surface (or even a subsurface that the window manager doesn't know about). 

My idea to solve this is to change pointer and touch events a little, so instead of just a single position they store an absolute position and position relative to surface. Either that, or we could not attach a relative position at all and instead send the surface offset next to the event as an argument to the relevant surface observer method.

We've discussed refactoring the event class to be more C++like, perhaps now is the time to do it?

**Comment by wmww** [comment]
I'm incrementally pushing out a sequence of PRs that should eventually fix this. The one that's currently waiting for review is #2644. After that I'll split up local and global positions for events, and then be able to send events from the frontend to the window manager.
