### ISSUE TITLE
On 18.04 GTK apps crash when using MIR_EXPERIMENTAL_XDG_SHELL

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#180]
MIR_EXPERIMENTAL_XDG_SHELL=1 cmake-build-debug/bin/miral-app

$ gedit

Expect: gedit starts and is responsive
Actuai: gedit starts but crashes on any(?) interaction

**Comment by AlanGriffiths** [comment]
I first noticed this this AM - apt log shows a bunch of gnome updates. (I suspect GTK is now expecting different protocols and/or versions than we offer.)

**Comment by AlanGriffiths** [comment]
I think things may have changed since last week. 

Today crashes seem to be happening on the first *keyboard* interaction. (Mouse and touch interaction seems fine.)

**Comment by AlanGriffiths** [comment]
```
[3604392.608] wl_keyboard@3.key(8, 1644784138, 30, 1)

(gedit:8506): GLib-GIO-ERROR **: 17:20:12.278: Settings schema 'org.gnome.settings-daemon.peripherals.keyboard' does not contain a key named 'repeat'
```

**Comment by AlanGriffiths** [comment]
Well, it looks like [something similar](https://github.com/kkspeed/NaiveWM/commit/3694cee277df468df0d1aae6510d7a4eaf06ecfb) happened once before.

Looking at /usr/share/wayland/wayland.xml (on bionic) it seems the wl_seat and wl_keyboard interfaces could be at version 6. But the apps only ask for version 5 anyway (which is what we advertise).

@wmww @RAOF does this make sense to either of you? (If not, I'll try hunting down the client-side code tomorrow)

**Comment by wmww** [comment]
Nice job finding that link. I've seen the repeat key bug on a few compositors, but I can't remember what the fix is. I I fixed it in hedgehog though, and I don't think it was too hard. I'll look into it more when I have time.
