### ISSUE TITLE
We don't check if glEGLImageTargetTexture2DOES is supported

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1808]
See https://github.com/MirServer/mir/pull/1806#discussion_r521084930

**Comment by wmww** [comment]
Based on the long-winded comment nearby the solution might be to drop `glEGLImageTargetTexture2DOES` entirely.

**Comment by RAOF** [comment]
Ok. I'm going to unassign myself from this. It's moderately difficult to get the necessary context in to the sites which need this, and the only benefit of doing so would be better error messages in the case of weird drivers.

**Comment by AlanGriffiths** [comment]
> the only benefit of doing so would be better error messages in the case of weird drivers.

Sounds like we don't need this
