### ISSUE TITLE
Windows don't change size when restoring if they started maximized

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1817]
I'm not exactly sure how it gets into this state, but for me I'll often have a maximized window that unmaximizes to about the same size and position it was before. If I don't try to move it or notice the subtle change in decorations, I can't even tell it's been unmaximized. In my opinion, it's a better user experience for windows to always get smaller when they are unmaximized.

I plan to implement this at some point. Please leave any feedback, as it's always easier here than in code review.

**Comment by AlanGriffiths** [comment]
With most window managers the "restored" size of a window is the size it was before being maximized/fullscreened/minimized. If that happens to be similar to the maximized size it _shouldn't_ be unexpected. This is also what I expect from Mir's default window management.

It sounds as though you've hit a scenario where that isn't happening and the wrong "restored" size is used. A reproducer could help clarify what exactly is going wrong.

**Comment by wmww** [comment]
Hmm perhaps you're right. The problem seems to be mostly apps that start maximized. Blender (with XWayland) always starts maximized, ans gedit starts maximized if it was previously closed while maximized. In both cases, after starting maximized and being restored they maintain their maximized size.

**Comment by wmww** [comment]
Using wayland-debug, I confirmed that we are explicitly requesting the client use the maximized size when we ask it to restore in these cases. We either need to window manager to pick a sensible size for it to restore to when it has no previous restored size to remember, or we need the window manager to be able to request no size in particular, with the frontend will pass on to the client.

**Comment by AlanGriffiths** [comment]
From memory, I think that during the initial placement we take the requested window size without any consideration of the state. We should set the "restored size" to something sensible for maximized windows.
