### ISSUE TITLE
Geometry classes should support floating-point types

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1829]
Rather than re-writing floating-point variants of everything, I propose we change the current types to templates and make specializations of them. `PointI` would be an alias for `Point<int>` and an equivalent of the current `Point`, `DisplacementF` would be an alias of `Displacement<float>`, etc. This would give our input handling code the same level of type safety as the rest of Mir.

**Comment by wmww** [comment]
I have an idea for the *right* way to do this. I started working on it but it's a lot of typing so I don't want to continue until I've gotten a green-light for the idea.

1. Replace `IntWrapper<Tag>` with a more generic `Tagged<Tag, T>` with `T` being the value type.
2. Use `using ... = ...` to define generic versions of dimensions: `WidthT`, `HeightT`, `XT`, `YT`, `DeltaXT` and `DeltaYT` (`T` stands for template, open to other suggestions. We can't use the names directly because they will still mean the int versions for backwards compat)
3. Define `Width`, `Height`, `X`, etc to be the int versions
4. Define `WidthF`, `HeightF`, `XF`, etc to be the float versions
5. Change all the operators to templates
6. Add conversions that change type but don't change tag
7. Change `Point` to more generic `PointT<XType, YType>`,
8. Define `Point` to be the `<Width, Height>` int version, and `PointF` to be the float version
9. Add safe casting to `PointT` as well
10. Do 7 - 9 for `Displacement`, `Size` and `Rectangle`

Compared to making entirely new classes for floating points, this would:
- Lower cost of maintenance, implementation is shared
- Allow allow for arbitrary types (sometimes we need a `SizeT<std::optional<Width>, std::optional<Height>>`)
- Allow safely converting between any types, (It should be easier to go `Width` -> `WidthF` than `Width` -> `HeightF`). Implementing this for just ints and floats might be possible but it would not scale well to any other types.

Unknowns:
- Would this be ABI stable? We'd be changing the type signatures but under the hood it should always just compile down to raw numbers.

**Comment by AlanGriffiths** [comment]
>     * Would this be ABI stable? We'd be changing the type signatures but under the hood it should always just compile down to raw numbers.

No. For one thing type names are encoded in function signatures

**Comment by wmww** [comment]
After discussion, we decided we might be able to make generic types work if we change our existing types to inherit from them. I will attempt this and put up a draft PR

**Comment by AlanGriffiths** [comment]
I think this was addressed by #1858
