### ISSUE TITLE
Untangle WlSeat from where it does not belong

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1832]
We send around and store `WlSeat` all over the place in the Wayland frontend and we should probably refactor a lot of this out. Two reasons:
- It's the wrong object (in many places what we really want is a Wayland executor, which `WlSeat` has been coerced into serving as)
- Using it as a singleton will get in the way of multi-seat (we don't have plans to support multi-seat at this time, but why make it harder than it needs to be?)

**Comment by AlanGriffiths** [comment]
@wmww didn't we do some or all of this?

**Comment by wmww** [comment]
Yes, `WlSeat` no longer exposes the Wayland executor, meaning most of the inappropriate usage must have been refactored out.
