### ISSUE TITLE
ObserverMultiplexer: deadlocks if observer removed from callback when executor runs immediately

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1880]
`ObserverRegistrar::register_interest()` is documented as such:

> If the thread calling is currently in an Observer call that call will complete, no further ones will be dispatched.

And that is indeed true and tested if the executor in use delegates the callback to another thread or later time. However, if the executor runs `work` immediately, the multiplexer deadlocks. I'm running into this problem because the Wayland executor runs work immediately if already on the Wayland thread. It's possible for me to work around this issue if fixing it would be too difficult or introduce significant tradeoffs.

I've written a test to demonstrate the problem, which I will PR shortly.

EDIT: in the current thing I'm working on not unregistering from a callback actually simplifies the code, so this is no longer a pressing issue.

**Comment by RAOF** [comment]
Yeah, I was a little worried when doing the immediate-execute Wayland executor bit, because it breaks the expectations of `mir::Executor`.

We should perhaps adopt the more precise vocabulary of one of the later Executor proposals; specifically, separating `spawn()` into `dispatch()` (which runs as soon as possible) and `post()` (which definitely does not run in the current stack frame).

**Comment by wmww** [comment]
There's other places where multiplexers use an immediate executor out of convenience. It would be nice to just remove the constraint. I've updated my PR to attempt to do that.

**Comment by RAOF** [comment]
Hm. Where else do multiplexers use immediate executors? Maybe we should have a `mir::system_executor` available in global scope to make this more convenient?

**Comment by wmww** [comment]
`ms::SessionManager::SessionObservers` in `session_manager.cpp` implements `Executor` using immediate dispatch, and uses itself as the multiplexer's default executor. Perhaps we should make the multiplexer do this and provide a default constructor that uses itself?

**Comment by wmww** [comment]
@RAOF isn't this fixed?

**Comment by wmww** [comment]
I'm fairly sure this has been fixed for some time
