### ISSUE TITLE
Non-black default screen when no apps open

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1971]
It's currently difficult to tell when Mir kiosk (or any Mir) is running because the default screen is black. Is there any reason not to set a glClearColor to something more distinctive, so it's clear when a Mir server is running with no windows open?

**Comment by AlanGriffiths** [comment]
This isn't true of Lomiri, miral-shell, ubuntu-frame nor egmde. (It is true of mir_demo_server and miral-kiosk.)

As it can be addressed by an actual server built with Mir, I don't think this needs tracking as an issue here.
