### ISSUE TITLE
Firefox initially wrong size

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#1978]
When testing with #1977, I noticed that when first opened, the Firefox window seems to be maximized but does not fill the screen.

**Comment by AlanGriffiths** [comment]
Data point: I've seen that on GNOME/Wayland too.

**Comment by wmww** [comment]
Data point: I don't seem to see it in Sway

**Comment by Saviq** [comment]
Data point: I've not seen it on Miriway in a good while.

**Comment by AlanGriffiths** [comment]
I've not seen this in a good while on Miriway, Mutter or egmde
