### ISSUE TITLE
[Mir-on-X] Ctrl-Alt-[Left|Right] doesn't work

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2001]
egmde uses these key combinations to dock windows left and right. This doesn't work on with Mir-on-X.

It doesn't seem to be the host desktop shell intercepting these as it is evident on GNOME, Unity and egmde (with shortcuts disabled by Ctrl-Alt-Del).

(This seems rather odd as other combinations such as Ctrl-Alt-[Up|Down] do work.)

**Comment by AlanGriffiths** [comment]
Update: this does work as expected on GNOME/Xorg.

**Comment by Saviq** [comment]
I ran egmde both on a "Ubuntu on Xorg" session and these worked correctly. Did I misunderstand where it _doesn't_ work?

**Comment by AlanGriffiths** [comment]
I'm still seeing this on egmde on Mutter/Wayland. Will try on Xorg...

**Comment by Saviq** [comment]
Maybe I didn't grok the steps to reproduce properly. :shrug:

**Comment by AlanGriffiths** [comment]
OK, so works on Mutter/Xorg and goes wrong on Mutter/Wayland. I think this is likely an issue with Xwayland not doing grabs "right", not something Mir can control
