### ISSUE TITLE
Source of timestamps besides platform 

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2064]
Currently timestamps generally come from platform-level events (libinput, X11, etc). There are a number of other places they're needed, and there is no consistent way of getting them. In the X11 platform timestamps are stored and when one is needed without an available X11 timestamp the last one is used. In `wl_touch.cpp`, previous timestamps are used to calculate an offset from `std::chrono::steady_clock`, which is then used to generate new ones.

All this is sub-optimal and over complicated, but the real problem is that no obvious workaround exists for the virtual keyboard. It gets events with a timestamp that may have a different base than the platform, and needs to convert them into Mir events. It's time to build a better way to synthesize timestamps.

Related to #2063

**Comment by AlanGriffiths** [comment]
You mean something like `mir::time::PosixTimestamp::Clock`?

**Comment by wmww** [comment]
I'll look into that. We'll need to make the platforms calibrate based on that, and then we can use it for other things.

**Comment by RAOF** [comment]
Be aware that this is an *immense* tarpit, depending on what you want to use these for. Platform timestamps are necessarily going to have different bases - particularly, graphics clocks for discrete GPUs are just entirely disconnected from anything CPU-accessible, so any attempt to calibrate GPU clocks against `CLOCK_MONOTONIC`/`CLOCK_MONOTONIC_COARSE` is doomed to failure.

**Comment by wmww** [comment]
Hopefully we won't have to connect timestamps to anything GPU-related

**Comment by wmww** [comment]
Fixed by #2117
