### ISSUE TITLE
GTK on Wayland: cursor moves when it should be hidden

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2073]
To reproduce:
- Open GTK app that hides cursor while typing (tested with gedit and lxterminal)
- Start typing with cursor over text area

Expected:
- Cursor disappears (as it does in Sway)

Actual:
- Cursor moves down and to the right by about one cursor size, but stays visible 

I *think* we would have noticed before if this never worked, but I don't know what broke it.

**Comment by AlanGriffiths** [comment]
Confirmed, and the cursor also disappears on GNOME.

**Comment by AlanGriffiths** [comment]
Not dug deep, but I was expecting `WlPointer::set_cursor()` to be called with `surface` unset. But this doesn't happen because gedit never calls `wl_pointer_set_cursor()` with a `NULL` pointer. So how it is hiding the cursor?!

**Comment by AlanGriffiths** [comment]
OK, this is what gedit is actully doing:
```
[1374086.622]  -> wl_surface@19.attach(nil, 0, 0)
[1374086.678]  -> wl_surface@19.commit()
[1396588.755]  -> wl_pointer@8.set_cursor(175469, wl_surface@19, 11, 12)
```
I.e. the surface is set, but should be unmapped. (Not what I thought the protocol says, but who can argue with existing practice.)
