### ISSUE TITLE
Deadlocks when invalid keymap set from miral

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2098]
To reproduce:
- Add `Keymap("invalid"),` to the `runner.run_with(...)` call in `examples/miral-shell/shell_main.cpp`

Expected:
- Error is printed or even shell aborts

Actual:
- Deadlock

**Comment by AlanGriffiths** [comment]
An easier reproducer is:
```
 WAYLAND_DISPLAY=wayland-99 miral-shell --keymap invalid
```

**Comment by wmww** [comment]
As far as I'm concerned this was fixed by #2103. Another issue can be opened for detecting invalid keymaps if needed.
