### ISSUE TITLE
Support virtual keyboard modifiers 

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2145]
As noticed by @AlanGriffiths in #2139, modifiers don't work on the virtual keyboard protocol.

To reproduce:
- Spin up a Squeekboard in Mir as described in #2139
- Focus on a terminal
- Enable `Ctrl` on the virtual keyboard
- Press `C`

Expected: same as Ctrl+C on a normal keyboard 

Actual: a `c` is typed into the terminal

**Comment by wmww** [comment]
We currently ignore the `.modifiers` request of `zwp_virtual_keyboard_v1`, which is the only indication the modifiers have changed (Squeekboard doesn't send a key request for ctrl). There are two obvious solutions:
1. Synthesize a ctrl-down key event when the modifiers indicate it's down. This will then be converted *back* to a modifiers event by the Wayland client
2. Make a new modifiers Mir event. This would imply moving XKB state tracking to the platforms.

2 seems like the correct solution (in wl_keyboard.cpp tracking keyboard state is considered a `HACK!`, so whoever originally wrong that code would probably agree with me).

**Comment by RAOF** [comment]
> 2. Make a new modifiers Mir event. This would imply moving XKB state tracking to the platforms.

Can we actually move XKB state tracking to the platforms? The client only sees a single `wl_keyboard`, so XKB state needs to be centralised *somewhere* unless, perhaps, we basically resync the full device state on any device switch?

**Comment by wmww** [comment]
What RAOF said is valid, and this is still an issue.
