### ISSUE TITLE
3-parameter CommandLineOption constructor overloads are ambiguous

### ISSUE THREAD

**Issue by WebDrake** [MirServer/mir#215]
When building on bionic, I get compilation errors when trying to use the various 3-parameter overloads of the `CommandLineOption` constructor, i.e. those overloads that do not include a `default_value` parameter:
https://github.com/MirServer/mir/blob/38ec6376284a88f94fd69f5c9e86fdc57a7a5a08/include/miral/miral/command_line_option.h#L72-L90

Specifically, if a lambda is provided to the constructor, the compiler appears unable to work out which `std::function<void(T)>` template instantiation is to be used.

The following simple test program can be used to illustrate the problem:

```C++
#include <miral/command_line_option.h>
#include <iostream>

int main(void)
{
    // ambiguous between all four possible 3-parameter overloads
    auto bool_flag = miral::CommandLineOption(
        [](bool is_set)
	{
	    std::cerr << "Boolean flag" << std::endl;
	},
	"bool", "Set a boolean flag");

    // ambiguous between `void(bool)`, `void(mir::optional_value<bool> const&)`
    // and `void(mir::optional_value<int> const&)`
    auto optional_bool_flag = miral::CommandLineOption(
        [](mir::optional_value<bool> const& value)
        {
            std::cerr << "Optional boolean flag" << std::endl;
        },
        "optional-bool", "Set an optional boolean flag");

    // ambiguous between `void(bool)` vs. `void(mir::optional_value<int> const&)`
    auto optional_int_flag = miral::CommandLineOption(
        [](mir::optional_value<int> const& value)
        {
            std::cerr << "Optional int flag" << std::endl;
        },
        "optional-int", "Set an optional int flag");

    // works
    auto optional_string_flag = miral::CommandLineOption(
        [](mir::optional_value<std::string> const& value)
        {
            std::cerr << "Optional string flag" << std::endl;
        },
        "optional-string", "Set an optional string flag");
}
```

(Build with e.g. `g++ -I/usr/include/mircore -I/usr/include/miral/ -c commandlineoption.cpp` to see the errors.)

The problem ~~does not show up when building on xenial, and~~ does not appear to be related to the `g++` version in use.

The best workaround I can find is to pass an explicit `std::function` instance to the `CommandLineOption` compiler, e.g.:

```C++
    auto bool_flag = miral::CommandLineOption(
        std::function<void(bool)>([](bool is_set)
	{
	    std::cerr << "Boolean flag" << std::endl;
	}),
	"bool", "Set a boolean flag");

```

**Comment by WebDrake** [comment]
Hmmm, with the minimal example alone, this _does_ show up on xenial, even though the original point of discovery (when modifying unity-system-compositor) did not.

**Comment by AlanGriffiths** [comment]
Hmm... Why didn't this connect to PR #228

**Comment by WebDrake** [comment]
I think it may be that you need the `Fixes #XXX` in the PR description (not the title).  Anyway, thanks! :-)
