### ISSUE TITLE
[mir_demo_client_wayland_egl_spinner] fails on Xvfb

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2154]
`mir_demo_client_wayland_egl_spinner` works when running on a real X11 backend but fails on `Xvfb`.

Real (Xwayland/GNOME) backend:
```
env -u WAYLAND_DISPLAY bin/mir_demo_server --test-client bin/mir_demo_client_wayland_egl_spinner
```
Failure when running on `Xvfb`:
```plain
env -u WAYLAND_DISPLAY xvfb-run bin/mir_demo_server --test-client bin/mir_demo_client_wayland_egl_spinner
...
[2021-08-24 14:46:30.444976] < -warning- > gbm-kms-buffer-allocator: Failed to bind EGL Display to Wayland display, falling back to software buffers: /home/alan/CLionProjects/mir/src/platform/graphics/egl_extensions.cpp(92): Throw in function mir::graphics::EGLExtensions::WaylandExtensions::WaylandExtensions(EGLDisplay)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: EGL display doesn't support EGL_WL_bind_wayland_display

[2021-08-24 14:46:30.445011] <information> gbm-kms-buffer-allocator: Cannot enable linux-dmabuf import support: EGL_EXT_image_dma_buf_import_modifiers not supported
[2021-08-24 14:46:30.445025] < - debug - > gbm-kms-buffer-allocator: Detailed error: : /home/alan/CLionProjects/mir/src/platform/graphics/egl_extensions.cpp(206): Throw in function mir::graphics::EGLExtensions::EXTImageDmaBufImportModifiers::EXTImageDmaBufImportModifiers(EGLDisplay)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: EGL_EXT_image_dma_buf_import_modifiers not supported
...
[2021-08-24 14:46:40.556321] <information> server_example_test_client.cpp: Client terminated by signal 11
```

In particular, this affects running smoke tests on `Xvfb`.

### A test setup where you can see what is going on

From your build directory:
```
sudo apt install xvfb x11vnc gvncviewer
env -u WAYLAND_DISPLAY x11vnc -create -localhost -cursor none -env FD_PROG=$(realpath --no-symlinks bin/mir_demo_server) -gone 'killall Xvfb'&
```
Wait for:
> The VNC desktop is:      octopull-PROX15-20:0
> PORT=5900
```
gvncviewer localhost
```
This will give you a (black) VNC window onto what is happening in the Xvfb session.

Now, if you're on a Wayland desktop, that will have created `wayland-1` (on an X11 desktop it will create)= `wayland-0`).

In another terminal/tab run
```
WAYLAND_DISPLAY=wayland-1 bin/mir_demo_client_wayland_egl_spinner
```
This will sometimes crash without showing anything, sometimes show for a second or two, and occasionally run to completion without error.

**Comment by graysonguarino** [comment]
Running eglinfo to check the EGL extensions on Xorg and xvfb, we get the following. Note the absence of EGL_WL_bind_wayland_display for xvfb.

### Xorg

X11 platform:
EGL API version: 1.4
EGL vendor string: Mesa Project
EGL version string: 1.4
EGL client APIs: OpenGL OpenGL_ES 
EGL extensions string:
    EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync
    EGL_CHROMIUM_sync_control EGL_EXT_buffer_age
    EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers
    EGL_EXT_swap_buffers_with_damage EGL_KHR_cl_event2
    EGL_KHR_config_attribs EGL_KHR_create_context
    EGL_KHR_create_context_no_error EGL_KHR_fence_sync
    EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace
    EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap
    EGL_KHR_no_config_context EGL_KHR_reusable_sync
    EGL_KHR_surfaceless_context EGL_KHR_swap_buffers_with_damage
    EGL_EXT_pixel_format_float EGL_KHR_wait_sync
    EGL_MESA_configless_context EGL_MESA_drm_image
    EGL_MESA_image_dma_buf_export EGL_MESA_query_driver
    EGL_NOK_texture_from_pixmap EGL_WL_bind_wayland_display
    
### xvfb:

X11 platform:
EGL API version: 1.5
EGL vendor string: Mesa Project
EGL version string: 1.5
EGL client APIs: OpenGL OpenGL_ES 
EGL extensions string:
    EGL_EXT_create_context_robustness EGL_KHR_cl_event2
    EGL_KHR_config_attribs EGL_KHR_context_flush_control
    EGL_KHR_create_context EGL_KHR_create_context_no_error
    EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses
    EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image
    EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image
    EGL_KHR_gl_texture_cubemap_image EGL_KHR_image_base
    EGL_KHR_no_config_context EGL_KHR_reusable_sync
    EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float
    EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image
    EGL_MESA_query_driver
    
Mir appears to be working as it should. Are Wayland bindings to be expected for xvfb at all?

**Comment by AlanGriffiths** [comment]
Seems like we're mentioning [EGL_]WL_bind_wayland_display in a few issues recently, e.g. #2288

It is too much to expect `mir_demo_client_wayland_egl_spinner` to fallback to software buffers. But segfaulting isn't a good failure mode.

Note also that the same code is used in `miral-shell` for a startup animation, that too could behave better.

Ideally, our EGL code should report the problem via an exception and that should be handled `mir_demo_client_wayland_egl_spinner` exiting with a message & failure code, and by `miral-shell` logging a warning (but continuing to operate normally).

**Comment by AlanGriffiths** [comment]
Speculation...

I've been experimenting with [running Mir on xvfb](https://github.com/MirServer/egmde-confined-desktop/pull/34) and experimented with adding `mir-test-tools` to that snap.

That means I could watching the display while starting `mir_demo_client_wayland_egl_spinner` and was surprised to see the animation starts running (definitely more than one frame) before the crash. If things can get that far, maybe they can be made to work after all.
