### ISSUE TITLE
Building v0.30.0.1 from source generates a package with 0.29.0 version

### ISSUE THREAD

**Issue by WebDrake** [MirServer/mir#217]
To reproduce:

* download https://github.com/MirServer/mir/releases/download/v0.30.0.1/mir-0.30.0.1.tar.xz, or clone git source and check out `v0.30.0.1` tag

* install build dependencies

* attempt to build deb package with `debuild -us -uc`

... results in:

```
 dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: source package mir
dpkg-buildpackage: source version 0.29.0
dpkg-buildpackage: source distribution UNRELEASED
```

... with the resulting `mir_0.29.0.dsc` containing:

```
Format: 1.0
Source: mir
Binary: libmirprotobuf3, libmirserver46, libmirplatform16, libmircore-dev, libmircommon-dev, libmirplatform-dev, libmirserver-dev, mirtest-dev, libmirclient9, libmirclient-dev, libmirclient-debug-extension1, libmirclient-debug-extension-dev, mir-demos, mir-utils, mir-doc, mir-test-tools, libmircore1, libmircommon7, mir-platform-graphics-mesa-x13, mir-platform-graphics-mesa-kms13, mir-platform-input-evdev7, mir-client-platform-mesa5, mir-client-platform-mesa-dev, mir-graphics-drivers-desktop, libmircookie2, libmircookie-dev, python3-mir-perf-framework, libmirrenderer-dev, mir-renderer-gl-dev, libmiral2, libmiral-dev
Architecture: any all
Version: 0.29.0
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Homepage: https://launchpad.net/mir
Standards-Version: 3.9.4
Vcs-Bzr: https://code.launchpad.net/mir
```

The same reproduces if instead I make a git clone, check out the `v0.30.0.1` tag, and attempt to build.

There's nothing specific (that I can find) about building the deb package in any of the online hacking guides, so this might just be a documentation issue (I might just not be using the expected means to build the package).  But I'm flagging it just in case.

**Comment by AlanGriffiths** [comment]
Seems we forgot to update debian/changelog for the 0.30 release. Not something that needs fixing now 0.31 is released.
