### ISSUE TITLE
Rename "Mir on X" window header 

### ISSUE THREAD

**Issue by GAN-Canonical** [MirServer/mir#2219]
As we promote the Ubuntu Frame simulation feature for developers to test their graphic applications before embedding them - we need to change the name on the window header;

"Mir on X" is not a good name.
Making it configurable in Mir, so that Ubuntu Frame can set it to something like "Ubuntu Frame simulator", is a better option.

Feature request:
The current Mir-on-Wayland support doesn't support a "windowed mode". That's not useful for the current scenario.

**Comment by AlanGriffiths** [comment]
> Feature request:
> The current Mir-on-Wayland support doesn't support a "windowed mode". That's not useful for the current scenario.

That is an unrelated feature, raised as a new issue: #2233

**Comment by wmww** [comment]
I think the way this should be implemented is a configuration option that changes the default titlebar name. In case we want to use it on other platforms, it shouldn't be X11-specific. Perhaps `nested-window-name`? `server-window-name`?
