### ISSUE TITLE
--display-scale 2 results in apps being scaled up every time output is resized

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2225]
From a visual inspection it looks like apps are being given the correct scale, rendering that and then being blown up more by Mir.

**Comment by AlanGriffiths** [comment]
This looks like the expected 2x -see the titlebar height:

![image](https://user-images.githubusercontent.com/9048879/143043057-6d2ac488-8fd8-4062-8bce-bf4c97b94799.png)

**Comment by wmww** [comment]
Ah! It appears the problem is that with `--display-scale 2`, the scale doubles every time the window is resized. On Sway, it gets auto-resized on startup in contrast to other desktops which leave it alone, so I always get it 4x to start. If I resize it more, things get even bigger. Does this happen for you?

**Comment by AlanGriffiths** [comment]
> Does this happen for you?

Yes. (You should reword the issue.)
