### ISSUE TITLE
Frontend aborts on unknown Wayland global names

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#2227]
The `wl_display_global_filter_func` aborts Mir [if it encounters a global name Mir is unaware of.](https://github.com/MirServer/mir/blob/86ebb35e9f62d33d11cce7b464482f1f03fe57fa/src/server/frontend_wayland/wayland_connector.cpp#L789). `mf::WaylandExtensions::init()` attempts to add known globals which are out of Mir's control, but unfortunately this list can never be complete - Mir graphics platforms can publish Wayland globals of their own. Worse, *EGL* implementations can publish globals, and these are entirely outside Mir's control.

We should not kill the server upon encountering an unknown global. We should work out what else to do.

**Comment by AlanGriffiths** [comment]
Presumably we should just `log_info()` & `return true`?

**Comment by wmww** [comment]
This error was added because if a shell adds a custom extension with an incorrect name it will be blindly enabled for all clients. I suppose this isn't too bad, and the error can be removed.
