### ISSUE TITLE
Keyboard focus given to popup only on key press

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2241]
Reproduce:
- Open gnome-terminal
- Open right-click menu
- Press a key

Expected: when menu opens, the cursor in the main window becomes empty

Actual: the main window cursor keeps blinking until a key is pressed, and Mir gives a warning message:
```
[2021-12-06 17:09:26.497322] < -warning- > mirserver: Sending keyboard event to wl_surface@34 even though it was not explicitly given keyboard focus
```

This also manifests as a minor OSK bug: the OSK does not go away as it should when the menu appears, and can be used to type into the main surface while the menu is still up (which does not dismiss the menu).

EDIT: this effects ALL apps, not just gnome-terminal

**Comment by AlanGriffiths** [comment]
Hmm, #2132 was a workaround for "weird focus stuff". Maybe we have fixed the real problem since.
