### ISSUE TITLE
[Xwayland] weird focus problems with CLion

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2255]
There are a lot of similar scenarios (c.f. #2250), documenting another one.

With keyboard focus in the CLion edit window:

1. Press Ctrl-K to bring up the commit dialog,
2. then press ESC to close it.

**Expect:** text cursor after the inserted text and able to type.
**Actual:** no text cursor and unable to type.

The editor does still respond to the keyboard (e.g. UP and DOWN arrows move the current line highlight).

**Comment by wmww** [comment]
note: when I tested with Intellij, I had to right-click the commit tab and click "switch to commit dialog" before I could reproduce.

**Comment by wmww** [comment]
I've confirmed this works correctly in Sway (so not an app or generic XWayland bug)

**Comment by AlanGriffiths** [comment]
> I've confirmed this works correctly in Sway (so not an app or generic XWayland bug)

Yes, also works with GNOME

**Comment by wmww** [comment]
Upon further investigation that doesn't just happen when using keyboard to switch focus. You can switch focus away with any method, and if you bring it back with either keyboard or by selecting the Mir-provided decorations then you get the strange focused-but-no-cursor behavior. Weston is even more broken (no cursor, and changing active line/selecting not possible) but Sway is fine.

**Comment by wmww** [comment]
Ah, it appears to fix this we need to both respect the input hint and support `_NET_WM_STATE_FOCUSED`. I have a prototype that works but hard-codes stuff. Will work on a real fix.

**Comment by wmww** [comment]
It turns out supporting `_NET_WM_STATE_FOCUSED` was not necessary to solve this.
