### ISSUE TITLE
Some (GTK based) fullscreen apps open the wrong menu

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2268]
Run xfce4-terminal in egmde (or Frame or miral-shell)

```
export WAYLAND_DISPLAY=wayland-99
egmde&
xfce4-terminal
```

Fullscreen (F11) the terminal

Now click on the "Help" menu

**Expect:** "Help" menu opens
**Actual:** "File" menu opens

This does not happen with maximised or restored windows, nor with kate. (Native GTK apps, like gnome-terminal use a "hamburger" menu that works as expected.)

xfce4-terminal menus work as expected on GNOME/Wayland

**Comment by wmww** [comment]
I can't reproduce on Ubuntu 21.04 (xfce-terminal 0.8.10). Tried miral-shell from master as well as the egmde snap.

**Comment by wmww** [comment]
Also can't repro on Arch

**Comment by AlanGriffiths** [comment]
Both of those working examples have a more recent GTK than core20/20.04. So this appears to be client-side.

**Comment by AlanGriffiths** [comment]
Cannot reproduce with Mir 2.7 - perhaps related to the focus issues resolved late in the release cycle
