### ISSUE TITLE
OSK does not hide when application closes

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2269]
Reproduced with ubuntu-frame and egmde (candidate)

1. Start server and OSK: `ubuntu-frame& ubuntu-frame-osk&`  (OSK does not appear - as expected)
2. Start gedit: `gedit` (OSK appears - as expected)
3. Close gedit: E.g. `Ctrl-C`

**Expect:** OSK closes
**Actual:** OSK remains open

Even after closing and restarting `ubuntu-frame-osk` it remains visible suggesting that internal state of Mir is incorrect rather than the OSK misbehaving.

**Comment by wmww** [comment]
Interestingly, if you close gedit by clicking the close button on the title bar instead of Ctrl+Cing it the OSK does go away.

**Comment by AlanGriffiths** [comment]
> Interestingly, if you close gedit by clicking the close button on the title bar instead of Ctrl+Cing it the OSK does go away.

I didn't see that, but I did try Ctrl-Shift-W when it doesn't go away.

**Comment by wmww** [comment]
Ah, GTK calls
```
13.3972 → zwp_text_input_v3@32a.disable()
13.3979 → zwp_text_input_v3@32a.commit()
```
If it shuts down normally, which hides the OSK
