### ISSUE TITLE
Nonblocking Wayland executor

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2309]
Currently, the Wayland executor has a performance optimization where it will invoke the work immediately if `spawn()` is called on the Wayland thread. This is correct in some cases, but may be undesirable in others (such as when an observable invokes observers under lock). There should be a nonblocking Wayland executor.

**Comment by AlanGriffiths** [comment]
Not going to spend time on this unless & until we need it. We won't need the issue before then or then
