### ISSUE TITLE
Nonblocking executor interface

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2310]
Some APIs may want to invoke an executor under lock, or otherwise need to guarantee the executor will not do the work immediately. We should have a subclass of `Executor`, that is only implemented by executors that never execute immediately.

See also #2309.

**Comment by RAOF** [comment]
There's potentially a useful hierarchy of Executor traits -
`Executor : NonBlockingExecutor : ConcurrentExecutor`, where the guarantees are
none : `spawn(work)` will not block waiting for `work` to finish : `spawn(work)` will have `work` executing in parallel.
