### ISSUE TITLE
Memroy leak on X11 platform window resize

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2312]
Reproduce:
- Open any Mir server on X11 (include mir_demo_server, indicating it's not a problem with the built-in clients)
- Resize the Mir-on-X window a bunch
- Watch system memory consumption fluctuate wildly, and end up significantly higher than it started

**Comment by graysonguarino** [comment]
Does this still persist? I am having trouble replicating this on Ubuntu 22.04 on GNOME on X.

**Comment by wmww** [comment]
I'm still seeing the fluctuations (not unsurprising considering we're tearing down and rebuilding a significant part of the rendering stack on each resize), but no significant upwards trend. I'm curious what fixed it, but not curious enough to bisect.
