### ISSUE TITLE
Double free on exit

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2313]
```plain
$ mir_demo_server
```
And close with [X] in the corner, or `Ctrl-Alt-BkSp`...
```
...
double free or corruption (fasttop)
Aborted (core dumped)
```

**Comment by wmww** [comment]
Not present in 2.6.0 (so needs to get fixed before release). Bisect points to 94fa9b4a31c96ce4a5316c88cdefa389412529cb. @RAOF might want to take a look.

**Comment by RAOF** [comment]
Huh. I ran the tests under valgrind and ASan to try and shake such things out! Let's see if I can reproduce locally…
