### ISSUE TITLE
Support for drag and drop

### ISSUE THREAD

**Issue by lduboeuf** [MirServer/mir#2317]
Hello,

Not 100% sure it is the right place to ask. ( i'm a Ubuntu Touch user)
Is there any plan to have drag and drop support within a single component ( e.g HTML drag and drop in a WebEngineView ) ?
https://github.com/ubports/morph-browser/issues/188

**Comment by AlanGriffiths** [comment]
I'm 100% sure this is the wrong place. (But I can't tell you the right one, sorry.)

WebEngineView is not part of Mir, nor is any part of the HTML support used by morph. (I'm not 100%, but as I understand it that is largely QML.)
