### ISSUE TITLE
Using the OSK "terminal" layout Ctrl is ignored

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2332]
Use the OSK with any Mir server (e.g. egmde) and switch to the "terminal" layout.

Press "Ctrl" and a key (say "C").

Expect: the `Ctrl-C` to be input
Actual: `c` is input

The log shows:
```
[2022-02-18 15:47:32.469921] <information> mirserver: Ignoring zwp_virtual_keyboard_v1.modifiers()
```

**Comment by AlanGriffiths** [comment]
There 's a comment in `VirtualKeyboardV1::modifiers()`:

```c++
    log_info("Ignoring zwp_virtual_keyboard_v1.modifiers()");
    // Currently we keep track of and send modifiers in the Wayland frontend, so handling this is not needed
```

While the premise is true the conclusion does not follow. (Because there are no key events sent for the modifiers.)

We either need to synthesise the modifier key events here, or introduce a way to pass the modifiers directly. (All part of the subtle mismatches between Mir's original event model and Wayland's)

**Comment by wmww** [comment]
Dup of #2145
