### ISSUE TITLE
Clicking on "New tab" option in qterminal results in SIGSEGV

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#2334]
With the new menu focus code in #2330 qterminal segfaults (in focus handling code) when clicking File->New Tab.

[Mir log with wayland protocol trace & WM trace](https://github.com/MirServer/mir/files/8112982/loggy.log)

**Comment by RAOF** [comment]
On further debugging, qterminal appears to be crashing in input-method code. Specifically, it's trying to send the “surrounding text” to the input method, but before the console has finished setting up it's internal state, so it accesses a null pointer.

Hah! And I can't test this properly on GNOME because *it* doesn't support `zwp_text_input_v2`

**Comment by RAOF** [comment]
Here are two `WAYLAND_DEBUG` logs for qterminal, both just clicking File→New Tab. [qterminal-only log with #3220 reverted](https://github.com/MirServer/mir/files/8114395/qterminal.working.log)
[qterminal-only protocol log](https://github.com/MirServer/mir/files/8114400/qterminal.log)

**Comment by AlanGriffiths** [comment]
Is this on 22.04? I can't reproduce on 20.04 (although I see problems _closing_ a qterminal tab)

**Comment by AlanGriffiths** [comment]
> Is this on 22.04? I can't reproduce on 20.04

I _can_ reproduce on 21.10.

**Comment by wmww** [comment]
I cannot repro on Arch. Haven't yet tried on Ubuntu. Someone who can repro should check if #2340 has any effect.

**Comment by RAOF** [comment]
#2340 does *not* fix this.

**Comment by RAOF** [comment]
Argh! I was trying to see whether there were any obvious differences in wayland trace under KWin, but qterminal doesn't even bind to `zwp_text_input_manager_v2` when run under kwin?!

**Comment by RAOF** [comment]
Good news, everyone! Rebooting and then running qterminal under kwin again resulted in it binding to `zwp_text_input_manager_v2`! And then crashing in exactly the same way as it crashes under Mir.

This looks to be a qterminal bug, not a Mir bug.
