### ISSUE TITLE
Cannot close tabs in qterminal

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2336]
Testing on 20.04 (probably can't reproduce on 22.04: c.f. #2334)

Run `miral-app -terminal qterminal`

Start qterminal `Ctrl-Alt-Shift-T`

Open another tab `Ctrl-Shift-T`

Attempt to close tab `Ctrl-Shift-W`

Expect: tab closes
Actual: qterminal UI locks up

This works with Mir 2.6

**Comment by AlanGriffiths** [comment]
This isn't cured by #2335

**Comment by AlanGriffiths** [comment]
If I use `--drop-wayland-extensions zwp_text_input_manager_v2` on 21.10 I can execute this scenario and get the expected results. (I.e. it works)

**Comment by AlanGriffiths** [comment]
This is weird. This works with egmde (both stable and beta), but not with a local build of miral-server with either of the corresponding commits.

**Comment by AlanGriffiths** [comment]
On 22.04 (with `--drop-wayland-extensions zwp_text_input_manager_v2` to avoid #2334) I see this intermittently _with the egmde shell_.

**Comment by AlanGriffiths** [comment]
On 20.04 I have only reproduced when starting qterminal from the CLion integrated terminal. (Nothing obvious in `env`)

**Comment by AlanGriffiths** [comment]
On 22.04 I'm running inside an egmde session, and that's a classic snap. As is CLion on 20.04.

So, _maybe_ this is only happening when launched (possibly indirectly) from a classic snap.

**Comment by Saviq** [comment]
Just in case this helps anything, I've gdb-dumped from qterminal:

```gdb
#0  0x00007fe43adf6eaf in Konsole::PlainTextDecoder::decodeLine (this=0x7ffc8127a210, characters=0x0, count=<optimized out>) at ./lib/TerminalCharacterDecoder.cpp:107
        i = 0
        outputCount = 1
#1  0x00007fe43ae0edc4 in Konsole::TerminalDisplay::inputMethodQuery (this=0x561f51421f70, query=<optimized out>) at ./lib/TerminalDisplay.cpp:2917
        lineText = {d = 0x7fe439c99ae0 <QArrayData::shared_null>}
                          _M_i = -1}, static is_always_lock_free = true}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7fe439c9a5f0 <QListData::shared_null>}, d = 0x7fe439c9a5f0 <QListData::shared_null>}}}
        cursorPos = <optimized out>
No symbol table info available.
...
```

Looks like it's crashing here:
https://git.launchpad.net/ubuntu/+source/konsole/tree/src/decoders/PlainTextDecoder.cpp?h=ubuntu/impish#n100

Now [refactored](https://invent.kde.org/utilities/konsole/-/commit/9f71cc38f329e18dd852911b35066550328e97d9), but still exists:
https://invent.kde.org/utilities/konsole/-/blob/master/src/decoders/PlainTextDecoder.cpp#L94-104

**Comment by wmww** [comment]
In `shell_main.cpp` having a keyboard shortcut that runs:
```
external_client_launcher.launch({"bash", "-c", "qterminal"});
```
opens a working QTerminal. The exact same line except `bash` replaced with `dash` results in a broken QTerminal. Replacing `qterminal` with `env | sort >env.txt` allows us to inspect the environment, and the difference in behavior persists even when they are identical except for the `_` variable.

**Comment by AlanGriffiths** [comment]
> Looks like it's crashing here:

OK, so indexing off a null pointer. Even if we're sending garbage that's not our fault.
