### ISSUE TITLE
Support idle inhibit protocol

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2346]
We should support a Wayland protocol that allows a client to acquire a wakelock, such as [idle_inhibit_unstable_v1](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/unstable/idle-inhibit/idle-inhibit-unstable-v1.xml) or whatever its successor is when we implement it. Whatever we implement we should make sure it's compatible with Firefox, which this one [seems to be](https://bugzilla.mozilla.org/show_bug.cgi?id=1587360).

I have no plans to work on this in the immediate future, but it should be fairly easy once it's needed.

**Comment by graysonguarino** [comment]
Solved with #2405
