### ISSUE TITLE
Global signal handling is broken

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#2364]
There are two problems in the signal handling code we do in `src/server/run_mir.cpp`.

Firstly: [here](https://github.com/MirServer/mir/blob/637984bb07ec9b25286630fe70bc037364e586b5/src/server/run_mir.cpp#L107) we have the problem that `signal` has unspecified behaviour in multithreaded programs. Mostly theoretical, as it seems to work, mostly?

Secondly, we have https://github.com/MirServer/wlcs/issues/30 which happens because `libwayland` installs a `SIGBUS` handler the *first* time that `wl_shm_begin_access()` is called in a process. When we have multiple calls to `run_mir()` in a process, this results in the old `SIGBUS` handler being restored at the end of the first `run_mir()`, then replaced by Mir's `SIGBUS` handler (that performs fatal error cleanup, then re-raises), but is *not* then replaced by `libwayland's` convert-SIGBUS-in-wl_shm-into-protocol-error handler, as libwayland thinks it has already installed it.

I've got a branch mostly fixing this, should be reviewable soon.

**Comment by AlanGriffiths** [comment]
> Firstly: [here](https://github.com/MirServer/mir/blob/637984bb07ec9b25286630fe70bc037364e586b5/src/server/run_mir.cpp#L107) we have the problem that `signal` has unspecified behaviour in multithreaded programs.

Mostly the program is single threaded at that point. But yeah.
