### ISSUE TITLE
Generated docs contain blank namespaces

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2365]
We're generating and publishing blank pages:

* https://mir-server.io/doc/namespacemir_1_1detail.html
* https://mir-server.io/doc/namespacemir_1_1frontend.html
* https://mir-server.io/doc/namespacemir_1_1graphics.html
* https://mir-server.io/doc/namespacemir_1_1scene.html
* https://mir-server.io/doc/namespacemir_1_1shell.html

There's also some overflow from the example lib:

* https://mir-server.io/doc/namespacewallpaper.html

**Comment by mattkae** [comment]
Our problem _might_ be that these namespaces are used for forward declaration, and doxygen decides that it found a namespace with _something_ inside of it.

**Comment by mattkae** [comment]
## Checklist

- [ ] https://mir-server.io/doc/namespacemir_1_1detail.html
- [ ] https://mir-server.io/doc/namespacemir_1_1frontend.html
- [ ] https://mir-server.io/doc/namespacemir_1_1graphics.html
- [ ] https://mir-server.io/doc/namespacemir_1_1scene.html
- [ ] https://mir-server.io/doc/namespacemir_1_1shell.html
