### ISSUE TITLE
Add autopkgtests to Mir for sanity checks against new uploads of Mesa, X.org

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#240]

**Comment by Conan-Kudo** [comment]
We might also want corresponding Fedora tests too: https://fedoraproject.org/wiki/CI

@stefwalter and @martinpitt would know more about how to make this (sadly I don't really know...)

**Comment by RAOF** [comment]
DEP8 tests were added in the Mir `1.4.0-0ubuntu1` upload.
