### ISSUE TITLE
Compilation error mir-2.5.0-2 AUR

### ISSUE THREAD

**Issue by grobx** [MirServer/mir#2404]
While installing mir 2.5.0-2 using AUR, I get this error (entire logs [here](https://pastebin.com/SQSsRVYa)):

> [ 58%] Built target mirplatforminputevdev
> [ 58%] Building CXX object tests/mir_test_framework/CMakeFiles/mir-public-test-framework.dir/input_device_faker.cpp.o
> [ 58%] Building CXX object tests/mir_test_framework/CMakeFiles/mir-public-test-framework.dir/open_wrapper.cpp.o
> [ 58%] Building CXX object tests/mir_test_framework/CMakeFiles/mir-public-test-framework.dir/test_server.cpp.o
> [ 58%] Building CXX object tests/mir_test_framework/CMakeFiles/mir-public-test-framework.dir/test_display_server.cpp.o
> [ 58%] Building CXX object src/platforms/gbm-kms/server/kms/CMakeFiles/mirplatformgraphicsgbmkmsobjects.dir/display_buffer.cpp.o
> /var/tmp/pamac-build-grobx/mir/src/mir-2.5.0/src/platforms/wayland/displayclient.cpp:282:1: error: missing initializer for member ‘wl_output_listener::name’ [-Werror=missing-field-initializers]
>   282 | };
>       | ^
> /var/tmp/pamac-build-grobx/mir/src/mir-2.5.0/src/platforms/wayland/displayclient.cpp:282:1: error: missing initializer for member ‘wl_output_listener::description’ [-Werror=missing-field-initializers]
>

**Comment by AlanGriffiths** [comment]
You are building with a newer version of wayland-protocols than Mir-2.5 was developed with. This was fixed in Mir 2.7 (https://github.com/MirServer/mir/commit/7bdcc0ac446213682ce2803462f2e841afb8dcf1)
