### ISSUE TITLE
Mir-on-Wayland platform deadlocks due to thread unsafety

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2450]
I can often reproduce by running an outer Mir normally, an inner Mir in wayland-debug GDB mode, launching weston-terminal on the inner Mir and playing around a bit.

The deadlock is in `mgw::DisplayClient::Output::swap_buffers()`. The cause appears to be `FrameSync::frame_done()` gets called after `swap_buffers()` returns (and thus after the `FrameSync` is destroyed). The `wl_callback_destroy(callback);` call in the destructor looks like it should prevent this, but I think libwayland does not guarantee further calls will not be delivered to the object after it is destroyed if events are being dispatched on a different thread than the destruction. In libwayland, the display mutex is locked during proxy destruction, however as you can see in `dispatch_event` in wayland_client.c the display mutex is unlocked while dispatching events. This allows the proxy return to complete and `swap_buffers()` to return before the `frame_done()` method has run.

Fixing this particular problem might not be too hard, but it calls into question the soundness of many aspects of the Wayland platform wrt threading. This needs a full review. If we solve each problem like this individually as they come up, we will waste a lot of time poking at bizarre race conditions.

**Comment by wmww** [comment]
There may be some threadsafety issues just within the Mir architecture. `MultiThreadedCompositor` holds non-owning pointers to `DisplayBuffer`s and uses them for rendering. When anything changes rendering is stopped and the compositor is re-initialized. The issue is that in `MediatingDisplayChanger::configure_for_hardware_change()` the display configuration is changed within a call to `server_action_queue->enqueue()` (which punts it to another thread. This means if `DisplayClient::remove_global()` destroys an output it may be used after free, even if that function waits for the display change call to complete before doing so.

**Comment by wmww** [comment]
Another way to see the problem is that `DefaultDisplayBufferCompositor` holds a ref to a `DisplayBuffer`, but no mechanism ensures the compositor is destroyed before the display buffer.

**Comment by wmww** [comment]
The 2nd problem I noted has been further diagnosed, and split off into #2457.

**Comment by AlanGriffiths** [comment]
Let me throw in another problem. This isn't the deadlock, but is in the same logic, so should likely be considered together.

With the latest trunk (post #2448) running on two monitors and GNOME...
```
 WAYLAND_DISPLAY=wayland-99 cmake-build-debug/bin/miral-app --wayland-host $WAYLAND_DISPLAY
```
Starts miral-shell across two monitors.

Now start a terminal (`Ctrl-Alt-Shift-T`) and position it across the monitors.

Finally, start glmark (`glmark2-wayland --fullscreen`).

Expect: terminal window painted correctly
Actual: terminal window painted with "noise"

This is _not_ affected by #2458
