### ISSUE TITLE
Using non-`ld` linker results in broken tests

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#2452]
Various tests in Mir will fail if built with `mold` or `lld`. This turns out to be due to a difference in symbol resolution - for the tests `ld.bfd` resolves GL symbols like `glCreateShader` to `libGLESv2.so`, but `mold` and `lld` both (correctly?) resolve those symbols to our GL stubs in `stub_gl.cpp`.

With the addition of `the_screen_shooter()` to the set of components that get initialised in tests, this results in the different resolution behaviour manifesting in a discernable difference. Since `the_screen_shooter()` transitively calls `glCreateShader`, builds with `lld` or `mold` add a GTest failure before triggering a (caught) exception, whereas builds with `ld.bfd` go through the system GL and do not generate the failure.

Conversation [here](https://matrix.to/#/!BLqVNwVsifZjueHWjt:libera.chat/$YNcSKyPXqbeF7qQmKQqql0CtnRboQ-c_NqJdaKlRetI?via=libera.chat&via=matrix.org&via=cooperteam.net)

**Comment by RAOF** [comment]
Looks like there's broadly 3 ways of dealing with this:
1. Override `the_screen_shooter()` in our headless tests. Requires first adding the *ability* to override `the_screen_shooter`. I'm not sure if this is a good idea?
2. Have `mir:stub-platform` instantiate a MockGL. GL calls now don't trigger failures, but will return failure, so we'll probably still pick up any attempts to use GL in headless tests?
3. Rebuild `mir:stub-platform` around a surfaceless EGL platform. This would let us use a real (software-rasterised) GL in the tests, but is the most work.

**Comment by wmww** [comment]
Would 3 apply to WLCS? Because being able to capture screenshots in WLCS and test their contents would be cool.

**Comment by RAOF** [comment]
3 would indeed apply to WLCS, which is one of the reasons it's a long-term wishlist bug. Which is… somewhere? I'm *sure* I filed a “use surfaceless EGL” bug *somewhere*…

**Comment by AlanGriffiths** [comment]
> I'm _sure_ I filed a “use surfaceless EGL” bug _somewhere_…

We might have closed it

**Comment by RAOF** [comment]
https://www.khronos.org/registry/EGL/extensions/MESA/EGL_MESA_platform_surfaceless.txt is the relevant EGL extension for implementing 3
