### ISSUE TITLE
Change from MAP_SHARED to MAP_PRIVATE in our clients

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2534]
In `wl_keyboard.keymap`, the protocol states:
> From version 7 onwards, the fd must be mapped with MAP_PRIVATE by the recipient, as MAP_SHARED may fail.

Our clients seem to to all use MAP_SHARED.

**Comment by graysonguarino** [comment]
Looking into this right now. I had misread the protocol and thought it said fds should be mapped with MAP_SHARED.
