### ISSUE TITLE
Send keyboard modifiers after keyboard enter

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2535]
The newest version of the protocol states that is required, it doesn't appear we do it.

**Comment by wmww** [comment]
Confirmed. If the modifiers change we send them before the enter event, and if they haven't changed we don't send them at all. The protocol states we need to always send modifiers after the enter event.

**Comment by AlanGriffiths** [comment]
This sounds like a likely cause for #2025 - and looking at the code, we don't seem to have any logic to send modifiers to a window gaining focus (whether or not they have changed).
