### ISSUE TITLE
libinput warns of client bug when I scroll my wheel

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#2565]
Every time I scroll the wheel of my Logitech MX Master Mir prints the following warning:
```
libinput error: client bug: Invalid event type LIBINPUT_EVENT_POINTER_AXIS (403) passed to libinput_event_pointer_get_scroll_value_v120()
```

I suspect that the recent libinput changes are slightly wrong?

**Comment by AlanGriffiths** [comment]
> the recent libinput changes are slightly wrong?

No, they are very wrong. We're not actually processing `LIBINPUT_EVENT_POINTER_SCROLL_WHEEL` at all. But we have also broken the processing of `LIBINPUT_EVENT_POINTER_AXIS` by adding logic only appropriate to `LIBINPUT_EVENT_POINTER_SCROLL_WHEEL` (which is what causes the message above).

In addition, if we were processing `LIBINPUT_EVENT_POINTER_SCROLL_WHEEL` we should be ignoring `LIBINPUT_EVENT_POINTER_AXIS` and that needs to be reflected in the tests (which need to work for both events).
