### ISSUE TITLE
Wheel-scrolling over remote assistance breaks input

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2572]
With Frame from `edge`, or `edge/mir-pr2566`, and edge -VNC:

```shell
WAYLAND_DISPLAY=wayland-99 ubuntu-frame --add-wayland-extensions \
    zwlr_virtual_pointer_manager_v1:zwp_relative_pointer_manager_v1:zwp_virtual_keyboard_manager_v1 &
WAYLAND_DISPLAY=wayland-99 wpe-webkit-mir-kiosk.cog
```

In a separate shell (because of #2571)
```shell
WAYLAND_DISPLAY=wayland-99 ubuntu-frame-vnc
```

Connect a VNC client and scroll your mouse wheel "through" it.

The client complains:

```plain
interface 'wl_pointer' has no event 9
```

And input stops working.

**Comment by AlanGriffiths** [comment]
OK, so "event 9" is `axis_value120` - i.e. Mir is sending `wl_resource_post_event(resource, Opcode::axis_value120, ...)` when the client doesn't expect it.

But all the Mir code I see gates this on `wl_resource_get_version(resource) >= 8` - which (modulo hard coded numbers) should be correct.

**Comment by AlanGriffiths** [comment]
This looks like a problem with `wpe-webkit-mir-kiosk`: it is negotiating `wl_seat` version 8 - which includes support for `axis_value120`, and then when it receives `axis_value120` it complains. I'd expect the same behaviour without VNC, but prior to #2566 we were not sending the correct `axis_value120` events on modern libinput.

**Comment by AlanGriffiths** [comment]
Confirmed that this also affects HW input (with Mir `dev`, which now includes #2566).

**Comment by AlanGriffiths** [comment]
With GNOME, is only offered at wl_seat at 5. But webkit doesn't display anyway

**Comment by AlanGriffiths** [comment]
Reported against the wpe-webkit snap: https://gitlab.com/glancr/wpe-webkit-snap/-/issues/38
