### ISSUE TITLE
CapsLock state gets stuck

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2592]
From time to time my CapsLock gets stuck on. I can still type lower case by keeping Shift down, so it's different to #2025.

Shifting focus _sometimes_ fixes it.

It feels related to idling out to some extent.

**Comment by Saviq** [comment]
Having encountered this again it seems to be triggered by shifting focus in the first place.

Turn CapsLock on, then Alt+Tab to another window. CapsLock is on, and can't turn it off. Going back to the original app, CapsLock sometimes fixes.

**Comment by AlanGriffiths** [comment]
OK, here's a sequence that seems repeatable (on `miral-app`):

1. Open a **terminal**
2. start **gedit**
3. Press CapsLock and type a couple of characters (show lowercase)
4. Press CapsLock and type a couple of characters (show uppercase)
5. `Alt-Tab` to **terminal**
6. Type a couple of characters (show uppercase)
7. Press CapsLock and type a couple of characters (_show uppercase_ - expect lowercase)
8. 4. `Alt-Tab` to **gedit**
9. type a couple of characters (show _lowercase_ - WTF?)
10. _goto 4_

**Comment by AlanGriffiths** [comment]
Urgh, this is another maze of twisty codepaths.

I've established that our logic for not sending modifiers when they haven't changed does not "do the right thing", but not how to fix it correctly, nor whether fixing it fixes actually this bug.

Time for a weekend and revisiting next week!

**Comment by AlanGriffiths** [comment]
Ah! I've found the place this is going wrong. Just need to work out the best way to fix it up.

**Comment by Saviq** [comment]
Fixed by #2631

**Comment by AlanGriffiths** [comment]
> Fixed by https://github.com/MirServer/mir/pull/2631

Not yet
