### ISSUE TITLE
test_wayland_generator fails (but not run by ptest target)

### ISSUE THREAD

**Issue by JamiKettunen** [MirServer/mir#2597]
Full build log: https://termbin.com/k6b5 (also includes `package-abis` failure as reported on #2596)
My `void-packages` fork with this packaging work: https://github.com/JamiKettunen/void-packages/tree/libmir

<p><details>
<summary>Clock to show/hide installed build-time dependencies with their versions</summary>
<pre><code>[host] pkg-config-0.29.2_3: found (https://repo-default.voidlinux.org/current)
[host] python3-Pillow-9.2.0_1: found (https://repo-default.voidlinux.org/current)
[host] libdrm-devel-2.4.112_1: found (https://repo-default.voidlinux.org/current)
[host] lttng-ust-2.12.2_1: found (https://repo-default.voidlinux.org/current)
[host] glib-devel-2.72.2_2: found (https://repo-default.voidlinux.org/current)
[host] cmake-3.22.2_1: found (https://repo-default.voidlinux.org/current)
[host] ninja-1.11.0_1: found (https://repo-default.voidlinux.org/current)
[check] gtest-devel-1.11.0_1: found (https://repo-default.voidlinux.org/current)
[check] umockdev-devel-0.17.13_1: found (/host/binpkgs/libmir)
[check] wlcs-devel-1.4.0_1: found (/host/binpkgs/libmir)
[check] elogind-246.9.2_3: found (https://repo-default.voidlinux.org/current)
[check] python3-dbusmock-0.19_3: found (https://repo-default.voidlinux.org/current)
[check] git-2.37.2_1: found (https://repo-default.voidlinux.org/current)
[target] boost-devel-1.80.0_1: found (/host/binpkgs/libmir)
[target] libglvnd-devel-1.4.0_1: found (https://repo-default.voidlinux.org/current)
[target] glm-0.9.9.8_1: found (https://repo-default.voidlinux.org/current)
[target] glog-devel-0.3.5_3: found (https://repo-default.voidlinux.org/current)
[target] gflags-devel-2.2.2_1: found (https://repo-default.voidlinux.org/current)
[target] lttng-ust-devel-2.12.2_1: found (https://repo-default.voidlinux.org/current)
[target] eudev-libudev-devel-3.2.11_1: found (https://repo-default.voidlinux.org/current)
[target] glib-devel-2.72.2_2: found (https://repo-default.voidlinux.org/current)
[target] wayland-devel-1.21.0_1: found (https://repo-default.voidlinux.org/current)
[target] libXcursor-devel-1.2.1_1: found (https://repo-default.voidlinux.org/current)
[target] libXrender-devel-0.9.10_2: found (https://repo-default.voidlinux.org/current)
[target] libdrm-devel-2.4.112_1: found (https://repo-default.voidlinux.org/current)
[target] libgbm-devel-22.1.7_1: found (https://repo-default.voidlinux.org/current)
[target] libepoxy-devel-1.5.10_1: found (https://repo-default.voidlinux.org/current)
[target] nettle-devel-3.8_1: found (https://repo-default.voidlinux.org/current)
[target] libxkbcommon-devel-1.4.1_1: found (https://repo-default.voidlinux.org/current)
[target] libinput-devel-1.21.0_1: found (https://repo-default.voidlinux.org/current)
[target] libxml++-devel-2.40.1_4: found (https://repo-default.voidlinux.org/current)
[target] yaml-cpp-devel-0.7.0_1: found (https://repo-default.voidlinux.org/current)
[target] gmpxx-devel-6.2.1_1: found (https://repo-default.voidlinux.org/current)
[target] freetype-devel-2.12.1_2: found (https://repo-default.voidlinux.org/current)
[target] libevdev-devel-1.12.0_1: found (https://repo-default.voidlinux.org/current)
[target] MesaLib-devel-22.1.7_1: found (https://repo-default.voidlinux.org/current)
[target] libatomic-devel-10.2.1pre1_3: found (https://repo-default.voidlinux.org/current)
[target] systemtap-devel-4.5_1: found (https://repo-default.voidlinux.org/current)
[runtime] elogind-246.9.2_3: found (https://repo-default.voidlinux.org/current)
[runtime] libmir-2.9.0_1: found (/host/binpkgs/libmir)
[runtime] weston-9.0.0_1: found (https://repo-default.voidlinux.org/current)
[runtime] xterm-372_1: found (https://repo-default.voidlinux.org/current)
[runtime] libmir-2.9.0_1: found (/host/binpkgs/libmir)</code></pre>
</details></p>

The relevant `test_wayland_generator` failure log (`expected.h` & `generated.h` don't match):
```diff
      Start 72: test_wayland_generator
72/81 Test #72: test_wayland_generator ...........................................................................................................***Failed    0.00 sec
diff --git a/builddir/mir-2.9.0/tests/acceptance-tests/wayland-generator/expected.h b/builddir/mir-2.9.0/build/tests/acceptance-tests/wayland-generator/generated.h
index 09484fa..11fe6cc 100644
--- a/builddir/mir-2.9.0/tests/acceptance-tests/wayland-generator/expected.h
+++ b/builddir/mir-2.9.0/build/tests/acceptance-tests/wayland-generator/generated.h
@@ -611,7 +611,7 @@ public:
 
     static Seat* from(struct wl_resource*);
 
-    Seat(struct wl_resource* resource, Version<6>);
+    Seat(struct wl_resource* resource, Version<8>);
     virtual ~Seat();
 
     void send_capabilities_event(uint32_t capabilities) const;
@@ -629,6 +629,11 @@ public:
         static uint32_t const touch = 4;
     };
 
+    struct Error
+    {
+        static uint32_t const missing_capability = 0;
+    };
+
     struct Opcode
     {
         static uint32_t const capabilities = 0;
@@ -642,7 +647,7 @@ public:
     class Global : public wayland::Global
     {
     public:
-        Global(wl_display* display, Version<6>);
+        Global(wl_display* display, Version<8>);
 
         auto interface_name() const -> char const* override;
 
@@ -664,7 +669,7 @@ public:
 
     static Pointer* from(struct wl_resource*);
 
-    Pointer(struct wl_resource* resource, Version<6>);
+    Pointer(struct wl_resource* resource, Version<8>);
     virtual ~Pointer();
 
     void send_enter_event(uint32_t serial, struct wl_resource* surface, double surface_x, double surface_y) const;
@@ -684,6 +689,9 @@ public:
     bool version_supports_axis_discrete();
     void send_axis_discrete_event_if_supported(uint32_t axis, int32_t discrete) const;
     void send_axis_discrete_event(uint32_t axis, int32_t discrete) const;
+    bool version_supports_axis_value120();
+    void send_axis_value120_event_if_supported(uint32_t axis, int32_t value120) const;
+    void send_axis_value120_event(uint32_t axis, int32_t value120) const;
 
     struct wl_client* const client;
     struct wl_resource* const resource;
@@ -724,6 +732,7 @@ public:
         static uint32_t const axis_source = 6;
         static uint32_t const axis_stop = 7;
         static uint32_t const axis_discrete = 8;
+        static uint32_t const axis_value120 = 9;
     };
 
     struct Thunks;
@@ -741,7 +750,7 @@ public:
 
     static Keyboard* from(struct wl_resource*);
 
-    Keyboard(struct wl_resource* resource, Version<6>);
+    Keyboard(struct wl_resource* resource, Version<8>);
     virtual ~Keyboard();
 
     void send_keymap_event(uint32_t format, mir::Fd fd, uint32_t size) const;
@@ -792,7 +801,7 @@ public:
 
     static Touch* from(struct wl_resource*);
 
-    Touch(struct wl_resource* resource, Version<6>);
+    Touch(struct wl_resource* resource, Version<8>);
     virtual ~Touch();
 
     void send_down_event(uint32_t serial, uint32_t time, struct wl_resource* surface, int32_t id, double x, double y) const;

X /builddir/mir-2.9.0/tests/acceptance-tests/wayland-generator/expected.h and /builddir/mir-2.9.0/build/tests/acceptance-tests/wayland-generator/generated.h do not match

- /builddir/mir-2.9.0/tests/acceptance-tests/wayland-generator/expected.cpp and /builddir/mir-2.9.0/build/tests/acceptance-tests/wayland-generator/generated.cpp match
```

**Comment by RAOF** [comment]
Huh. This is apparently a behaviour difference between our `test` and `ptest` targets; this doesn't fail with `ninja ptest`, and fails with `ninja test`.
