### ISSUE TITLE
Popups dismissed by Mir when parent clicked

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2604]
#2330 Fixed several previous and reoccurring issues (see #2324 for an upsettingly in-depth analysis), however it appears it's still not doing quite the same thing as other compositors.

The current Mir code roughly gives grabbing popups pointer focus but not keyboard focus. Therefore, when the user clicks on the parent window outside of a popup the click is consumed and the popup is dismissed. In wlroots and weston in this situation the parent gets the click events, and the popup is not automatically dismissed by the compositor.

To see a difference in behavior:
- Open Kate
- Open a menu and hover over an item with a submenu (the submenu will appear)
- Click
- On Mir, the submenu disappears
- On wlroots/weston the submenu does not disappear

In fixing this we must be mindful to not reintroduce #1941 or #2241. Those should be tested in WLCS, but I'll verify that.

**Comment by RAOF** [comment]
Right. As per [the protocol](https://wayland.app/protocols/xdg-shell#xdg_popup:request:grab), pointer events that *would* be delivered to the client should be delivered as normal (and I guess this should not end the grab/dismiss the popup).

Events that would *not* be delivered to the client should *not* be delivered, and *should* dismiss the popup.
