### ISSUE TITLE
miral does not expose Alarm functionality from MainLoop

### ISSUE THREAD

**Issue by graysonguarino** [MirServer/mir#2613]
MirAL currently has no wrapper for `mir::time::Alarm` and there is no way to create an alarmed callback in a similar vein to `miral::MirRunner::add_start_callback()` and `miral::MirRunner::add_stop_callback()`. This could come in handy for clients that need to delay function calls.

**Comment by AlanGriffiths** [comment]
Quick note that the similarity to `add_start_callback()` and `add_stop_callback()` is limited: these are called before running the server, whereas the primary usage of alarms is whilst the server is running.

What is needed is something along the lines of:

```c++
namespace miral
{
class AlarmFactory
{
...
   auto create_alarm(std::function<void()> const& callback) -> std::unique_ptr<Alarm>;
};
```

**Comment by Saviq** [comment]
Duplicate of #2543

**Comment by graysonguarino** [comment]
Closing this again as it actually may be unnecessary. Similar functionality can be achieved with `timerfd` which can be utilized once #2646 is completed.
