### ISSUE TITLE
Alt+Tab should (optionally?) reorder apps it's switching between

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2629]
Traditionally a double Alt+Tab toggles between two apps. In Mir, there's a list of clients (by connection order?) Alt+Tab cycles through, so you always have to cycle through the whole set to switch and then switch back.

Not sure if the current behaviour is desirable (as an option?), haven't seen it in other environments.

**Comment by AlanGriffiths** [comment]
Yes, the current code is simplistic: it treats each `Alt+Tab` event in isolation. Consider getting to a third app. Traditionally, you'd do:

1. Alt (down)
2. Tab
3. Tab
4. Alt (up)

`MinimalWindowManager` handles this as:

1. Alt+Tab
2. Alt+Tab

And if the second `Alt-Tab` returned to the first window navigating to a third window wouldn't be possible. Some years ago this was the simplest thing that could possibly work, but we should do something better.

**Comment by Saviq** [comment]
Fixed by #2981
