### ISSUE TITLE
Support mapping a Compose key

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2630]
Many keyboard layouts don't have a Compose key, but users map some other key to act as one.

Would be good to have a way to set this up.

Maybe there's a broader, existing standard we should employ? Akin to xmodmap?

**Comment by RAOF** [comment]
The compose key is already settable in the keymap selection, under xkboptions.

For example, my keymap specifier is
`us+dvorak+compose=menu,ctrl=nocaps`.

I've not tested that miriway handles the compose key, though; I've been using an external keyboard without a menu key 🤦‍♀️

**Comment by Saviq** [comment]
OK this worked for me: (**NB**: colons, not equal signs):

```
keymap=pl++compose:caps
```

Compose is handled correctly, though only _some_ apps (e.g. the GNOME text editor does) show the hint you're actually composing.
