### ISSUE TITLE
Shutdown crash when OSK is running

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2639]
Steps (handle `WAYLAND_DISPLAY` and `XDG_RUNTIME_DIR` as appropriate):
1. run e.g. `miriway-shell --add-wayland-extensions all`
2. run `ubuntu-frame-osk`
3. interrupt `miriway-shell`

Expected:
1. clean shutdown

Current:
1. segfault in https://github.com/MirServer/mir/blob/e3ef13e0165d5125042163c3689756627bd97549/src/miral/wayland_extensions.cpp#L379

[shutdown_gdb.txt](https://github.com/MirServer/mir/files/9567187/shutdown_gdb.txt)

**Comment by wmww** [comment]
I can't seem to repro with the steps given and I don't have a theory as to what's happening, but #2640 was an overall improvement to extension filtering. Can you give that a spin?

**Comment by Saviq** [comment]
@wmww that does seem to help, yes.

**Comment by Saviq** [comment]
Duplicate of #2209

**Comment by AlanGriffiths** [comment]
I'm surprised this code would be active during shutdown. #2640 might mask the symptoms, but probably doesn't address the root cause

**Comment by Saviq** [comment]
@AlanGriffiths could you reproduce? It's a 100% here if I:

```shell
env \
  -u LD_LIBRARY_PATH \
  MIR_SERVER_WAYLAND_HOST=$WAYLAND_DISPLAY \
  WAYLAND_DISPLAY=wayland-99 \
  miriway-shell --add-wayland-extension all \
& WAYLAND_DISPLAY=wayland-99 ubuntu-frame-osk \
& sleep 2; kill %1
```

**Comment by AlanGriffiths** [comment]
Yes, with a simpler incantation:
```plain
miriway --shell-component ubuntu-frame-osk& sleep 2; kill %1
```

**Comment by AlanGriffiths** [comment]
Annoyingly, as soon as I try with a local build it doesn't crash.

**Comment by AlanGriffiths** [comment]
OK, so I've not traced it all through yet but...

During "teardown" destroying the `DisplayServer` is destroying the `mf::WaylandConnector` and that (indirectly) destroys `WlrScreenCopyManagerV1Global` which destroys `mw::Global::~Global()` destructor calls `wl_global_destroy()`, and that (indirectly) calls `wl_global_is_visible()` and that ends up calling our `mf::WaylandConnector::wl_display_global_filter_func()` which leads to the segfault location.

1. I am not sure why `wl_global_destroy()` would need to be calling the filter logic
2. I don't think that `WlrScreencopyManagerV1Global` instances should exist during teardown as it should be tied to the client connections

I'm guessing that "something" used by the filtering logic has already been torn down at this point: hence the segfault
