### ISSUE TITLE
OSK stays on screen with unfocused app

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2651]
Steps:
1. run `miriway --shell-component ubuntu-frame-osk`
2. start [`telegram-desktop`](https://snapcraft.io/telegram-desktop)
3. focus a text field
4. unfocus the app

Expected:
1. OSK closes when the app is unfocused

Current:
1. OSK opens and stays on, ~~even when the app goes away (#2657)~~

There probably isn't enough knowledge in the compositor (OSK is like any other layer-shell surface) to hide it, so when the app misbehaves, we're at the mercy of other apps doing the right thing.

**Comment by wmww** [comment]
Ah, problem is #2270 only addressed #2269 for protocol version v3. v1 and v2 still have the bug.

**Comment by Saviq** [comment]
Reopening for the "unfocused" piece.
