### ISSUE TITLE
Bug in implementation of `xdg_output`

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#2666]
In the journal of my Miriway session, I see:
```
xdg-desktop-portal-kde[11860]: qt.qpa.wayland: zxdg_output_v1.name received after output has been initialized, this is most likely a bug in the compositor
```

We should work out if this is a Qt bug or a Mir bug.

**Comment by wmww** [comment]
It is indeed explicitly not supposed to be re-sent, and we do indeed re-send it.
