### ISSUE TITLE
Waking screens up after `idle-timeout` often stops or locks Mir up

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2674]
I would estimate about 1/3 of wakes ends up either with going back to gdm (without an apparent crash) or deadlock (sometimes it's still possible to `chvt …` remotely, sometimes not even that.

I will collect what I can find here.

Most recent example had me completely locked up, I had to reboot. GDB showed: [gdb.txt](https://github.com/MirServer/mir/files/9653069/gdb.txt)

**Comment by Saviq** [comment]
This sounds like #2632, but I've not seen evidence of actually crashing.

**Comment by Saviq** [comment]
Likely related to #2661

**Comment by AlanGriffiths** [comment]
I have yet to reproduce the problem (I've seen it a few times over the weeks, but nothing like 1/3).

I notice that you have a lot of threads inside iris_dri.so but my systems use i915. Maybe there's a behavioural difference with the newer hardware/driver that makes the problem a lot more noticeable.

**Comment by Saviq** [comment]
> I notice that you have a lot of threads inside iris_dri.so but my systems use i915. Maybe there's a behavioural difference with the newer hardware/driver that makes the problem a lot more noticeable.

Could well be, I do have some other issues with this hw (primarily HDMI through USB-C being unstable, to the point of unusable [LP#1988989](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1988989)).
