### ISSUE TITLE
[spread] Build failure on Fedora 35

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2686]
We have a build failure on Fedora 35 with multiple test failing because:
```plain
2022-10-04T00:58:01.8248432Z error: XDG_RUNTIME_DIR not set in the environment
2022-10-04T00:58:01.8248653Z Mir fatal error: Unable to bind Wayland socket
```
That looks like a change to the build environment.

In the Alpine and sbuild tasks we set XDG_RUNTIME_DIR, maybe we should do so for Fedora too

https://github.com/MirServer/mir/actions/runs/3178554440/jobs/5180169817

**Comment by Saviq** [comment]
Seems like a one-off?

https://github.com/MirServer/mir/actions/workflows/spread.yml

**Comment by AlanGriffiths** [comment]
> Seems like a one-off?

Reported so that we can track that

**Comment by AlanGriffiths** [comment]
Now on Fedora 36:

https://github.com/MirServer/mir/actions/runs/3217858860/jobs/5261331663
