### ISSUE TITLE
Create a `miral::ConfigurationOption` for `boost::filesystem::path`

### ISSUE THREAD

**Issue by graysonguarino** [MirServer/mir#2724]
In [Ubuntu Frame #103](https://github.com/MirServer/ubuntu-frame/pull/103) I proposed it would be nice to add a `boost::filesystem::path` variant of `miral::ConfigurationOption`. This way, every time a Miral user wants to take in a path as a configuration option, they do not need to check the validity of the path every time.

**Comment by AlanGriffiths** [comment]
I'm not sure we want to add a `ConfigurationOption` for every data type: dates, times, durations, colours, ...

But we should definitely prefer `std::filesystem` over `boost::filesystem`

**Comment by graysonguarino** [comment]
After creating a working implementation, I wasn't happy with it. I felt this would be useful so Miral could check the validity of paths instead of putting that responsibility on the user each time.

The problem is, *the user doesn't want a valid path every time.*

Case in point: Ubuntu Frame's `--diagnostic-path` option, *the very thing this was meant to improve*, specifically doesn't want an existent path every time.
