### ISSUE TITLE
Mir C++ Style Guide Missing

### ISSUE THREAD

**Issue by graysonguarino** [MirServer/mir#2727]
The following 404's: https://mir-server.io/doc/cppguide/index.html

**Comment by AlanGriffiths** [comment]
Missing in the `mir-docs` package too. (Not surprising as we copy that into the website)

**Comment by AlanGriffiths** [comment]
OK, so this is recent: it is in `mir-doc=2.8.0-0ubuntu22.04`, but not in `mir-doc=2.9.0-0ubuntu2`

**Comment by AlanGriffiths** [comment]
So, when building `doc` we are not building `guides`. But I don't see why:

```cmake
  add_custom_target(doc ${ALL}
                    COMMAND rm -rf ${CMAKE_BINARY_DIR}/doc/html ${CMAKE_BINARY_DIR}/doc/xml
                    COMMAND ${DOXYGEN_EXECUTABLE} ${PROJECT_BINARY_DIR}/Doxyfile
                    SOURCES ${PROJECT_BINARY_DIR}/Doxyfile
                    DEPENDS guides)
```

**Comment by AlanGriffiths** [comment]
Oh that's why `COMMAND rm -rf ${CMAKE_BINARY_DIR}/doc/html ${CMAKE_BINARY_DIR}/doc/xml` deletes the output from `guides`!
