### ISSUE TITLE
Segment fault when launching Mir on release/1.8

### ISSUE THREAD

**Issue by cat-master21** [MirServer/mir#2746]
A segment fault happens when launching Mir, via mir-shell, miral-kiosk, from display manager, etc. Here is the logfile when running `miral-kiosk --enable-mirclient --debug`
[log.txt](https://github.com/MirServer/mir/files/10203149/log.txt)

* Mir version: `release/1.8` branch
* Built on Fedora 37
* Compiler flags: `-GNinja %{?with_lto:-DMIR_LINK_TIME_OPTIMIZATION=ON} -DMIR_USE_PRECOMPILED_HEADERS=ON -DCMAKE_INSTALL_LIBEXECDIR="usr/libexec/mir" -DMIR_EGL_SUPPORTED=ON -DMIR_FATAL_COMPILE_WARNINGS=OFF -DMIR_RUN_INTEGRATION_TESTS=OFF -DMIR_BUILD_UNIT_TESTS=OFF -DMIR_PLATFORM="mesa-kms;mesa-x11;wayland;eglstream-kms"`

**Comment by AlanGriffiths** [comment]
The currently supported release of Mir is 2.10
