### ISSUE TITLE
Time to refresh xdg-shell implementation

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2778]
Seems we're behind the latest version:

![image](https://user-images.githubusercontent.com/9048879/211628729-723483c1-9b29-41dd-a4f4-bc2c492b2530.png)

From https://wayland.app/protocols/xdg-shell#compositor-support

**Comment by JamiKettunen** [comment]
In a similar vein Mir remains the only compositor on the site reporting support for [the deprecated `wl_shell`](https://wayland.app/protocols/wayland#wl_shell) (which got replaced by `xdg_wm_base`), though I'm not sure if dropping that is a nuanced issue; perhaps it's better as a separate issue to solve.
![image](https://user-images.githubusercontent.com/47358222/217413349-15d1cac0-ba16-4b7b-98e2-b63dfa17d4f1.png)

**Comment by AlanGriffiths** [comment]
@JamiKettunen it is definitely a separate discussion. We must also consider that the primary distribution mechanism for Mir is as a Snap. That means we can, for example, find ourselves running on an Ubuntu 16.04 system with the potential for clients that predate that deprecation.

**Comment by wmww** [comment]
Also unclear to me why dropping an interface is desirable. Our wl_shell implementation takes very little effort to maintain and should not effect clients that don't use it.

**Comment by JamiKettunen** [comment]
@wmww See https://gitlab.freedesktop.org/wayland/wayland/-/commit/698dde19 (`protocol: Add deprecation note about wl_shell`) and https://gitlab.freedesktop.org/wayland/wayland/-/commit/1078ee49 (`wl_shell is not mandatory`), it's just been deprecated for 5 years but I guess it doesn't matter that much and can be revisited at a later time anyway.

**Comment by AlanGriffiths** [comment]
As @wmww says, there is little cost to us from maintaining deprecated protocol extensions (it isn't like they are likely to change).

The situation is different between servers and clients. Clients using deprecated extensions _should_ move on. On the other hand, servers should support _what clients are using_.

In practice, some toolkits move slowly, and LTS releases, for example, contain old versions of toolkits.
