### ISSUE TITLE
Need a better display output naming solution

### ISSUE THREAD

**Issue by graysonguarino** [MirServer/mir#2815]
Looking into #2809 brought `src/common/output_type_names.cpp` to my attention. We need a better solution for reporting display names in wl_output. There is a TODO from 6 years ago talking about the need to introduce type safety.

**Comment by AlanGriffiths** [comment]
We also need an improved output naming solution for display configuration. Ideally one that also works for Wayland protocols.

Our configuration names outputs by numbering within type on each card independently, but that means we can have, for example, "HDMI-A-2" on two different cards.

 The Wayland frontend creates unique names by ignoring the card and type and using a global sequence number. But these names are not expected to be stable across compositor sessions
