### ISSUE TITLE
Popup positioning does not seem to respect constraint adjustment

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2857]
As tested by https://github.com/MirServer/wlcs/pull/276, Mir seems to always use slide constraint adjustment regardless of what's specified.

**Comment by AlanGriffiths** [comment]
That's weird, we had all the same positioning algorithms before switching to Wayland. I'd expect them to "just work".

**Comment by wmww** [comment]
```c++
void mf::XdgPositionerStable::set_constraint_adjustment(uint32_t constraint_adjustment)
{
    (void)constraint_adjustment;
    // TODO
}
```
lol
