### ISSUE TITLE
Window input geometry not respected for popups

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2941]
I haven't determined the cause so I don't know if this is true in all cases. To reproduce:
1. Open weston-terminal and another window
2. Focus weston-terminal and move it so that it's edge is over the other window
3. Notice that it casts a shadow on the other window, but when your cursor clicks in the shadowed area the other window gets focused (correct)
4. Right click in weston-terminal to open a popup
5. Notice that when the cursor is in the popups shadow the popup still gets cursor events

The problem can also be seen by which application's cursor is shown in these three screenshots:
![a](https://github.com/MirServer/mir/assets/9331264/21ef8516-cf37-43bb-8365-e3f26817eaea)
![b](https://github.com/MirServer/mir/assets/9331264/30943ece-440f-44d2-8c8f-c674275d5e6e)
![c](https://github.com/MirServer/mir/assets/9331264/9a2db0f7-04f7-4291-87e0-9167b77ef775)

**Comment by AlanGriffiths** [comment]
I've not noticed this before as it appears to be unusual for popups to cast shadows

**Comment by mattkae** [comment]
Interestingly enough, this also happens on regular Ubuntu (not running Mir). Perhaps this is a bug on the Weston side of things?
[Screencast from 07-25-2023 02:53:57 PM.webm](https://github.com/MirServer/mir/assets/25062299/693d525e-b855-4ba9-a3a6-8adfee552037)

**Comment by AlanGriffiths** [comment]
The suggested behaviour is reasonable, but as no other desktop (not even Weston) implements it I don't think we should spend time on it.
