### ISSUE TITLE
Broken X11 window controls (titlebar, drag, resize)

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2943]
The server-side X11 window decoration controls don't work. You can't drag or close X11 apps.

**Comment by AlanGriffiths** [comment]
I don't see this with Mir 2.13 (ppa:mir-team/release), only with main (ppa:mir-team/dev)

**Comment by AlanGriffiths** [comment]
And.. this is the commit that broke it: 8c2f31bf7598e4dd4f7e9e87dbd59b7d4549f2ef
