### ISSUE TITLE
Subcompositor not working

### ISSUE THREAD

**Issue by aleasto** [MirServer/mir#2950]
Here's a simple reproducer based on [hello-wayland](https://github.com/emersion/hello-wayland):
https://gist.github.com/aleasto/ba565b1c5a6f6347ce8cb81195d4b884

Expected output, as seen on kwin_wayland:
![Screenshot_20230527_023128](https://github.com/MirServer/mir/assets/8167495/13809880-1150-4032-8d4b-4fe0d9345013)

Ubuntu Touch 20.04 output:
![screenshot20230527_023025358](https://github.com/MirServer/mir/assets/8167495/2ccaa416-ed58-46c6-96a7-e588df699e9e)

The green subsurface is not rendered at all in mir.

**Comment by wmww** [comment]
When I run the given code on Mir built from current main I see the correct behavior (green square is visible). This could mean the Mir bug has been recently fixed, or it could mean the issue is in QtMir/Lomiri.

**Comment by AlanGriffiths** [comment]
The problem is in Lomiri. @mariogrip recently discovered that it only displays the first buffer it receives for each surface.
