### ISSUE TITLE
Keyboard meta key state gets out of step

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2985]
Originally reported [on discourse](https://discourse.ubuntu.com/t/mir-release-2-14-0/37082/11):

> Can’t write text on Firefox when switching window
> 
> 1. Open Firefox (not full screen, just windowed)
> 2. Open Konsole or Chromium (not full screen)
> 3. Focus on a text box of Firefox (e.g. the discourse message compositor I’m using for this message) and try to write. It works move to Konsole with ALT+TAB
> 4. go back to Firefox (mouse-click on Firefox window, do not use Alt+Tab again)
> 5. press any letter on the keyboard, you will see the Firefox menu appears. It behaves like if you are keeping the ALT key pressed.
>
> I can “release” the fake ALT key pressing the Meta/Super/Windows key on the keyboard and I’m be able to write again.

**Comment by mattkae** [comment]
## Reproducing
- Firefox opens the "Alt" menu upon the alt key going "up"
- The bug no longer happens when we remove the Alt + Tab behavior from `MinimalWindowManager`, which leads me to believe that this is a focus + input issue.

**Comment by mattkae** [comment]
## Researching
- I have confirmed that when the compositor handles an event, it does not allow the `wl_seat` to take that event
- I have confirmed that the Alt + Up event is appropriately sent to the tabbed-to process instead of firefox

**Comment by mattkae** [comment]
## Conclusion (so far)
- My best guess at the moment is that Firefox continues to think that alt is held down internally as it has received no information to cancel that state

**Comment by AlanGriffiths** [comment]
>     * My best guess at the moment is that Firefox continues to think that alt is held down internally as it has received no information to cancel that state

From the discussion above (and experience of seeing this but being unable to reproduce) I think this is handled correctly when focus changes using the keyboard. But not when using the mouse: I suspect there is code to resync the keyboard state on one path, but not the other. (Try looking in the Wayland frontend)

**Comment by mattkae** [comment]
Another way to experience this bug:
1. Open firefox and Konsole
2. Type some stuff in the address bar
3. Hold alt and then click on Konsole
4. Release alt once Konsole is focused
5. Click back to Firefox and note that you are still stuck in the same bugged state

I am not so certain that it is handled correctly when we use the keyboard either. That _might_ be a fluke as we end up sending firefox an "alt modifier released" event when we inevitable alt + tab back to it. But I will investigate further

**Comment by mattkae** [comment]
[This commit](https://github.com/MirServer/mir/commit/5edc2b24dfe39c380aee2c4386d299fcef0797f6) might be the culprit. 

Here's what I think is going on:
1. In `WlKeyboard::focus_on`, we call `helpers->refresh_modifiers` for the new client that comes online  (wl_keyboard.cpp:87)
2. However, in `KeyboardHelper::refresh_modifiers` (keyboard_helper.cpp:102) we call `set_modifiers` which checks if the old modifiers are equal to the new modifiers before sending them out. If they are equal, we don't send them out

In this case, because we are switching contexts, I believe that we _always_ want to inform the surface of the new modifiers
