### ISSUE TITLE
X11 apps' focus and input transparency wrong with subwindows

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#3024]

**Comment by AlanGriffiths** [comment]
An example of this is that CLion's menus cannot be used with a mouse. You can activate a menu and scroll down, but selecting an item fails.

Possibly connected: I've also noticed that the mapping from [Extended Window Manager Hints](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html) to MirWindowType in [xwayland_surface.cpp](https://github.com/MirServer/mir/blob/d11b9e9a2d7b5e05189731b0c8edbecc9b3e0f0f/src/server/frontend_xwayland/xwayland_surface.cpp#L188) seems rather odd (and doesn't match our specification)

**Comment by AlanGriffiths** [comment]
OK, so a bit of digging here:

CLion creates menus with `_NET_WM_WINDOW_TYPE_DIALOG` and Mir treats this as `mir_window_type_tip`. (I see no sense to any of that!)

**Comment by AlanGriffiths** [comment]
A bit more digging and submenus are created without any `_NET_WM_WINDOW_TYPE` but with both `override_redirect` and `is_transient_for`
