### ISSUE TITLE
display scaling breaks gl renderer clipping

### ISSUE THREAD

**Issue by seanpringle** [MirServer/mir#3036]
A display scaling factor appears to break Mir GL renderer window clipping:

* Using main at 7d67a3378cd22f5d8cf2b3442f9d64999d231bfe 
* In a Gnome3 shell Wayland session, set display scaling to 200%
* Run miral-shell directly pointing to the host Wayland, using the example tiling window manager:
```bash
WAYLAND_DISPLAY=mir DISPLAY=no MIR_SERVER_WAYLAND_HOST=wayland-0 build/bin/miral-shell --window-manager tiling
```
* Start a single instance of the Ctrl-Alt-T terminal window, or any app, or just watch the splash screen
* Window geometry looks full-screen but only the lower left quarter is rendered

```
[2023-09-08 17:24:17.272855] <information> mirserver: Initial display configuration:
[2023-09-08 17:24:17.272876] <information> mirserver: * Output 0: unknown connected, used
[2023-09-08 17:24:17.272891] <information> mirserver: . |_ Physical size 27.7" 610x350mm
[2023-09-08 17:24:17.272899] <information> mirserver: . |_ Power is on
[2023-09-08 17:24:17.272906] <information> mirserver: . |_ Current mode 3840x2160 60.00Hz
[2023-09-08 17:24:17.272913] <information> mirserver: . |_ Preferred mode 3840x2160 60.00Hz
[2023-09-08 17:24:17.272919] <information> mirserver: . |_ Orientation normal
[2023-09-08 17:24:17.272927] <information> mirserver: . |_ Logical size 1920x1080
[2023-09-08 17:24:17.272933] <information> mirserver: . |_ Logical position +0+0
[2023-09-08 17:24:17.272939] <information> mirserver: . |_ Scaling factor: 2.00
```

Full log in case: [mir-bug.txt](https://github.com/MirServer/mir/files/12565711/mir-bug.txt)

![mir-clipping](https://github.com/MirServer/mir/assets/120825/5bbb28ee-1ee2-4b5f-8a7d-ce2028f684b3)

I am currently compensating for this in `mir::renderer::gl::Draw()` by scaling the renderable's clip_area and the logical viewport to match the render_target size, before calculating the screen-space rectangle to pass to `glScissor()`, like this: 319466f75f27c46848bcc2d9ab92f2e404486429

But that feels hacky compared to (say) exposing the scaling factor via `CurrentRenderTarget`, or applying the transformation matrix to the clip_area? Also I'm unsure if it plays correctly with the way `mir::renderer::gl::update_gl_viewport()` centers the viewport. Also I'm just assuming a renderable clip_area is always using logical coordinates, based on the way the example tiling manager simply uses a tile rectangle to populate the clip_area... assumptions galore :)

Any advice? Am I doing something unsupported?

So far this is only an issue on my dev machine, where I'm testing a Mir window manager directly from Gnome. I've used miral-shell manually above only to reproduce the issue. On my target hardware the scaling factor is 1.0, so clipping is not a blocker there. It might be in the future though.

**Comment by AlanGriffiths** [comment]
I've yet to investigate, but my guess is that the `wayland` platform is providing inconsistent geometry for the output.

**Comment by AlanGriffiths** [comment]
OK, I've done a little investigation.

The root cause is that the wayland platform is passing through GNOME's scale as part of Mir's display configuration. That doesn't make sense as Mir should be doing scaling independently.

That is simple to fix: [host-scale.patch.txt](https://github.com/MirServer/mir/files/12575707/host-scale.patch.txt)

The problem is that this breaks pointer input in a couple of ways:

1. The cursor image isn't scaled (it needs to be scaled for the surface it is over)
2. The cursor position isn't calculated correctly (because the position within the surface needs to be scaled)

That's a bit more involved and I may need to come back to it
