### ISSUE TITLE
Can't resize GTK apps

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#306]
This is because GTK places the resize border outside the window, and Mir's default event handling restricts the active input region to the window. (So the client doesn't see the cursor in this resize border.)

Mir can handle this, it just needs some code writing to implement the non-default input region in the Wayland frontend.

Originally reported here: https://github.com/AlanGriffiths/egmde/issues/7

**Comment by wmww** [comment]
This will get fixed along with the input region support I'll need to do for subsurface input.

**Comment by AlanGriffiths** [comment]
Fixed by #336
