### ISSUE TITLE
Wayland platform results in cropped rendering

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#3091]
E.g.:
```
$ env -u DISPLAY MIR_SERVER_WAYLAND_HOST=$WAYLAND_DISPLAY WAYLAND_DISPLAY=wayland-1 ./build-Debug/bin/mir_performance_tests --gtest_filter=Hosted*fullscreen
```

Stable:
<img src="https://github.com/MirServer/mir/assets/231077/7b59e793-f629-47e4-b0a9-6c54474ab774" width="50%" />

Edge:
<img src="https://github.com/MirServer/mir/assets/231077/b7d04448-d5f9-4879-9975-01d3336ff69b" width="50%" />

**Comment by Saviq** [comment]
This happens also when running on gbm-kms, not doubly-nested.

I've not seen anything else that's wrong, e.g. `swaybg` covers the right outputs properly.

**Comment by AlanGriffiths** [comment]
Please clarify: Your command isn't referencing edge nor stable

**Comment by AlanGriffiths** [comment]
OK, I've just update to the current ppa:mir-team/dev and see problems with:

    env -u DISPLAY MIR_SERVER_WAYLAND_HOST=$WAYLAND_DISPLAY WAYLAND_DISPLAY=wayland-1 mir_performance_tests --gtest_filter=Hosted*fullscreen

It was working before the last update, so happened in the past few days

**Comment by AlanGriffiths** [comment]
FWIW it's the Wayland platform that's cropped, the same problem exists with, for example, miral-shell

**Comment by Saviq** [comment]
> FWIW it's the Wayland platform that's cropped, the same problem exists with, for example, miral-shell

miral-shell works fine here, sounds like it's racing then.

**Comment by AlanGriffiths** [comment]
> > FWIW it's the Wayland platform that's cropped, the same problem exists with, for example, miral-shell
> 
> miral-shell works fine here, sounds like it's racing then.

What are you running miral-shell on?

**Comment by Saviq** [comment]
> What are you running miral-shell on?

On the default GNOME/Wayland session on mantic:

```
$ env -u DISPLAY MIR_SERVER_WAYLAND_HOST=$WAYLAND_DISPLAY WAYLAND_DISPLAY=wayland-1 MIR_EXPERIMENTAL_HYBRID_GRAPHICS=1 ./build-Debug/bin/miral-shell
```

**Comment by AlanGriffiths** [comment]
> On the default GNOME/Wayland session on mantic:

I'm running the same session of Miriway/edge since yesterday morning, so the host might matter.

But anyway, this is weird! Both the display layout of the guest server and clients started in that session think the output size and the size of a fullscreen surface is `1920x1600` (correct) but the rendered area is approx `1280x1024`.

**Comment by AlanGriffiths** [comment]
OK, so this results from merging changes from trunk and on the platform API branch.

I know what's going wrong - the logic doesn't match, but I need to figure out the right logic to handle everything. (What a shame there are no tests!)
