### ISSUE TITLE
[VT console provider] Input device not recognised after disconnect/reconnect cycle

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#3149]
When using `--console=vt`, my USB keyboard works both if it is plugged in before Mir is started or if it is plugged in after Mir has started.

However, when it is unplugged, Mir (correctly) notices it has disappeared, but never notices when it is plugged *back* in.

This is specific to the `LinuxVirtualTerminal` console provider; when using logind I can plug and unplug the device multiple times and it works as expected.

**Comment by RAOF** [comment]
Aha! This is because in `evdev/platform.cpp` we rely on the `ConsoleProvider` to call the `removed()` method on the `InputDeviceObserver` when a device is removed, but only the `LogindConsoleProvider` actually does this.

For `LinuxVirtualTerminal`, failure to call `removed()` means that on hot-unplug the input device is removed, but the corresponding `mir::Device` is *not* removed from `device_watchers`, and so when plugged back in our udev ADDED event handler finds it in the `device_watchers` array, assumes we're already using it, and bails.

**Comment by AlanGriffiths** [comment]
Thanks for tracking this down. I can now reproduce
