### ISSUE TITLE
Switching VTs hangs the system

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#316]
Today I've experienced a lockup, twice on Fedora 28, once on Ubuntu 17.10.

What I did was run miral-desktop, try a few apps, switch back to VT2 and the system locked up. Upon `ssh`ing in it was impossible to "sudo chvt 4" until miral-shell was terminated (which unlocked the system). (Attaching a debugger to the miral-shell process didn't show anything immediately suspicions.)

(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7fd11af558c0 (LWP 31833) "miral-shell.bin" 0x00007fd1190df929 in poll () from /lib64/libc.so.6
  2    Thread 0x7fd10decc700 (LWP 31851) "Mir/Snapshot" 0x00007fd1193bc4fc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  3    Thread 0x7fd10cc1a700 (LWP 31852) "Mir/Comp" 0x00007fd1193bc4fc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  4    Thread 0x7fd105ffb700 (LWP 31857) "RPC Thread" 0x00007fd1190df929 in poll () from /lib64/libc.so.6
  5    Thread 0x7fd1057fa700 (LWP 31858) "miral-shell.bin" 0x00007fd1193bc4fc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  6    Thread 0x7fd0eafff700 (LWP 31861) "IPC Executor" 0x00007fd1193bc4fc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0

**Comment by AlanGriffiths** [comment]
Also happens with the archive Mir 0.31.0.1 on Fedora 28.

How can I have missed this for so long? I run miral-desktop and switch VTs multiple times a day, and I've only seen this problem today.

**Comment by AlanGriffiths** [comment]
@RAOF as you're currently poking around this code could you take a quick look at this one to see if there's something obvious?

**Comment by RAOF** [comment]
Was this not fixed by #375 ?

**Comment by AlanGriffiths** [comment]
Yep
