### ISSUE TITLE
Changing scale factor at runtime leads to misrendering

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#3165]
When using `gbm-kms` as the display platform and Mir is started with `--display-config static=$FILENAME`, changing the scale for an output in `$FILENAME` and saving it will result in Mir mis-rendering the scene on that output.

Specifically, the Renderer does not take the scaling into account so if an output started with `scale: 1` and was modified to `scale: 2`, only the top-left-hand quarter of the display will contain output (although if you move a window so some of it is outside the logical screen space, it will be rendered into the otherwise black section of the output).

This appears to be due to the reconfiguration process assigning the wrong logical size to the relevant `DisplaySink`; in `OverlappingOutputGroup` it's taken from the existing logical size of the output.

**Comment by AlanGriffiths** [comment]
Synchronicity! I just ran into this too.

**Comment by AlanGriffiths** [comment]
And, after checking out miriway --revision 2114 (Mir 2.15), this is new with 2.16

**Comment by AlanGriffiths** [comment]
Another weird thing to note: if the `.display` is rewritten without further changes another reconfiguration happens (but subsequent rewrites don't cause further reconfigurations)
