### ISSUE TITLE
Display with `orientation: left/right` flipped

### ISSUE THREAD

**Issue by freefos** [MirServer/mir#3185]
Hi,

After the 123-mir2.16.1 update, the frame screen is rotated 180 degrees.

![kiosk_rotation180](https://github.com/MirServer/ubuntu-frame/assets/121096589/8a305526-5e33-458f-8bca-d35d6a266c49)
The boot animation is still correct.

Reverted back to 121-mir2.15.0 and everything is back to normal.

This is my display configuration

```
layouts:
# keys here are layout labels (used for atomically switching between them).
# The yaml anchor 'the_default' is used to alias the 'default' label

  default:
    cards:
    # a list of cards (currently matched by card-id)

    - card-id: 0
      HDMI-A-1:
        # This output supports the following modes: 1920x1080@60.0, 1920x1080@59.9,
        # 1920x1080@30.0, 1920x1080@30.0, 1920x1080@50.0, 1920x1080@25.0, 1600x900@60.0,
        # 1280x1024@75.0, 1280x1024@60.0, 1152x864@75.0, 1280x720@60.0, 1280x720@59.9,
        # 1280x720@50.0, 1024x768@75.0, 1024x768@60.0, 800x600@75.0, 800x600@60.3,
        # 720x576@50.0, 720x480@60.0, 720x480@59.9, 640x480@75.0, 640x480@60.0,
        # 640x480@59.9, 720x400@70.1
        #
        # Uncomment the following to enforce the selected configuration.
        # Or amend as desired.
        #
        state: enabled  # {enabled, disabled}, defaults to enabled
        mode: 1920x1080@60.0    # Defaults to preferred mode
        position: [0, 0]        # Defaults to [0, 0]
        orientation: left       # {normal, left, right, inverted}, defaults to normal
        scale: 1
        group: 0        # Outputs with the same non-zero value are treated as a single display

  side_by_side:
    cards:
    # a list of cards (currently matched by card-id)

    - card-id: 0
      HDMI-A-1:
        # This output supports the following modes: 1920x1080@60.0, 1920x1080@59.9,
        # 1920x1080@30.0, 1920x1080@30.0, 1920x1080@50.0, 1920x1080@25.0, 1600x900@60.0,
        # 1280x1024@75.0, 1280x1024@60.0, 1152x864@75.0, 1280x720@60.0, 1280x720@59.9,
        # 1280x720@50.0, 1024x768@75.0, 1024x768@60.0, 800x600@75.0, 800x600@60.3,
        # 720x576@50.0, 720x480@60.0, 720x480@59.9, 640x480@75.0, 640x480@60.0,
        # 640x480@59.9, 720x400@70.1
        #
        # Uncomment the following to enforce the selected configuration.
        # Or amend as desired.
        #
        state: enabled  # {enabled, disabled}, defaults to enabled
        mode: 1920x1080@60.0    # Defaults to preferred mode
        position: [0, 0]        # Defaults to [0, 0]
        orientation: left       # {normal, left, right, inverted}, defaults to normal
        scale: 1
        group: 0        # Outputs with the same non-zero value are treated as a single display
```

What could be the issue here?

**Comment by AlanGriffiths** [comment]
After discussing with @Saviq we can confirm that `left` and `right` have been switched. Will investigate

**Comment by freefos** [comment]
Hi @Saviq,

I'm sorry for not getting back to you sooner.
Here you have my log file.
[kiosk1_ubuntuframe_log.txt](https://github.com/MirServer/mir/files/13919151/kiosk1_ubuntuframe_log.txt)

You've already verified that the left and right have been swapped.
I can confirm that when I switch to "right" the rotation is indeed "correct" but the touch isn't rotated correctly.

**Comment by AlanGriffiths** [comment]
This is weird!

I cannot reproduce on an intel system, but can on a rpi400.

**Comment by AlanGriffiths** [comment]
The easiest reproducer I have is to run:

    miral-app -demo-server --screen-rotation

**Expected:** pressing `Ctrl-Alt-<arrow>` moves the top of the screen to the side indicated by the arrow key

**Actual:** On RPi400, left and right are reversed

----
This is not just when running on hardware, it is also when running Mir-on-X (which uses a different driver) - that must help by excluding a lot of possible causes. (The fact this is, in some way, hardware specific helps explain how we missed it)

@freefos - it looks like you're also seeing this problem on an arm64 device - can you confirm?

**Comment by AlanGriffiths** [comment]
> Here you have my log file.
> [kiosk1_ubuntuframe_log.txt](https://github.com/MirServer/mir/files/13919151/kiosk1_ubuntuframe_log.txt)

Thanks, one thing that looks unusual here is that when Mir 2.16 is configuring the display we get:

    < - ERROR - > gbm-kms: Failed to set CRTC: No space left on device (28)

(And this doesn't happen with Mir 2.15.)

**Comment by freefos** [comment]
@AlanGriffiths These devices are running in a production environment.
I can only access them remotely.

We use the Odroid m1. (8GB RAM(2GB used))
16GB EMMC
```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           768M   57M  711M   8% /run
/dev/mmcblk0p2   15G  2.8G   11G  21% /
tmpfs           3.8G  8.0K  3.8G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/mmcblk0p1  240M   42M  186M  19% /boot
tmpfs           768M  4.0K  768M   1% /run/user/1000
```

Ordered an extra device so I can play around, test stuff, and see what's going on.
It should arrive at the end of this week.

**Comment by AlanGriffiths** [comment]
> We use the Odroid m1. (8GB RAM(2GB used))

Thanks. The internet says that's an ARM Cortex-A55: an arm64 device

**Comment by freefos** [comment]
That's correct.

It's using the Rockchip RK3568B2 CPU.
[https://wiki.friendlyelec.com/wiki/images/3/35/Rockchip_RK3568B2_Datasheet_V1.0.pdf](https://wiki.friendlyelec.com/wiki/images/3/35/Rockchip_RK3568B2_Datasheet_V1.0.pdf)

[https://www.hardkernel.com/shop/odroid-m1-with-8gbyte-ram/](https://www.hardkernel.com/shop/odroid-m1-with-8gbyte-ram/)

**Comment by AlanGriffiths** [comment]
OK, the point of variation between platforms is this code, on our arm64 devices we are taking the `graphics::gl::OutputSurface::Layout::TopRowFirst` codepath:

```c++
void mrg::Renderer::set_output_transform(glm::mat2 const& t)
{
    auto new_display_transform = glm::mat4(t);

    switch (output_surface->layout())
    {
    case graphics::gl::OutputSurface::Layout::GL:
        break;
    case graphics::gl::OutputSurface::Layout::TopRowFirst:
        // GL is going to render in its own coordinate system, but the OutputSurface
        // wants the output to be the other way up. Get GL to render upside-down instead.
        new_display_transform *= glm::mat4{
            1.0, 0.0, 0.0, 0.0,
            0.0, -1.0, 0.0, 0.0,
            0.0, 0.0, 1.0, 0.0,
            0.0, 0.0, 0.0, 1.0
        };
        break;
    }

    if (new_display_transform != display_transform)
    {
        display_transform = new_display_transform;
        update_gl_viewport();
    }
}
```

The resulting `new_display_transform` *looks* wrong (and clearly has the wrong effect), but I need to understand the code better before proposing a fix.

**Comment by AlanGriffiths** [comment]
@freefos the fix is now part of a ["call for testing"](https://discourse.ubuntu.com/t/call-for-testing-ubuntu-frame-mir-kiosk/40683/11)

**Comment by freefos** [comment]
@AlanGriffiths, @Saviq 

I finally received my test device and had the time to install it.
In the future, I will be able to test things much quicker.

I can confirm that 123-mir2.16.2 fixed the orientation.

But there seems to be a new issue:
The mouse cursor is a lot slower on 123-mir2.16.2 compared to 121-mir2.15.0.

On 121-mir2.15.0 the mouse cursors moves very smooth.
On 123-mir2.16.2 the mouse cursors moves very slowly and stutters.

Here are the logs of both versions.
[log_121-mir2.15.0.txt](https://github.com/MirServer/mir/files/14065325/log_121-mir2.15.0.txt)
[log_123-mir2.16.2.txt](https://github.com/MirServer/mir/files/14065326/log_123-mir2.16.2.txt)
