### ISSUE TITLE
The mouse cursor is a lot slower on 2.16.2 compared to 2.15.0

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#3205]
This has been seen by @freefos on an ARM Cortex-A55 based SOC (Rockchip RK3568B2) and might be restricted to ARM systems.

> The mouse cursor is a lot slower on 123-mir2.16.2 compared to 121-mir2.15.0.
> 
> On 121-mir2.15.0 the mouse cursor moves very smooth.
> On 123-mir2.16.2 the mouse cursor moves very slowly and stutters.

[Original report](https://github.com/MirServer/mir/issues/3185#issuecomment-1912080208)

**Comment by Saviq** [comment]
@RAOF would you be able to look at this in your am?

**Comment by RAOF** [comment]
Hm. So on careful inspection the only thing that stands out between the two logs is the framebuffer config: 2.15 uses an RGBA 8880 config, 2.16 uses an RGBA 8888 config.

I suspect that the stuttery mouse is an artifact of a general performance difference - @freefos, is that correct?

#3206 re-adds hardware cursor support, which will likely make the *cursor* more responsive.

I think I need to add some extra information to our logging in order to track down what is actually happening here. We don't have enough information about how the framebuffer is being allocated to say anything more concrete.

**Comment by Saviq** [comment]
@freefos could you please try `snap refresh ubuntu-frame --channel edge/mir-pr3206`? It has the hardware accelerated cursor again.

**Comment by freefos** [comment]
@Saviq I've tested the new version.
The performance is the same and there is no cursor anymore.

There seems to be an issue with setting the cursor.
A reboot didn't help.
```
2024-01-29T14:11:00+01:00 ubuntu-frame.daemon[14180]: [2024-01-29 14:11:00.697377] < -warning- > gbm-kms: set_cursor: drmModeSetCursor failed (No such device or address)
2024-01-29T14:11:00+01:00 ubuntu-frame.daemon[14180]: [2024-01-29 14:11:00.705170] < -warning- > gbm-kms: move_cursor: drmModeMoveCursor failed (Bad address)
```
[log_129-mir2.16.2+dev68.txt](https://github.com/MirServer/mir/files/14084703/log_129-mir2.16.2%2Bdev68.txt)

**Comment by freefos** [comment]
@Saviq 
Currently just by scrolling on a webpage. 
So not very scientific...

How do you guys test this?

**Comment by Saviq** [comment]
@freefos well, we monitor the results from glmark2, and CPU/memory consumption for a handful of scenarios. These didn't surface any problems with 2.16, but that may well not covering some cases, one of which you may have encountered.

**Comment by freefos** [comment]
@Saviq I did some tests with [MotionMark](https://browserbench.org/MotionMark1.3/)

Here are the results:
121-mir2.15.0
![image](https://github.com/MirServer/mir/assets/121096589/f17d448f-cf3d-4265-ae1a-a529727b3d8b)

129-mir2.16.2+dev68
![image](https://github.com/MirServer/mir/assets/121096589/02dd460a-7262-4ae3-b5c0-bd0dd5261dbc)

**Comment by AlanGriffiths** [comment]
> The performance is the same and there is no cursor anymore.

I tried to reproduce on RPi400. First thing I noticed was "no cursor" - and that was with Frame/stable!

I'm not sure what can have changed (obviously not Frame/Mir), but found that running in devmode got the cursor back.

**Comment by Saviq** [comment]
Huh! The most suspect thing here to me is the 15fps (that's _detected_, not benchmarked).

On Intel, I couldn't notice any difference, but on a Pi4 I also got the detected framerate at 15fps. The CPU usage of frame is significantly higher just looking at the main page of MotionMark on wpe-webkit-mir-kiosk.

**Comment by AlanGriffiths** [comment]
> I tried to reproduce on RPi400. First thing I noticed was "no cursor" - and that was with Frame/stable!

Sorry for the noise. This happens when running Frame directly as a use (as in `frame-it wpe-webkit-mir-kiosk.cog`), but doesn't happen when run as a root daemon.

**Comment by AlanGriffiths** [comment]
> The CPU usage of frame is significantly higher just looking at the main page of MotionMark on wpe-webkit-mir-kiosk.

Confirmed (2.15 is around 15-20% CPU, 2.16 is around 50-70%)

**Comment by RAOF** [comment]
> There seems to be an issue with setting the cursor. A reboot didn't help.
> 
> ```
> 2024-01-29T14:11:00+01:00 ubuntu-frame.daemon[14180]: [2024-01-29 14:11:00.697377] < -warning- > gbm-kms: set_cursor: drmModeSetCursor failed (No such device or address)
> 2024-01-29T14:11:00+01:00 ubuntu-frame.daemon[14180]: [2024-01-29 14:11:00.705170] < -warning- > gbm-kms: move_cursor: drmModeMoveCursor failed (Bad address)
> ```

Looks like there's an additional failure path the gbm-kms platform needs to address; it would appear that the rockchip DRM driver does not support the standard HW cursor API.

> On Intel, I couldn't notice any difference, but on a Pi4 I also got the detected framerate at 15fps. The CPU usage of frame is significantly higher just looking at the main page of MotionMark on wpe-webkit-mir-kiosk.

Ok. My hypothesis is that the CPU copy output fallback is being taken here, but we don't have any logging of the actual display/rendering topology we select.

**Comment by Saviq** [comment]
> On further thought; it's not _Firefox_ at all; it's WebKit. I wonder how MotionMark asks for the display refresh rate, and how WebKit calculates it.

Yeah it's certainly something it's measuring - on its first page you can see it's changing colours, I bet it's measuring how quickly it can do that, and approximating FPS, capped at vsync. I think it's a result of the slower rendering, not a symptom / cause.
