### ISSUE TITLE
Possible memory leak while a VNC client is connected

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#3215]
> alan_g:
> FYI I've just run wpe-webkit on miriway with Frame-vnc configured. There's a very obvious memory drain impact of connecting a viewer.
This needs both the hardware and virtual outputs rendering. (Wpe-webkit is still on the motionmark page fwiw)
(All this is running on the RPi400 I have ready to test the release)

So the currently known reproducer is running a busy page in WPE, with a VNC client connected.

> Saviq
Hmm VNC isn't virtual output, though?

> alan_g
No, this is remote assist mode

> Saviq
Right, so it's somewhere on the screencopy path, not virtual platform

**Comment by AlanGriffiths** [comment]
I've just tried running miriway.vnc-server - that shows the drain too

**Comment by AlanGriffiths** [comment]
A bit more investigation. All with Wpe-webkit is on the motionmark homepage: https://browserbench.org/MotionMark1.3/ (in case that is relevant).

1. I've tried running with a scrolling terminal and with neverputt instead of wpe-webkit-mir-kiosk.cog. Neither shows the same problem
2. I've tried WPE without the VNC client connected. No problem.

The excess memory is mostly with the Webkit process and is all freed if wpe-webkit-mir-kiosk.cog is closed.

**Comment by AlanGriffiths** [comment]
> 3. I've tried a virtual output with VNC. No problem.

Well, maybe. After the initial settling period, memory use went up by around 1% over 20min.

**Comment by AlanGriffiths** [comment]
This apparent memory leak in wpe-webkit isn't leaking buffers in our the wayland comminucation.

My test scenario is:

    snap set wpe-webkit-mir-kiosk url=https://browserbench.org/MotionMark1.3/
    WAYLAND_DEBUG=client wpe-webkit-mir-kiosk.cog &> without-remote-assist

Wait for the "framerate" to be detected and Alt-F4 to close.

```bash
alan@Octopull-x1c1-2404:~$ grep "new id wl_buffer@" with-remote-assist  | wc -l
493
alan@Octopull-x1c1-2404:~$ grep "wl_buffer@.*\.destroy()" with-remote-assist  | wc -l
490
alan@Octopull-x1c1-2404:~$ grep "new id wl_buffer@" without-remote-assist  | wc -l
405
alan@Octopull-x1c1-2404:~$ grep "wl_buffer@.*\.destroy()" without-remote-assist  | wc -l
401
alan@Octopull-x1c1-2404:~$ 
```

There are 3 or 4 buffers left at the end, but nothing to explain the growing memory footprint.

While there are some minor timing differences in the logs, nothing leaps out as being problematic.

When VNC is attached, WPE does allocate new buffers and `destroy()` more, but that seems to be accounted correctly at least within the wayland protocol.
[with-remote-assist.txt](https://github.com/MirServer/mir/files/14168976/with-remote-assist.txt)
[without-remote-assist.txt](https://github.com/MirServer/mir/files/14168977/without-remote-assist.txt)

**Comment by AlanGriffiths** [comment]
Reported this at https://gitlab.com/glancr/wpe-webkit-snap/-/issues/58

**Comment by Saviq** [comment]
@AlanGriffiths could you try with the 22-based snap built below?

https://launchpad.net/~mir-team/+snap/wpe-core22-test

I'll also have a look if there's a newer cog/wpe/* version to use, in case it has that fixed.

**Comment by AlanGriffiths** [comment]
> @AlanGriffiths could you try with the 22-based snap built below?

That looks significantly better on Intel. Getting the Rp4 out of the drawer to check arm64...

**Comment by AlanGriffiths** [comment]
Closing as this now looks like a [wpe-webkit issue](https://gitlab.com/glancr/wpe-webkit-snap/-/issues/58)
