### ISSUE TITLE
Surface frame events don't have timestamps

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#341]
In `WlSurface::send_frame_callbacks()`, the second argument of `wl_callback_send_done()` should be a timestamp. It is currently hard coded to `0`. There are currently no known bugs caused by this.

**Comment by AlanGriffiths** [comment]
@wmww please write a failing, disabled test

To do the right thing, we would need to send the last frame time here - the `Display` has a `Frame` object you can get with the timing, you might need to plumb `the_display()` through to the wayland frontend.

**Comment by AlanGriffiths** [comment]
Solved by #1974
