### ISSUE TITLE
Touch input not working on subsurfaces

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#347]
With #346  keyboard and mouse input seems to be working on subsurfaces, but not touch input. Test case:

1. Start gedit.
2. Touch "Open"
3. Touch a recent doc. Expect it opens, actual nothing
4. Touch "Other Document...". Expect open dialog, actual nothing.

**Comment by AlanGriffiths** [comment]
@wmww do you have a touch enabled device?

**Comment by wmww** [comment]
I do not have a touch device, but the fix (#350) was easy enough without. Still needs testing, obviously.
