### ISSUE TITLE
Warning when downsizing GTK windows

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#354]
To reproduce:
* Open a GTK window
* Resize by clicking and dragging just outside the window border
* Must resize the bottom edge, right edge or bottom right corner
* As soon as the window is smaller then it was at the start of the resize, a single instance of the warning `surface->transform_point() returned nullopt for motion action` is shown

This may or may not have to do with the edges of windows flickering on resize.

**Comment by AlanGriffiths** [comment]
AFACS it has nothing to do with the flickering. What happens is that the surface rectangle and input area resize by several pixels and the resulting cursor position is one pixel to the right/bottom of the input area.

E.g. Input rectangle {26, 22, 866, 874}, cursor {892, 256} (where 892 == 26+866).

Not sure why this warrants a warning message. (Nor why, during a resize drag, we care about the input area.)

**Comment by wmww** [comment]
I believe there are multiple valid cases were that warning shows up, so I will remove it. In this case however, we shouldn't be trying to send pointer events to surfaces while resizing or moving the surface with that pointer.

**Comment by wmww** [comment]
Fixed by #405
