### ISSUE TITLE
[mirscreencast] segfaults after "Permission denied" error on Fedora

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#38]
Seen on both Fedora 26 (real, but old x386 hardware) and Fedora 27 VM. (It might "just" be the drivers.)

Message: Failed to mmap buffer
Location : mesa/client/client_buffer.cpp(64)

**Comment by AlanGriffiths** [comment]
I had a chance to try recent hardware with F27. I see the same error.

**Comment by AlanGriffiths** [comment]
Oh, I see the same message on Ubuntu. The crash on Fedora is because mirscreencast then "falls back" to (Mir) EGL which isn't supported on Fedora.

**Comment by AlanGriffiths** [comment]
OK, so the problem is that:

1. the server-side code allocates "hardware" buffers in CompositingScreencast::create_session()
(That leads to the "Permission denied" error in the client when it tries to use "software" buffers)

2. the client side code that handles "software" buffers uses Mir EGL, and that isn't available everywhere.

Thoughts:

1. There ought to be a better way to co-ordinate the client and server buffer usage, the client should know what type of buffer its getting.

2. Can we handle "software" buffers in the client using just GL?

**Comment by RAOF** [comment]
For (2) the answer is “no”.

The buffer management is basically what EGL is *for*. That said, we *could* handle hardware buffers using a non-Mir EGL platform - at the cost of mirscreencast *only* working on mesa.

To do that you'd extract the dma-buf FD from the (mesa-platform-specific) buffer package and import it using the dma-buf import extension for EGLImage.

**Comment by AlanGriffiths** [comment]
> The buffer management is basically what EGL is for. That said, we could handle hardware buffers using a non-Mir EGL platform - at the cost of mirscreencast only working on mesa.
> 
> To do that you'd extract the dma-buf FD from the (mesa-platform-specific) buffer package and import it using the dma-buf import extension for EGLImage.

Right, so we *could* make this work through the mirclient extensions APIs (effectively detecting Mesa), but YAGNI.
