### ISSUE TITLE
Fails to restore VT after quitting

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#386]
While testing #385 by running `miral-desktop` I found that quitting using Ctrl-Alt-Backspace wouldn't restore the VT into a working state. I thought it might be a bug in the MP, but the same thing happens on master, too.

Running `chvt 2` would successfully switch back to GNOME, and then switching back to VT4 would find a perfectly working terminal.

**Comment by AlanGriffiths** [comment]
I'm not entirely sure of your scenario: The `miral-desktop` includes a `chvt ${oldvt}` that switches you back to VT2 when you Ctrl-Alt-BkSp.

**Comment by AlanGriffiths** [comment]
Oh. This happens when you run from VT4. Confirmed.

**Comment by AlanGriffiths** [comment]
This seems OK now.
