### ISSUE TITLE
mir_unit_tests.LogindConsoleServices.* timeout

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#399]
https://launchpadlibrarian.net/373556377/buildlog_ubuntu-bionic-i386.mir_0.31.2+dev380-g3013b91849-0ubuntu18.04_BUILDING.txt.gz

```
[ RUN ] LogindConsoleServices.take_device_resolves_to_exception_on_error
99% tests passed, 1 tests failed out of 357
The following tests FAILED:
	228 - mir_unit_tests.LogindConsoleServices.* (Timeout)
```

Also failed on 16.04/arm64

**Comment by Saviq** [comment]
Beat you to it:

https://github.com/MirServer/mir/issues/398
