### ISSUE TITLE
[miral-kiosk] support more complex display configurations

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#418]
We're getting asked about more complex display configurations than clone for kiosk scenarios. Either config file or command line options would suffice.

It should be as simple as saying `display-layout: side-by-side` on one end, up to specifying full geometry (resolution, offset, rotation etc...) for multiple displays.

This can probably be split into smaller work chunks.

**Comment by AlanGriffiths** [comment]
Mir has a configuration system that supports config file, environment variables and command line. This is used by miral-shell:

    $ miral-shell --help
    ...
      --display-config arg (=sidebyside)    Display configuration 
                                            [{clone,sidebyside,single}]

That can be used with environment variables:

    MIR_SERVER_DISPLAY_CONFIG=sidebyside miral-server

Or, config file:

    $ cat ~/.config/miral-shell.config 
    ...
    display-config=single
    ...
Or on the command line:

    $ miral-shell --display-config clone

**Comment by AlanGriffiths** [comment]
I propose splitting this as follows and implementing /1/ now but deferring /2/ for later.

1. "pre-baked" layout strategies:

- `--display-layout clone` (default to current mir-kiosk behaviour)
- `--display-layout sidebyside` (as used by miral-shell and mir_demo_server)
- `--display-layout wall=<cols>:<rows>`

2. Bespoke layout:

- `--display-layout manual=<filename>`

Obviously, we need to design a format for the manual layout file.

**Comment by Saviq** [comment]
This is catered for by https://github.com/MirServer/mir/pull/551
