### ISSUE TITLE
[miral-kiosk] ...but as a plug-in platform module (!?)

### ISSUE THREAD

**Issue by Osndok** [MirServer/mir#430]
Dear Mir wizards:

I'm trying to brew a [zany plan](https://forums.ubports.com/topic/1389/reverse-convergence-view-control-your-phone-from-computer-like-vnc-rdp/21) that might require Mir to be... well... "ported to itself".

The overall goal is to have an executable binary **much like miral-kiosk** (in that it presents itself as **an x11 application** and bidirectionally converts x11 to/from mir-traffic)... except that rather than having it's own in-built mir-server, it would **plug into an already-running mir-server as a platform module** (keyboard/mouse/display).

By chance, is the code for miral-kiosk already somehow divided (or dividable) along this server/platform boundary? that this effort might be trivially accomplished?

If you could provide **any sort** of solid technical grounding ("you need to make an X that plugs Y into Z, watch out for W")... that would be much appreciated.

...or even just a overall comment concerning **feasibility**, or the upstream **acceptability** of whatever additional mir-support this might require, would greatly help.

Thanks in advance!

**Comment by AlanGriffiths** [comment]
1. What we've been discussing is nothing like miral-kiosk (in that miral-kiosk is a Wayland server and not a converter between X11 and "mir-traffic").

2. I've already [indicated](https://forums.ubports.com/topic/1389/reverse-convergence-view-control-your-phone-from-computer-like-vnc-rdp/13) that you can do this entirely within the code controlled by UBports.

You need to extend or adapt the "platform" used on the phone to support connection from a new application and present that to Mir as new devices (screen, mouse, keyboard, etc).

As the discussion [developed](https://forums.ubports.com/post/10102) this new application could run on the phone and use a remote X server to implement these devices on a PC (as a "remote desktop" style window).

Neither Mir not Unity8 would know these "devices" are actually a program connected to a PC. So the existing support Unity8 has for plugging in new devices and switching to "desktop mode" will give you a usable experience.

If this can be done without coupling it to the "android" platform used on the phone it would be of interest to the Mir project. Especially if the use of X11 could be easily switched to Wayland.

Please, let's keep the discussion in one place: the UBports forum. (Feel free to C&P this response there if you feel it adds value.)

**Comment by Osndok** [comment]
It sounds like you are saying that the platform is entirely up to the server, and that there is no existing mechanism for which a mir client or executable running alongside the mir server to proffer an additional platform.

As to the miral-kiosk wayland question, I find that rather strange, because I'm **not** using wayland, and mir-kiosk works just fine for me! So I suppose the question then shifts to "what lets wayland apps like mir-kiosk run in xorg"?

Thanks for helping to dispel my ignorance, I'm really not trying to get on your nerves.

**Comment by AlanGriffiths** [comment]
Please forget miral-kiosk, it has nothing to do with what you want to achieve. Lots of programs can run on X including any Mir server.

For what you want, you have to use the Mir server running on the phone: Unity8.

Maybe this will help: https://community.ubuntu.com/t/mir-architecture/

Please, in consideration to anyone trying to understand this discussion, let's keep the it in one place: the UBports forum.

**Comment by Osndok** [comment]
I'm not 100% sure, but I think I've found the road to satisfying my original question...
* mesa-x11
* https://github.com/MirServer/mir/tree/master/src/platforms/mesa/server/x11
* "Mir On X"

My understanding, at the moment, is that something very similar to the above must be loaded alongside the "mir-android-platform".

So unless someone knows otherwise, or is willing to help, I'll take my newfound identifiers as a resolution to this ticket.

**Comment by AlanGriffiths** [comment]
Please, in consideration to anyone trying to understand this discussion, let's keep it in one place: the UBports forum. At least, please write a summary of this discussion there.

The `phablet-control` program does not need to inject a platform into the Unity8 process, it simply connects to the hypothetical, modified "mir-android-platform" using some as-yet-unspecified mechanism (probably a local socket).

The `phablet-control` implementation will have _some_ similarities to the X11 portions of the "mesa-x11" platform, but there will be many significant differences and "something very similar" would be inaccurate.
