### ISSUE TITLE
MIR_SERVER_LIBGL build option no longer works.

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#434]
Setting `-DMIR_SERVER_LIBGL=libGL` rather than the default `libGLESv2` results in a build failure in (at least) the mesa-kms platform.

**Comment by AlanGriffiths** [comment]
@RAOF is this build failing on cosmic?

On bionic it _builds_ & passes tests, and reports passing smoke tests. (The smoke tests only actually show a couple of the clients, and log a lot of `<DEBUG> GLRenderer: GL error: 1281`)

Having built, it fails to composite correctly though:

1. Spinner & cursor appear
2. Wallpaper doesn't appear
3. `qterminal` doesn't appear (but cursor changes suggest it is there, and it exits with Ctrl-D)
4. `mir_demo_client_multiwin` doesn't appear (but it exits with Alt-F4)
5. `glmark2-es2-wayland --fullscreen` appears

**Comment by RAOF** [comment]
Ok, the build *works* on disco, but everything is black with GL errors. I think there's an obvious thing to try - using the relevant GL extension rather than GLES extension.

**Comment by AlanGriffiths** [comment]
@Saviq @mariogrip any reason to keep this build option? (It seems like the wrong thing and nobody has complained for years.)

**Comment by Saviq** [comment]
+1 on dropping it.

**Comment by mariogrip** [comment]
We don't use it, so +1 for dropping :+1:
