### ISSUE TITLE
egdme session doesn't start with lightdm

### ISSUE THREAD

**Issue by pixelr0** [MirServer/mir#443]
using Ubuntu 18.04, mir-devel 0.32.0+dev*, lightdm, [egdme session](https://community.ubuntu.com/t/egmde-desktop-session/) doesn't load, bounce back to lighdm
changed to gdm3 and the session loaded fine

**Comment by pixelr0** [comment]
sorry, maybe it's just because i didn't reboot 
"weird… changed back to lighdm and now the session started. so… the only difference is that now i restarted the pc and the first time when it didn’t load i just logged out. so maybe you actually need to reboot? (i followed how to from this thread, after installing the next instruction is to logout to greeter).
closing the issue for the moment"

you can close this issue since it doesn't look like a mir bug to me

**Comment by AlanGriffiths** [comment]
Agreed
