### ISSUE TITLE
0.32 broke 21 tests on Arch GNU/Linux 

### ISSUE THREAD

**Issue by vanyasem** [MirServer/mir#451]
Broken tests: https://paste.ubuntu.com/p/pTK46mD5W8/
Some logs (will publish full log soon): https://paste.ubuntu.com/p/pTK46mD5W8/

**Comment by AlanGriffiths** [comment]
The common feature of those tests is they make use of Posix signals. Pending more detailed information I would guess that signal handling is broken on your build system.

Try a simple test along the lines of:
```
#include<stdio.h>
#include<signal.h>
#include<unistd.h>

void sig_handler(int signo)
{
  if (signo == SIGINT)
    puts("SUCCESS: received SIGINT");
}

int main()
{
  if (signal(SIGINT, sig_handler) == SIG_ERR)
    puts("ERROR: can't catch SIGINT");
  kill(getpid(), SIGINT);
}
```

**Comment by vanyasem** [comment]
Full log: https://paste.ubuntu.com/p/NFMbsbG6zB/

**Comment by vanyasem** [comment]
The test succeeds
```
● gcc test.c -o test
● ./test
SUCCESS: received SIGINT
```

I will try re-running the build in a clean environment on the CI just to be sure

**Comment by AlanGriffiths** [comment]
Hmm. The details logs suggest a different problem. There come from cross-process synchronization done by creating a pipe() and then polling it. The code raising the error is in tests/mir_test/cross_process_sync.cpp.

This still looks like a problem on your system: the code these tests validate has not changed with 0.32 and passes the tests on various Ubuntu, Fedora and Debian versions.

**Comment by vanyasem** [comment]
Right, the build on my CI server succeeded as well. Oh well I guess it's time to reinstall the system on my PC. Sorry for the inconvenience caused by my stupidity.
