### ISSUE TITLE
logind integration VT switching support is broken

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#459]
Sign into a Mir based shell (e.g. egmde)

* Press Ctrl-Alt-F4
  * Expect: Switches to VT 4
  * Actual: Nothing

* Open a terminal and type: sudo chvt 4
  * Expect: Switches to VT 4
  * Actual: Switches to VT 4

* Press Ctrl-Alt-F2
  * Expect: Switches back to Mir shell
  * Actual: Shell has crashed, need to login again

**Comment by AlanGriffiths** [comment]
This can be replicated using just the Mir demos:

1. Login to a VT
2. Run miral-app

**Comment by RAOF** [comment]
Hah. This is because the existing request-VT-switching code only works when run as root (and is not clearly correct even then).
