### ISSUE TITLE
XDG shell windows loose focus when popup created

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#522]
* Open an XDG shell window (such as Gedit)
* Open a popup (for example, open the right click menu in the editor

__Expected:__
* The window remains focused (this is what happens in weston and rootston)

__Actual:__
* The window looses focus to its popup (you can tell by the title bar dimming, depending on your theme)

__Solution:__
I believe the state is being sent by `xdg_toplevel_send_configure()` which is called in `XdgToplevelV6::handle_resize()`. It is getting the activeness from `WindowWlSurfaceRole::is_active()`. To fix this problem we must dig deeper.

**Comment by AlanGriffiths** [comment]
@wmww I trust you will forgive me if you're actually working on this, but I'm going to steal it from you.
