### ISSUE TITLE
Update-manager crashes while trying to install updates

### ISSUE THREAD

**Issue by pharaone** [MirServer/mir#536]
While trying to install updates update-manager crashed on Egmde (snap) with the error described on the photo.
![img_20180812_152316](https://user-images.githubusercontent.com/17162630/44002498-d0866a86-9e43-11e8-8a54-ed611995901f.jpg)

**Comment by AlanGriffiths** [comment]
That looks like gdk is failing to find the cursor theme. Probably because it expects to be running on Mutter and/or X11.

**Comment by AlanGriffiths** [comment]
I've managed to reproduce. This is connected to the way root access is requested by gnome apps: the PolicyKit desktop integration expected by update-manager simply isn't present.

I don't consider this a Mir issue (or egmde issue), it is a limitation inherent in the scope of project.

Two workarounds:

1. There's no problem if you use: `sudo --preserve-env update-manager`.

2. Stay with the command-line and `sudo apt update && sudo apt upgrade`
