### ISSUE TITLE
Mir on X11 crashes both MATE and LXQt desktops

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#539]
On a MATE 18.04 install, from a terminal on the MATE desktop:

    sudo snap install --classic --edge egmde
    snap run egmde

Expect: Mir-on-X window appears on desktop
Actual: black screen (desktop has died)

Tracing the Mir [egmde]  startup, everything looks normal, and the process is still running. There's just no desktop on which to display the output.

----
[Original description]

Original report: https://github.com/AlanGriffiths/egmde-snap/issues/2

In terminal on the 18.04 MATE desktop:

    sudo add-apt-repository --update ppa:mir-team/release
    sudo apt install mir-demos mir-graphics-drivers-desktop
    sudo apt install qterminal qtwayland5
    miral-app

Expect: Mir-on-X window
Actual: black screen

> the entire screen invariably goes black. I have a cursor, but nothing else. I can’t exit the black screen using “ctrl-alt-bksp” or any other way that I could determine.

This has been seen on a couple of different systems. In contrast, egmde works as a login shell and miral-app works on the Unity desktop.

**Comment by AlanGriffiths** [comment]
@GizmoChicken you might be able get more information by directing the console output from miral-app to a file (and then looking at the file after reboot). Vis:

    miral-app &> miral-app.out
(reboot)
    pastebinit miral-app.out

But, unless we fail to reproduce, we've got enough information for now.

**Comment by AlanGriffiths** [comment]
Simply installing `mate-desktop-environment` isn't enough to reproduce. I have egmde happily running on a MATE desktop. Perhaps this needs to be a clean install.

**Comment by AlanGriffiths** [comment]
It's the MATE desktop that crashes when Mir starts.

Mir starts successfully and selects the X11 platform. The blank screen on VT7 is the remnant of the MATE desktop. Many of the processes (including egmde) are still running. I'm not familiar enough with MATE to know immediately what died.

**Comment by AlanGriffiths** [comment]
Hmm, Xorg is running as root (other desktops I've used Mir on successfully run it as $USER). That implies various permissions will be set up differently.

I think this is a "rabbit hole" I don't have time to spend on just now. Clearly other applications don't crash the desktop, so Mir is doing something unexpected, but desktops shouldn't allow apps to crash them!

**Comment by AlanGriffiths** [comment]
@GizmoChicken it isn't a solution, but from the "black screen" you can get you desktop back by restarting lightdm.

1. Ctrl-Alt-F2 to get a "virtual terminal"
2. `sudo service lightdm restart`

**Comment by GizmoChicken** [comment]
Not urgent, but before I forget:  I can confirm that, on a fresh install of Lubuntu 18.04, attempting to start Mir-on-X from a terminal on the LXQt desktop results in a black screen.

**Comment by AlanGriffiths** [comment]
@GizmoChicken thanks for trying that. I have pictures of Mir on LXQt to prove that used to work: "something changed" is a big clue. There are only so many things that might be (and one obvious suspect I'll try later).

**Comment by AlanGriffiths** [comment]
OK, so (still testing on my MATE 18.04 install):

* from the 18.04 archive
** `miral-app` works as expected
* from ppa:mir-team/release
** `miral-app` kills the desktop on startup
* from ppa:mir-team/dev
** `miral-app` kills the desktop *on exit*
** `miral-app --console-provider none` works as expected
** `miral-app --console-provider logind` kills the desktop *on exit*

That seems like it is the logind console-provider "probing" going wrong. That's an area @RAOF is actively working on and this may be a manifestation one of the issues he already has in his sights.

**Comment by AlanGriffiths** [comment]
Pretty sure now that this and #535 are both the result of our logind console-services messing with an X11session that hasn't claimed the VT from logind.
