### ISSUE TITLE
Scale is not supported when compositing

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#552]
We can configure outputs (and surfaces) with a scale attribute. But this is ignored when compositing.

**Comment by RAOF** [comment]
This should only require changes in `src/renderers/gl/renderer.cpp`; all the required information *should* be available in that file.

If you'd like help starting on this, please feel free to ping us in #mir-server on Freenode!

**Comment by AlanGriffiths** [comment]
Fixed in 1.8.0
