### ISSUE TITLE
miral-shell: if mouse down inside window moves over titlebar, titlebar takes it as a grab and moves window

### ISSUE THREAD

**Issue by gerboland** [MirServer/mir#61]
Steps to repro:
1. Run miral-shell and the fingerpaint demo
2. Press the mouse button down inside the fingerpaint app and wiggle it around to get painting
3. Now with mouse button continually down, move the cursor up over the window titlebar

Expected result
Nothing happens, one can move the cursor back inside the window to continue drawing.

Actual result
The titlebar steals the mouse down, and will reposition the window as the mouse moves.

**Comment by AlanGriffiths** [comment]
Sorted
