### ISSUE TITLE
(Re)plugging of keyboard/mouse dongles is not handled correctly

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#617]
While trying to count pointer devices I've found that the Seat doesn't know what's going on. (I'm still trying to work out if it should!)

I've a dongle that connects keyboard and mouse.

When registered by mie::LibInputDevice::update_device_info() this is processed twice:

1. [2018-09-27 17:49:51.971670] evdev-input: Added /dev/input/event3: USB Receiver
With ID_INPUT_KEY=1 ID_INPUT_KEYBOARD=1
2. [2018-09-27 17:49:51.975383] evdev-input: Added /dev/input/event4: USB Receiver
With ID_INPUT_KEY=1 ID_INPUT_KEYBOARD=1 ID_INPUT_MOUSE=1 ID_INPUT_KEY=1

mi::BasicSeat::add_device() is only called with the /dev/input/event3 and therefore is only aware of the keyboard. (Instead of notifying the mouse we log "[2018-09-27 17:49:51.975490] <DEBUG> evdev-input: Device event4 is part of an already opened device group").

At this stage mouse input is recognised. But...

If I now unplug and replug the dongle then there is no second "added" event and mouse input is no longer recognized.

**Comment by AlanGriffiths** [comment]
Actually, there's more to this.

If I unplug and replug the dongle then there is no second "added" event and mouse input is no longer recognized.

**Comment by AlanGriffiths** [comment]
@RAOF to do some investigation

**Comment by RAOF** [comment]
Specifically, @RAOF will see if using the `libinput` API which handles device hotplug inside `libinput` (but has an awkward blocking API).

**Comment by AlanGriffiths** [comment]
Needs retesting, and check the libinput API used

**Comment by AlanGriffiths** [comment]
Can no longer reproduce (I used the same kit, but it's now on 20.04, not 18.04). There are not many changes in this area to account for any different behaviour. (I don't know what motivated #689, while I don't see how that affects this, it touches some of the code.)
