### ISSUE TITLE
cursor needs to become a snap config option

### ISSUE THREAD

**Issue by ogra1** [MirServer/mir#624]
today it is not possible to set the cursor to null on a user-less appliance image (where you can not ship files like the mir config but only use a gadget.yaml option to pre-set a config option that would otherwise be set via ```snap set mir-kiosk corsor=null``` when being on comandline). 

to hide the cursor, management through the configure hook needs to be added

**Comment by Saviq** [comment]
Done in https://github.com/MirServer/mir-kiosk/pull/13
