### ISSUE TITLE
Internal clients failing with eglstream-kms platform

### ISSUE THREAD

**Issue by gerboland** [MirServer/mir#661]
Am testing with Bionic, using Mir's RC PPA with the NVidia driver 410 from [this ppa
](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa?field.series_filter=bionic).

For servers with GL internal clients I see nothing on the output, and get this error:

```<WARNING> Wayland: Failed to bind Wayland EGL display. Accelerated EGL will be unavailable.: /build/mir-6xp8kA/mir-1.1.0~rc2-g7d4d8dc0bb/src/platforms/eglstream-kms/server/buffer_allocator.cpp(405): Throw in function virtual void mir::graphics::eglstream::BufferAllocator::bind_display(wl_display*, std::shared_ptr<mir::Executor>)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::system_error> >
std::exception::what: Failed to bind Wayland EGL display: EGL_SUCCESS (0x3000)
```

For servers with software internal clients, I also see nothing but get an error:

```<ERROR> mirclient: Caught exception at client library boundary (in mir_connection_create_render_surface): /build/mir-6xp8kA/mir-1.1.0~rc2-g7d4d8dc0bb/src/client/mir_render_surface_api.cpp(107): Throw in function void mir_connection_create_render_surface(MirConnection*, int, int, MirRenderSurfaceCallback, void*)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: Error creating native window
```

I'm testing miral-shell and egmde.

**Comment by RAOF** [comment]
Argh. I've not seen this before (the previous problem with internal clients Gerry was referencing was with them failing on EGL 1.5), *and* it seems like it might not be entirely Mir-code related? I've tested some older eglstreams commits which *definitely* worked on my laptop and which now fail with `EGL_SUCCESS`.

Additionally, Disco's `gdb` has a hard time debugging this; it misses breakpoints or crashes itself(!)

**Comment by RAOF** [comment]
This was an issue with the `egl-wayland` package in the PPA. I've uploaded a new version to all the relevant releases which *should* work and also fix the installation issue, but it requires that Mir be rebuilt against the new packages to pick up the new dependencies.

**Comment by RAOF** [comment]
Ok. So, it's a bit difficult to see on the webcam but the `miral-shell` spinner works with the above commit.

Clients which use the mirclient API are expected to fail; there's a fairly large chunk of work to make those work, the API is deprecated, and Wayland works without any additional effort…

I'm not entirely sure what the status of this bug should be; whether there was something more than the spinner that we expected to work?
