### ISSUE TITLE
release candidate PPA: unable to install eglstreams platform plugin

### ISSUE THREAD

**Issue by gerboland** [MirServer/mir#662]
I've added the mir-team/rc ppa, trying to install eglstreams support gives me:
```
The following packages have unmet dependencies:
 mir-platform-graphics-eglstream-kms16 : Depends: libnvidia-egl-wayland1 but it is not installable
```

I've used the same from the release PPA, which does have this libnvidia-egl-wayland1 package, but it conflicts with libnvidia-gl-410 from the graphics-drivers/ppa (I'm on Bionic)

**Comment by AlanGriffiths** [comment]
@Saviq, @RAOF, putting the _build_ dependencies in ppa:mir-team/release (or /dev) is not the solution we hoped. And we need to resolve the _install_ dependencies in a way that doesn't conflict with ppa:graphics-drivers/ppa.

Thoughts?

**Comment by RAOF** [comment]
This is now fixed, with the exception of disco, which just needs the `libnvidia-egl-wayland1` package that Timo uploaded to be accepted from the NEW queue.
