### ISSUE TITLE
glmark2-wayland crashes on shutdown on eglstreams

### ISSUE THREAD

**Issue by gerboland** [MirServer/mir#663]
WIth Mir, glmark2-wayland (and its es2 cousin) both crash on shutdown. This does not happen with weston-eglstreams.

I couldn't find other clients to reproduce the issue though.

**Comment by RAOF** [comment]
I think this is actually a bug in the NVIDIA driver, or maybe glmark2-wayland, or maybe both.

Instrumenting `libwayland` with AddressSanitizer shows that libnvidia-egl-wayland is dispatching a wayland event after glmark2-wayland has called `wl_display_disconnect`, which has freed a bunch of state. It looks like it's processing the wl_buffer.destroy() event that Mir doesn't explicitly send.

It appears to all be in the same thread as glmark2-wayland, so maybe it *is* a glmark2-walyand bug.

**Comment by RAOF** [comment]
Should check on more recent nvidia drivers.

**Comment by RAOF** [comment]
I *think* this no longer happens? I shall see if this still applies.

**Comment by RAOF** [comment]
Verified fixed on my Ubuntu 20.04 desktop, with NVIDIA-440
