### ISSUE TITLE
mir_stress doesn't stress Mir

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#677]
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 7932 alan      20   0  629000   6720   5644 S 335.1  0.1   6:36.92 mir_stress
 7909 alan      20   0  628832  92208  61676 S  17.2  1.1   0:24.83 miral-shell
```

**Comment by AlanGriffiths** [comment]
mir_stress is only testing a legacy API and needs reworking anyway.

**Comment by RAOF** [comment]
This will go away in the near future with the dropping of mirclient.

If we work out what we want to prove with a stress test, we can write a new one with the wayland API.
