### ISSUE TITLE
Mir-on-Mir does not work (without Mir EGL)

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#73]
This is a special case of a Mir client that fails when Mir EGL is unavailable. I.e. when using anything other than the Ubuntu 16.04 Mesa driver (or the UBport's android driver).

We're never going to support such clients on other stacks.

What is needed is to rework Mir-on-Mir as a Wayland client. (Probably using the https://github.com/MirServer/mir-platform-wayland work.)

**Comment by RAOF** [comment]
With the merging of the Wayland platform it is now once again possible to run a Mir server on a Mir server.
