### ISSUE TITLE
Mutating mc::MultiMonitorArbiter code does not fail tests 

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#744]
While looking at something unrelated, @wmww and I found:
```
    if (current_buffer_users.find(id) != current_buffer_users.end() || !current_buffer)
    {
        if (schedule->num_scheduled())
            current_buffer = schedule->next_buffer();
        current_buffer_users.clear();
    }
```
This seemed odd; we clear the `current_buffer_users` even if we don't change the current buffer.

I could not off the top of my head remember why we did that, so in the spirit of experimentation, changed the code to
```
    if (current_buffer_users.find(id) != current_buffer_users.end() || !current_buffer)
    {
        if (schedule->num_scheduled())
        {
            current_buffer = schedule->next_buffer();
            current_buffer_users.clear();
        }
    }
```
To only clear `current_buffer_users` if we actually changed the buffer and then ran the tests to see what would break.

Unfortunately, none of the tests break with this change.

We should:
 * Determine which of the two presented codepaths is correct, and then
 * Write a test which distinguishes between them.

**Comment by wmww** [comment]
The code is currently in recommended state, and changing it back breaks `mir_unit_tests.MultiMonitorArbiter.second_compositor_advances_schedule_after_both_aquire_first_buffer`. It appears this was fixed by #862
