### ISSUE TITLE
FTBFS: missing symbol

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#776]
As advertised in [the dev PPA](https://launchpad.net/~mir-team/+archive/ubuntu/dev/+packages):

```
+ _ZN5miral17WaylandExtensions33add_extension_disabled_by_defaultERKNS0_7BuilderE@MIRAL_2.5 2.5.0
```

**Comment by AlanGriffiths** [comment]
Fixed: https://github.com/MirServer/mir/commit/0bae64c646e966729025a3783b4f845aa3abdabb
