### ISSUE TITLE
Include a CI musl build on Ubuntu

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#777]
This should make it easier to maintain the port to Alpine.

> Sure, a musl on Ubuntu CI would suffice.
> It's just, that it's "easy" for a change to break musl support (like a missing include) and it took quite some time fixing all the little things that we came across while getting Mir running on Alpine.
https://github.com/MirServer/mir/issues/503#issuecomment-477647201

**Comment by RAOF** [comment]
There's an Alpine lxd image available; maybe we should just build on Alpine?

**Comment by RAOF** [comment]
There's an Alpine lxd image available; maybe we should just build on Alpine?

**Comment by z3ntu** [comment]
Related: #990 

My PR for adding Alpine Linux CI to wlcs was merged (https://github.com/MirServer/wlcs/commit/97a356ee9aead1424ea264c00df2392a2bb2c402) but the CI setup for Mir looks a bit more complicated even though it seems to be the same system. If somebody familiar with the CI could do the initial setup (get the commands in `spread/build/alpine/task.yaml` running inside an Alpine image) I can do the rest.

**Comment by AlanGriffiths** [comment]
@Saviq is this feasible now?

**Comment by Saviq** [comment]
> @Saviq is this feasible now?

We'll see: #1949

**Comment by Saviq** [comment]
https://github.com/MirServer/mir/blob/08112d7a4edef44582ab71684dafccd695c50bd7/.github/workflows/spread.yml#L36-L37
