### ISSUE TITLE
Mir tests fail on Alpine Linux

### ISSUE THREAD

**Issue by z3ntu** [MirServer/mir#778]
An extension of issue #503

In mir_unit_tests the `Dummy/ClientPlatformTest.platform_name/0` test fails at an `dladdr` call - maybe this is the "fault" of musl

Quite many other tests also fail (mostly segfault)

**Comment by RAOF** [comment]
We look forward to the Alpine CI build :grin:

**Comment by AlanGriffiths** [comment]
@z3ntu is this still a problem?

**Comment by z3ntu** [comment]
Yes, a bunch of tests still segfault. At least one is also hanging. If you want the full test log I can prepare one.

**Comment by Saviq** [comment]
@z3ntu I pushed a stub CI on `alpine-3.13` and `alpine-edge` (which seems to be 3.12 for some reason), based on LXD images from https://images.linuxcontainers.org: #1949 

You can try locally roughly following this:

https://github.com/MirServer/mir/blob/8c7bdb39cb4b4d19360cc857267bd7f566e420a7/.github/workflows/spread.yml#L111-L114

And then running `spread lxd:alpine-3.13:spread/build/alpine:amd64`. You can also just put up a PR to see how GitHub fares.

**Comment by z3ntu** [comment]
I don't have easy access to snap but I can work with what the CI builds. I'll likely copy #1949 and try to get it working there.

**Comment by AlanGriffiths** [comment]
Closing as we now (#1957) have a successful Alpine build in CI
