### ISSUE TITLE
Segmentation fault of miral-shell with nouveau 1.3.1 [nVidia Riva/TNT/GeForce/Quadro/Tesla/Tegra K1+]

### ISSUE THREAD

**Issue by ilyaigpetrov** [MirServer/mir#798]
Before the test I run `rm /run/user/1000/wayland*` and `rm /run/user/1000/miral*`, then I exit openbox, get into lightdm, press Ctrl+Alt+Backspace, it blinks and gets me back to lightdm, I login into openbox again and start a gnome-terminal.
Then I run `miral-shell` and it usually fails with a segmentation fault.
I attach a log, a crash dump and packages versions:
1) [miral-shell-1-wmtrace.log](https://github.com/MirServer/mir/files/3095744/miral-shell-1-wmtrace.log).
2) [verions.txt](https://github.com/MirServer/mir/files/3095745/verions.txt).
3) [crash-dump.txt](https://github.com/MirServer/mir/files/3095749/crash-dump.txt).

**Comment by ilyaigpetrov** [comment]
Here is a result of crashing from `valgrind -v miral-app &> miral-app-valgrind.log`. The command was executed after Xorg restart (Ctrl+Alt+Backspace) and `rm /run/user/1000/wayland*` (two files were deleted left after previous launch of some miral commands I guess).
[miral-app-_usr_bin_miral-shell.1000.crash.txt](https://github.com/MirServer/mir/files/3097286/miral-app-_usr_bin_miral-shell.1000.crash.txt)
[miral-app-valgrind.log](https://github.com/MirServer/mir/files/3097287/miral-app-valgrind.log)

**Comment by AlanGriffiths** [comment]
@ilyaigpetrov most of the team have public holidays around the Easter weekend: we might not get to this until next week.

**Comment by AlanGriffiths** [comment]
@ilyaigpetrov I don't see anything obvious that would explain the Mir crash and I've confirmed that Mir is working on 19.04 desktop (I know you reported this on server, but I would need to set that up).

However, as it sounds as though openbox is also crashing (i.e. "it blinks and gets me back to lightdm"), I suspect that there may be a problem external to Mir.

How does Mir behave if, instead of logging into openbox, you log into a virtual terminal (e.g. Ctrl-Alt-F4) and run `miral-shell` from the command line?

**Comment by ilyaigpetrov** [comment]
Thank you for your reply, @AlanGriffiths. Under vt4 miral-shell crashes too, two logs are below:
[miral-shell.log](https://github.com/MirServer/mir/files/3107068/miral-shell.log)
[miral-shell-wmtrace.log](https://github.com/MirServer/mir/files/3107069/miral-shell-wmtrace.log)

**Comment by ilyaigpetrov** [comment]
UEFI is turned off and MBR is used if it's important.

**Comment by AlanGriffiths** [comment]
Ah, this seems somewhat unusual:
```plain
[2019-04-23 05:29:23.477403] mesa-kms: EGL platform does not support EGL_KHR_platform_gbm extension
...
[2019-04-23 05:29:25.086197] <WARNING> mesa-kms: Unable to determine the current display mode.
[2019-04-23 05:29:25.086307] <WARNING> mesa-kms: Unable to determine the current display mode.
[2019-04-23 05:29:25.086352] <WARNING> mesa-kms: Unable to determine the current display mode.
[2019-04-23 05:29:25.089129] mesa-kms: DRM device details:
[2019-04-23 05:29:25.089219] mesa-kms: /dev/dri/card0: using driver nouveau [nVidia Riva/TNT/GeForce/Quadro/Tesla/Tegra K1+] (version: 1.3.1 driver date: 20120801)
...
[2019-04-23 05:29:25.194200] <WARNING> mesa-kms: drmModeCrtcSetGamma failed: Invalid argument
[2019-04-23 05:29:25.285612] mesa-kms: Detected single-GPU DisplayBuffer. Rendering will be sent directly to output
```
I suspect your graphics card/drivers does not support enough EGL for Mir to work. (OTOH that shouldn't be causing a crash.)

If I'm right, you may find that `miral-kiosk` can start successfully (although connecting an EGL client to it will fail to work.)

**Comment by ilyaigpetrov** [comment]
On vt4 `miral-kiosk` starts successfully but I haven't found any way to launch qterminal on it from another terminal. Tried this:
```sh-session
$ miral-run qterminal
$ Failed to create wl_display (Connection refused)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```
Then I revealed ``miral-kiosk --startup-apps `which qterminal` `` and it worked without crashes both in vt4 and inside openbox/xorg.

Which package may I use as a test for EGL client support on Mir or just to test EGL support on my system required for Mir?

**Comment by AlanGriffiths** [comment]
I think you're already aware of it, but there's a script `miral-app` to simplify configuring Mir sessions:
```bash
miral-app -kiosk
```
Will start `miral-kiosk` and attempt to run `qterminal`. (That will likely work in view of your revelation.) It also exits the server when the "launcher" exits.

Your success with `miral-kiosk` and `qterminal` suggests that there's more to the problem than I assumed. Could you try another experiment?
```bash
miral-app --window-manager tiling
```
(The point of this is that this configuration of `miral-shell` doesn't try to paint "wallpaper", which is one of the differences between `miral-kiosk` and the default `miral-shell`.)

**Comment by ilyaigpetrov** [comment]
Here you are, `miral-app --window-manager tiling` on vt4, I see the logo but then it quits or freezes while I switch virtual terminals:
[miral-app-tiling-crashed.log](https://github.com/MirServer/mir/files/3107390/miral-app-tiling-crashed.log)
[valgring-miral-app-tiling-2.log](https://github.com/MirServer/mir/files/3107391/valgring-miral-app-tiling-2.log)

**Comment by AlanGriffiths** [comment]
@ilyaigpetrov thanks for that. It makes the issue a lot clearer.

I believe the significant difference between `miral-shell --window-manager tiling` (which fails) and `miral-kiosk` (which works) is the startup "splash". The failing startup animation uses EGL, the successful one uses sw rendering.

A plausible explanation lies in the animation code failing to handle an error status correctly.

Unfortunately, I don't see this issue on any of the kit I have to hand, which could make resolving the specific cause of crash problematic.

**Comment by AlanGriffiths** [comment]
@ilyaigpetrov I note that this is an Nvidia card - does it work with `nvidia-driver-418` instead of Mesa? (If so, you could try installing `mir-graphics-drivers-nvidia`.)

**Comment by ilyaigpetrov** [comment]
I doubt my old laptop supports version 418, `ubuntu-drivers list` returns `nvidia-340`. I installed it together with `mir-graphics-drivers-nvidia` but seems it was enough. I attach logs with exception `Failed to find platform for current system`:
[nvidia-driver-miral-app-tiling-from-vt4.log](https://github.com/MirServer/mir/files/3107886/nvidia-driver-miral-app-tiling-from-vt4.log)
[nvidia-driver-miral-shell-tiling-from-xorg.log](https://github.com/MirServer/mir/files/3107887/nvidia-driver-miral-shell-tiling-from-xorg.log)

**Comment by AlanGriffiths** [comment]
Yes, Mir doesn't work with nvidia-340.

For the moment, you'll have to use mesa and a Mir server that doesn't use the EGL "spinner". (Anything but `miral-shell`: `miral-kiosk`, `mir_demo_server` or `egmde`.)

**Comment by AlanGriffiths** [comment]
nvidia-340 is unsupportable - can't fix
