### ISSUE TITLE
Shells inconsistantly crash when output width is much larget than height

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#799]
`miral-shell --x11-output 800x100` usually crashes. Less extreme aspect ratios crash less often, and by the time it gets to 2:1 they go away. There does not seem to be a problem with tall skinny outputs. `mir_demo_server` does the same thing.

**Comment by AlanGriffiths** [comment]
Is this only on shells with text on wallpaper? If `--window-manager tiling` and `miral-kiosk` are unaffected then check the wallpaper text sizing logic.

**Comment by wmww** [comment]
Yes, both are unaffected and gdb says the crash happens at `/home/wmww/code/mir/examples/example-server-lib/decoration_provider.cpp:209`. I'll take care of this next week
