### ISSUE TITLE
General improvements to generated wayland code

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#801]
Here is a list of things I'd like to improve with our generated code. None of this is urgent, and is mostly just my personal todo list
* ☑ ~Function to handle errors~ (#739)
* ☑ ~Split globals and instances of the toplevel types~ (#819)
* ☑ ~Automatcially use the latest protocol version~ (~#832~) (#845)
* ☐ Handle version errors
  * ~At least catch if we send an event not support by the in-use version~
  * ~Not sure if we should print an error, disconnect the client or just silently ignore it (and remove the need to check)~
  * We have agreed the best option is to silently drop events sent to objects of an incompatible version
    * Manual checks will still be possible if needed
* ☑ ~Common Wayland object base class~ (#828)
  * ☒ ~Standardize a way to run code on the wayland thread only if the object is still around~ *Better to do this when entering the Wayland frontend, and just already be in the Wayland thread here*
* ☑ ~Better resource creation path~ (#807)
* ☐ `destroy_thunk()` should automatically destroy the wayland object
  * Currently we must remember to call `destroy_wayland_object()`, which is error prone
  * If it should always be destroyed, just do it after `destroy()`
  * If there are cases when it shouldn't, `destroy()` should return a bool of if to do it (thus making not destroying it an explicit decision)
* ☐ Make destruction process more obvious (right now it can be as convoluted as `.destroy` request -> `destroy_thunk()` -> `destroy()` -> `destory_wayland_object()` -> `wl_resource_destroy()` -> [libwayland calls the function set in wl_resource_set_implementation] -> `resource_destroyed_thunk()` -> `delete Type`. There are reasons for this complexity, but there might be some improvements possible
* ☒ ~Better namespacing? `wayland::xdg::Shell`?~ *Not really needed and a lot of code churn*
* ☐ Make Wayland object implementations testable
  * ☐ Wayland event interface
  * ☐ Wayland request interface
  * ☐ Generated mock objects
* ☐ Change generated event methods to take typesafe Wayland types
* ☐ Generate docs from Wayland protocol comments

**Comment by AlanGriffiths** [comment]
As we'll be packaging the code generator as part of 1.2.0 shortly we should discuss "not urgent" as changes could impact downstream projects. @RAOF thoughts?

**Comment by RAOF** [comment]
Some of these seem like sensible things; particularly the things around lifecycle could be much nicer.

> Not sure if we should print an error, disconnect the client or just silently ignore it (and remove the need to check)
We shouldn't silently ignore it, as now the client and server have a different view of state. Since this is a compositor error, probably throwing an exception would be the winner.

Some of these are more important than others; I think fixing the lifecycle mess would be a sufficiently high priority to at least see if it'll break code across the migration.

**Comment by wmww** [comment]
After some discussion about these issues we've come to the following conclusions:

## Threading and lifecycle
* We like approximately the architecture we have
  * A user implemented Wayland object, a generated Wayland and the `wl_resource` it wraps are all created and destroyed together, as controlled by libwayland
  * Execution moves to the Wayland thread as it enters the Wayland frontend (so not when sending events)
* We do need to make some changes
  * Replace the pervasive `std::shared_ptr<bool> destroyed` and `spawn(run_unless_destroyed(...))` pattern with our recently improved observer-with-executor system
  * It handles moving execution to the Wayland thread
  * It also handles not calling into objects after they are destroyed (`->unregister_interest()` needs to be called in the destructor)

## Generated code
* Generated code should silently drop events that are incompatible with the current resource version
  * Almost always the desired behavior
  * If it is not the desired behavior, a manual check will be possible.
* Wayland object classes should be testable.
  * Manually implemented Wayland objects should **NOT** inherit from a generated Wayland object class (as it currently does)
  * Instead they should implement a generated [interface](https://mir-server.io/doc/cppguide/#Interfaces) for request methods
  * On construction, they should receive a pointer (which they store as const) to an interface for sending events
  * A real and a mock implementation of all Wayland objects can then be generated, which implement the event interface and call into the request one

**Comment by wmww** [comment]
The "Threading and lifecycle" part above has mostly been resolved by the introduction of `wayland::Weak`. It still might be nice to port the surface observers to the new observer system (so all messages will arrive on the Wayland thread), that is non-urgent.

**Comment by wmww** [comment]
The following improvements to generated Wayland code have not been made and should still be considered when we have the available cycles:
- Generated code should silently drop events that are incompatible with the current resource version
- Each object should have a requests interface and an events interface (instead of a base class) so Wayland objects can be mocked and tested
- Wayland objects should be automatically destroyed by the `.destroy` request
- Generated methods should take typesafe Wayland types
- The generator should generate doc comments from Wayland protocol comments

**Comment by Saviq** [comment]
Sounds like another review is in order. For anything remaining, should we file separate issues for simpler tracking?

**Comment by wmww** [comment]
Split into new issues.
