### ISSUE TITLE
Don't give keyboard focus to non-grabbing popups

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#827]
As I mentioned in #825, it appears popups should not be getting keyboard focus unless they are the current grab.

`xdg_popup.grab`:
> During a popup grab...the top most grabbing popup will always have keyboard focus. [implying the toplevel should, if none are grabbing]

Also `keyboard.leave` should be sent before `keyboard.enter`.

**Comment by AlanGriffiths** [comment]
Fixed by #1646
