### ISSUE TITLE
Mir doesn't use libwayland-server's `wl_*_interface` definition

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#829]
The binding generator appears to provide Mir its own definition of `wl_surface_interface` (and, indeed, all the interface definitions), but this is hidden (as it's not explicitly exported in `symbols.map`).

I'm not sure the extent to which this is a problem, but *I've* written code in the past which checks for reference equality against a Wayland interface symbol; this would fail with current Mir.

**Comment by wmww** [comment]
Indeed Mir provides it's own implementation of all the generated things, as we don't use `wayland-scanner` output at all.

> *I've* written code in the past which checks for reference equality

I'm not sure precisely what you're trying to accomplish. Are you checking if a `wl_resource` is of a specific type? If so, we have `wayland::WlType::is_instance(resource)` for that. If it's something else, I'm sure I can add it easily.

**Comment by AlanGriffiths** [comment]
The only mentions of `wl_surface_interface` I see are in `mir/tests/miral/org_kde_kwin_server_decoration.c`. And these, AFAICS, reference `libwayland-server`'s definition.

Mir does provide `wl_surface_interface_data`, but that is exported.

@RAOF could you clarify?

**Comment by RAOF** [comment]
> Indeed Mir provides it's own implementation of all the generated things, as we don't use `wayland-scanner` output at all.

Is there any particular reason to duplicate the existing definitions in `libwayland-server`? This doesn't require using the `wayland-scanner` output, just what's in the existing `libwayland-server.so`.

> 
> > _I've_ written code in the past which checks for reference equality
> 
> I'm not sure precisely what you're trying to accomplish. Are you checking if a `wl_resource` is of a specific type? If so, we have `wayland::WlType::is_instance(resource)` for that. If it's something else, I'm sure I can add it easily.

Yes. The (rather minor) problem is that there's existing Wayland server code that does reference-equality testing on the interface, which could be copy-and-pasted and unexpectedly break.

There's also the `wl_resource_instance_of()` call, which has a fast-path on reference-equality.

None of these are particularly serious issues, but I didn't think that there was a particularly good reason *to* define our own duplicates of these symbols.

**Comment by wmww** [comment]
> This doesn't require using the wayland-scanner output, just what's in the existing libwayland-server.so

Is libwayland-server built with `wl_surface_interface` included? Is it built with all of the interfaces for wayland.xml types? I suppose we could special-case interfaces from standard Wayland types, then generate the ones from other protocols.

**Comment by RAOF** [comment]
> > This doesn't require using the wayland-scanner output, just what's in the existing libwayland-server.so
> 
> Is libwayland-server built with `wl_surface_interface` included? Is it built with all of the interfaces for wayland.xml types? I suppose we could special-case interfaces from standard Wayland types, then generate the ones from other protocols.

Yes; libwayland-server contains definitions for all the standard interface types.

**Comment by RAOF** [comment]
I'll give this a whirl; it shouldn't actually be much effort.

**Comment by RAOF** [comment]
As discovered in the PR, using the `libwayland-server` symbols means that we're limited to the versions supported by whatever version of `libwayland` the environment has. That's a significant enough limitation that we should just keep doing what we're doing.
