### ISSUE TITLE
Short “Ubuntu”-colored flash when mir-kiosk snap starts

### ISSUE THREAD

**Issue by tobias-grasse** [MirServer/mir#830]
First of all: Thank you for your work on this software! I use the mir-kiosk snap with an Ubuntu Core system on a Raspberry Pi 3. 

When the mir-kiosk snap starts up, I see a short colored flash tinted in “Ubuntu” orange.
1) Can I disable this in a way that does not involve forking the snap?
2) If that is not possible, can someone guide me where to start with a MR to make this configurable?

**Comment by tobias-grasse** [comment]
Now I'm the one to reply late 😊 Thanks for clearing this up and outlining the required work. It's currently not a high priority, but once I find the time to get a bit comfortable with C++ I'll give it a try.

**Comment by knitzsche** [comment]
Hi: We have a customer project that is making a device that normal folks in their houses turn on, and the orange flash is not very clean in their opinion. Can you add a way to disable the orange flash via snap config? Thanks.

**Comment by knitzsche** [comment]
I submitted a PR for this: https://github.com/MirServer/mir/pull/1699

**Comment by AlanGriffiths** [comment]
Closed by #1699
