### ISSUE TITLE
Maximized windows cover entire display area when outputs are hotplugged

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#853]
Whenever outputs are connected, disconnected or changed, all maximized windows are moved to cover the entire display area. Unmaximizing and remaximizing puts the window back on a specific output. This behavior is obvious from the implementation of `miral::BasicWindowManager::update_windows_for_outputs()`

**Comment by AlanGriffiths** [comment]
Yup, there's obviously confusion in the code about what `mir_window_state_maximized` etc. mean. 

`BasicWindowManager::update_windows_for_outputs()` and `BasicWindowManager::place_and_size_for_state()` treat them as relative to the aggregate display area.

`BasicWindowManager::place_new_surface()` treats them as relative to the active output's area.

Either behaviour _could_ be argued for, but not a mix like this.
