### ISSUE TITLE
Parentless window placed off screen

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#899]
If a window doesn't have a parent, the window is placed near the first existing window of the same application. This sounds like a good idea at first, except that in the case of mate-panel this results in the properties window being placed mostly off-screen and inaccessible (because the panel is close to the edge of the screen).

**Comment by AlanGriffiths** [comment]
That default behaviour comes from one of the Unity8 design docs. As you say, if anyone cares for it, it is easily be reproduced in the Unity8 window management policy.
