### ISSUE TITLE
Signed .tar.xz release tarballs missing for 1.2.0, 1.3.0

### ISSUE THREAD

**Issue by ollieparanoid** [MirServer/mir#912]
The signed .tar.xz files are missing for the most recent two releases:

https://github.com/MirServer/mir/releases/

**Comment by AlanGriffiths** [comment]
Until wlcs was split out as a separate project the tarballs generated by github were "wrong" (as they didn't include the wlcs submodule). The tarballs we generated outside of github were signed.

Since wlcs was split out the github tarballs are OK to use.

**Comment by ollieparanoid** [comment]
Thanks for explaining!
