### ISSUE TITLE
Mir-on-X: Held key generates series of press/release Wayland events

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#917]
![ 3.6498 wl_keyboard@3.1 key(serial=25, time=54421816, key=14, state=0:released) ↲
 3.6582 wl_keyboard@3.1 key(serial=26, time=54421816, key=14, state=1:pressed) ↲
 3.6931 wl_keyboard@3.1 key(serial=27, time=54421856, key=14, state=0:released) ↲
 3.7030 wl_keyboard@3.1 key(serial=28, time=54421856, key=14, state=1:pressed) ↲
 3.7317 wl_keyboard@3.1 key(serial=29, time=54421896, key=14, state=0:released) ↲
 3.7404 wl_keyboard@3.1 key(serial=30, time=54421896, key=14, state=1:pressed) ↲
 3.7668 wl_keyboard@3.1 key(serial=31, time=54421936, key=14, state=0:released) ↲
 3.7715 wl_keyboard@3.1 key(serial=32, time=54421936, key=14, state=1:pressed) ↲
 3.8116 wl_keyboard@3.1 key(serial=33, time=54421977, key=14, state=0:released) ↲
 3.8211 wl_keyboard@3.1 key(serial=34, time=54421977, key=14, state=1:pressed) ↲
 3.8522 wl_keyboard@3.1 key(serial=35, time=54422017, key=14, state=0:released) ↲
 3.8636 wl_keyboard@3.1 key(serial=36, time=54422017, key=14, state=1:pressed) ↲
 3.8883 wl_keyboard@3.1 key(serial=37, time=54422057, key=14, state=0:released) ↲
 3.8934 wl_keyboard@3.1 key(serial=38, time=54422057, key=14, state=1:pressed) ↲
 3.9264 wl_keyboard@3.1 key(serial=39, time=54422097, key=14, state=0:released) ↲
 3.9295 wl_keyboard@3.1 key(serial=40, time=54422097, key=14, state=1:pressed) ↲
 3.9675 wl_keyboard@3.1 key(serial=41, time=54422138, key=14, state=0:released) ↲
 3.9717 wl_keyboard@3.1 key(serial=42, time=54422138, key=14, state=1:pressed) ↲
 4.0095 wl_keyboard@3.1 key(serial=43, time=54422178, key=14, state=0:released) ↲
 4.0146 wl_keyboard@3.1 key(serial=44, time=54422178, key=14, state=1:pressed) ↲
 4.0490 wl_keyboard@3.1 key(serial=45, time=54422218, key=14, state=0:released) ↲
 4.0540 wl_keyboard@3.1 key(serial=46, time=54422218, key=14, state=1:pressed) ↲
 4.0885 wl_keyboard@3.1 key(serial=47, time=54422258, key=14, state=0:released) ↲
 4.0968 wl_keyboard@3.1 key(serial=48, time=54422258, key=14, state=1:pressed) ↲
 4.1368 wl_keyboard@3.1 key(serial=49, time=54422298, key=14, state=0:released) ↲
 4.1467 wl_keyboard@3.1 key(serial=50, time=54422298, key=14, state=1:pressed) ↲
 4.1691 wl_keyboard@3.1 key(serial=51, time=54422338, key=14, state=0:released) ↲
 4.1741 wl_keyboard@3.1 key(serial=52, time=54422338, key=14, state=1:pressed) ↲
 4.2081 wl_keyboard@3.1 key(serial=53, time=54422378, key=14, state=0:released) ↲
 4.2118 wl_keyboard@3.1 key(serial=54, time=54422378, key=14, state=1:pressed) ↲
 4.2485 wl_keyboard@3.1 key(serial=55, time=54422418, key=14, state=0:released) ↲
 4.2536 wl_keyboard@3.1 key(serial=56, time=54422418, key=14, state=1:pressed) ↲
 4.2910 wl_keyboard@3.1 key(serial=57, time=54422458, key=14, state=0:released) ↲
 4.2975 wl_keyboard@3.1 key(serial=58, time=54422458, key=14, state=1:pressed) ↲
 4.3307 wl_keyboard@3.1 key(serial=59, time=54422499, key=14, state=0:released) ↲
 4.3369 wl_keyboard@3.1 key(serial=60, time=54422499, key=14, state=1:pressed) ↲
 4.3694 wl_keyboard@3.1 key(serial=61, time=54422539, key=14, state=0:released) ↲
 4.3762 wl_keyboard@3.1 key(serial=62, time=54422539, key=14, state=1:pressed) ↲
 4.4148 wl_keyboard@3.1 key(serial=63, time=54422579, key=14, state=0:released) ↲
 4.4213 wl_keyboard@3.1 key(serial=64, time=54422579, key=14, state=1:pressed) ↲
 4.4503 wl_keyboard@3.1 key(serial=65, time=54422619, key=14, state=0:released) ↲
 4.4566 wl_keyboard@3.1 key(serial=66, time=54422619, key=14, state=1:pressed) ↲
 4.4896 wl_keyboard@3.1 key(serial=67, time=54422659, key=14, state=0:released) ↲
 4.4946 wl_keyboard@3.1 key(serial=68, time=54422659, key=14, state=1:pressed) ↲
 4.5283 wl_keyboard@3.1 key(serial=69, time=54422699, key=14, state=0:released) ↲
 4.5318 wl_keyboard@3.1 key(serial=70, time=54422699, key=14, state=1:pressed) ↲
 4.5736 wl_keyboard@3.1 key(serial=71, time=54422739, key=14, state=0:released) ↲
 4.5825 wl_keyboard@3.1 key(serial=72, time=54422739, key=14, state=1:pressed) ↲
 4.6078 wl_keyboard@3.1 key(serial=73, time=54422779, key=14, state=0:released) ↲
 4.6108 wl_keyboard@3.1 key(serial=74, time=54422779, key=14, state=1:pressed) ↲
 4.6539 wl_keyboard@3.1 key(serial=75, time=54422819, key=14, state=0:released) ↲
 4.6638 wl_keyboard@3.1 key(serial=76, time=54422819, key=14, state=1:pressed) ↲
 4.6965 wl_keyboard@3.1 key(serial=77, time=54422860, key=14, state=0:released) ↲
 4.7069 wl_keyboard@3.1 key(serial=78, time=54422860, key=14, state=1:pressed) ↲
](https://user-images.githubusercontent.com/9331264/61082407-f3ebd480-a418-11e9-9c6f-5002dbbf768f.png)

That was all from a single press-and-hold of backspace. Appears to only effect Mir-on-X

**Comment by RAOF** [comment]
This would seem likely to be Mir-on-X getting key-repeat events from X11?
