### ISSUE TITLE
renderer::gl::TextureSource should be deprecated

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#950]
`mir::graphics::gl::Texture` provides the essentially same functionality as `mir::renderer::gl::TextureSource` but with an interface that the EGLStream platform can provide (and that would be easier for `WlShmBuffer`, too).

We should port existing users off `mir::renderer::gl::TextureSource` and deprecate it. Removing it will need to be coordinated with the UBports team as this will affect their Android graphics platform.

**Comment by RAOF** [comment]
Yes, but let's work out what the final-state platform API should be first.

**Comment by AlanGriffiths** [comment]
Possible now?

**Comment by AlanGriffiths** [comment]
> Possible now?

Almost. The remaining use is `GBMBuffer` in `gbm-kms` (via `BindResolverTexTarget`), that looks replaceable but isn't trivial.

**Comment by AlanGriffiths** [comment]
This is gone (#2045)
