### ISSUE TITLE
Build configuration doesn't fail if it can't find wlcs binary

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#973]
I mis-built wlcs so that `pkg-config --variable test_runner wlcs` returned a non-existent path; Mir detected WLCS support and proceeded to build, but silently failed to run any WLCS tests.

**Comment by AlanGriffiths** [comment]
Is this fixed by #1944

**Comment by AlanGriffiths** [comment]
> Is this fixed by #1944

Yes
