### ISSUE TITLE
GTK popups on subsurfaces not placed correctly

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#975]
Also happens in Sway, not yet tested in Gnome Shell.

To reproduce:
* Open Nautilus
* Click the view options drop down in the upper right (this is implemented as a subsurface)
* Hover over the zoom in and zoom out buttons
* Observe the tooltip (implemented as a a popup) is placed far to the left

Based on the wayland-debug output, GTK is sending the correct anchor rect, but a weird offset. May be a GTK bug. Will investigate.

**Comment by wmww** [comment]
Doesn't appear to effect GTK on Ubuntu 18.04

**Comment by Pajn** [comment]
I saw in IRC that you wanted reproductions on 19.10. I can reproduce it with Mir 1.4.0 and egmde. I have not tested against master, do you need that as well?

**Comment by AlanGriffiths** [comment]
Yes, also happens with GNOME Wayland on 19.10.

Possibly not relevant, but I've also seen intermittent weird placement of popups with GNOME using X. (But the above reproducer doesn't show this problem.)

**Comment by wmww** [comment]
Looks like it doesn't happen in X, but does in all Wayland sessions tested (Mir, Sway, Gnome). This would strongly indicate Mir is fine and this is a GTK bug (as I suspected after reading the protocol messages). I'll report to GTK if I can reproduce with GTK master.
