### ISSUE TITLE
Missing systemtap dependency check

### ISSUE THREAD

**Issue by dos1** [MirServer/mir#979]
The build system doesn't check whether systemtap is installed, leading to a build-time error on missing `sys/sdt.h` header.

**Comment by AlanGriffiths** [comment]
If build dependencies are not installed, it is unsurprising that there are build errors.

In this case, systemtap is listed in the build dependencies (debian/control):
```
               systemtap-sdt-dev,
```

(It is also mentioned in spread/build/fedora/task.yaml.)

What are you trying to achieve? A better diagnostic message? Or to be able to build without the functionality that uses systemtap?

**Comment by dos1** [comment]
Just a message - when there's missing dependency, I'd generally expect CMake generation to already catch that and fail early.

**Comment by z3ntu** [comment]
This also happens on Alpine Linux where systemtap is not even packaged. Shouldn't lttng define `LTTNG_UST_HAVE_SDT_INTEGRATION` itself when it has systemtap in `/usr/include/lttng/ust-config.h`?

**Comment by AlanGriffiths** [comment]
Fixed by #1957
