### ISSUE TITLE
Mir does not render layer_shell clients on the correct monitor

### ISSUE THREAD

**Issue by Pajn** [MirServer/mir#980]
This can be reproduced most easily with [swaybg](https://github.com/swaywm/swaybg) and [mirco](https://github.com/wmww/mirco/) and two virtual monitors with `--x11-output 1024x768:1024x768`.

After starting swaybg, notice in its how it correctly creates two windows but both of them ends up on the first monitor making it seem like only one was rendered.

I have also confirmed that `output_id()` of the `WindowSpecification` passed to `place_new_window` is always `0` and `top_left` are equal as well.

I assume that this is the problem:
https://github.com/MirServer/mir/blob/master/src/server/frontend_wayland/layer_shell_v1.cpp#L202

**Comment by wmww** [comment]
Yes, this is still and incomplete part of our Layer Shell implementation. I'll try to get to this within the next two weeks.

**Comment by Pajn** [comment]
With both #982 and #984 merged I can no longer find any issues with specifying output.
