### ISSUE TITLE
FTBFS (LP, 16.04)

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#986]
Lots of tests failing with:
```
ERROR:src/umockdev.c:4991:umockdev_testbed_create_node_for_device: assertion failed: (Linux.openpty (out ptym, out ptys, ptyname_array, null, null) == 0)
```
https://launchpadlibrarian.net/440767195/buildlog_ubuntu-xenial-i386.mir_1.4.0+dev27-gec9eecf303-0ubuntu16.04_BUILDING.txt.gz

https://launchpadlibrarian.net/440767281/buildlog_ubuntu-xenial-amd64.mir_1.4.0+dev27-gec9eecf303-0ubuntu16.04_BUILDING.txt.gz

https://launchpadlibrarian.net/440774115/buildlog_ubuntu-xenial-armhf.mir_1.4.0+dev27-gec9eecf303-0ubuntu16.04_BUILDING.txt.gz

https://launchpadlibrarian.net/440775305/buildlog_ubuntu-xenial-arm64.mir_1.4.0+dev27-gec9eecf303-0ubuntu16.04_BUILDING.txt.gz

**Comment by AlanGriffiths** [comment]
Not been able to reproduce locally.

**Comment by AlanGriffiths** [comment]
@RAOF I'm failing to reproduce what the PPA build is doing. Not sure what I've missed: could I get you to try?

**Comment by RAOF** [comment]
I also cannot get this to fail in this way, although this apparently fails reproducibly in the PPA. Maybe it's a LP builder kernel issue?

**Comment by RAOF** [comment]
Reproduced with the Xenial kernel in an sbuild chroot; passed on to Colin Watson, who's made a change to the LP chroot builder.

**Comment by AlanGriffiths** [comment]
Working now
