### ISSUE TITLE
Race in BasicWindowManager::remove_surface()

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#993]
The `MultiRectRegionCorners/SurfaceWithInputRegions` WLCS tests (and maybe others) will occasionally fail with
```
Mir fatal error: Could not find surface to remove in miral::BasicWindowManager::remove_surface()
Aborted (core dumped)
```
It seems more common when the CPUs are stressed.

To reproduce:
1. Open a terminal
2. Run `while ~/code/wlcs/build/wlcs ~/code/mir/build/lib/miral_wlcs_integration.so --gtest_filter='MultiRectRegionCorners/SurfaceWithInputRegions*'; do echo and again; done` (with your WLCS and Mir locations, obviously)
3. Repeat in new terminals until you're at 100 CPU
4. Wait for one of them to crash

**Comment by AlanGriffiths** [comment]
Seems to be fixed now. (Likely by  #1156 and/or #1177)
